-- CreateTable
CREATE TABLE "REFRESH_TOKENS" (
    "ID" SERIAL NOT NULL,
    "TOKEN_HASH" VARCHAR(255) NOT NULL,
    "USER_ID" INTEGER NOT NULL,
    "EXPIRES_AT" TIMESTAMP(3) NOT NULL,
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "REVOKED_AT" TIMESTAMP(3),

    CONSTRAINT "REFRESH_TOKENS_pkey" PRIMARY KEY ("ID")
);

-- CreateIndex
CREATE UNIQUE INDEX "REFRESH_TOKENS_TOKEN_HASH_key" ON "REFRESH_TOKENS"("TOKEN_HASH");

-- CreateIndex
CREATE INDEX "REFRESH_TOKENS_USER_ID_idx" ON "REFRESH_TOKENS"("USER_ID");

-- AddForeignKey
ALTER TABLE "REFRESH_TOKENS" ADD CONSTRAINT "REFRESH_TOKENS_USER_ID_fkey" FOREIGN KEY ("USER_ID") REFERENCES "USERS"("USER_ID") ON DELETE CASCADE ON UPDATE CASCADE;
