-- HR modules Phases B–E (employees, attendance, leave, performance, payroll)

CREATE TABLE IF NOT EXISTS "HR_EMPLOYEES" (
    "EMPLOYEE_ID" SERIAL NOT NULL,
    "EMPLOYEE_NO" VARCHAR(40) NOT NULL,
    "USER_ID" INTEGER,
    "FIRST_NAME" VARCHAR(100) NOT NULL,
    "LAST_NAME" VARCHAR(100) NOT NULL,
    "EMAIL" VARCHAR(255),
    "PHONE" VARCHAR(50),
    "DEPARTMENT_ID" INTEGER,
    "DEPARTMENT_NAME" VARCHAR(150),
    "DESIGNATION" VARCHAR(150),
    "GRADE_LEVEL" VARCHAR(50),
    "CADRE" VARCHAR(100),
    "EMPLOYMENT_TYPE" VARCHAR(30) NOT NULL DEFAULT 'Permanent',
    "STATUS" VARCHAR(30) NOT NULL DEFAULT 'Active',
    "DATE_JOINED" DATE,
    "DATE_OF_BIRTH" DATE,
    "EXPECTED_RETIRE_DATE" DATE,
    "DATE_LEFT" DATE,
    "QUALIFICATIONS" TEXT,
    "CERTIFICATIONS" TEXT,
    "LICENSE_NO" VARCHAR(100),
    "LICENSE_EXPIRY" DATE,
    "NEXT_OF_KIN" VARCHAR(255),
    "NEXT_OF_KIN_PHONE" VARCHAR(50),
    "EMERGENCY_CONTACT" VARCHAR(255),
    "EMERGENCY_PHONE" VARCHAR(50),
    "EMPLOYMENT_HISTORY" TEXT,
    "BASE_SALARY" DECIMAL(14,2),
    "CREATED_BY_ID" INTEGER,
    "CREATED_BY" VARCHAR(100),
    "CREATED_DATE" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_BY_ID" INTEGER,
    "UPDATED_BY" VARCHAR(100),
    "UPDATED_DATE" TIMESTAMP(3),
    CONSTRAINT "HR_EMPLOYEES_pkey" PRIMARY KEY ("EMPLOYEE_ID")
);

CREATE UNIQUE INDEX IF NOT EXISTS "HR_EMPLOYEES_EMPLOYEE_NO_key" ON "HR_EMPLOYEES"("EMPLOYEE_NO");
CREATE UNIQUE INDEX IF NOT EXISTS "HR_EMPLOYEES_USER_ID_key" ON "HR_EMPLOYEES"("USER_ID");
CREATE INDEX IF NOT EXISTS "HR_EMPLOYEES_STATUS_idx" ON "HR_EMPLOYEES"("STATUS");
CREATE INDEX IF NOT EXISTS "HR_EMPLOYEES_DEPARTMENT_ID_idx" ON "HR_EMPLOYEES"("DEPARTMENT_ID");
CREATE INDEX IF NOT EXISTS "HR_EMPLOYEES_EMPLOYMENT_TYPE_idx" ON "HR_EMPLOYEES"("EMPLOYMENT_TYPE");
CREATE INDEX IF NOT EXISTS "HR_EMPLOYEES_DEPARTMENT_NAME_idx" ON "HR_EMPLOYEES"("DEPARTMENT_NAME");

CREATE TABLE IF NOT EXISTS "HR_LEAVE_TYPES" (
    "LEAVE_TYPE_ID" SERIAL NOT NULL,
    "CODE" VARCHAR(40) NOT NULL,
    "NAME" VARCHAR(100) NOT NULL,
    "DAYS_PER_YEAR" INTEGER NOT NULL DEFAULT 0,
    "IS_ACTIVE" BOOLEAN NOT NULL DEFAULT true,
    CONSTRAINT "HR_LEAVE_TYPES_pkey" PRIMARY KEY ("LEAVE_TYPE_ID")
);
CREATE UNIQUE INDEX IF NOT EXISTS "HR_LEAVE_TYPES_CODE_key" ON "HR_LEAVE_TYPES"("CODE");

INSERT INTO "HR_LEAVE_TYPES" ("CODE", "NAME", "DAYS_PER_YEAR", "IS_ACTIVE")
VALUES
  ('ANNUAL', 'Annual', 30, true),
  ('SICK', 'Sick', 15, true),
  ('MATERNITY', 'Maternity', 90, true),
  ('CASUAL', 'Casual', 7, true),
  ('STUDY', 'Study', 10, true),
  ('OTHER', 'Other', 0, true)
ON CONFLICT ("CODE") DO NOTHING;

CREATE TABLE IF NOT EXISTS "HR_ATTENDANCE" (
    "ATTENDANCE_ID" SERIAL NOT NULL,
    "EMPLOYEE_ID" INTEGER NOT NULL,
    "WORK_DATE" DATE NOT NULL,
    "CHECK_IN" TIMESTAMP(3),
    "CHECK_OUT" TIMESTAMP(3),
    "STATUS" VARCHAR(30) NOT NULL DEFAULT 'Present',
    "SHIFT" VARCHAR(40),
    "NOTES" TEXT,
    "CREATED_BY_ID" INTEGER,
    "CREATED_BY" VARCHAR(100),
    "CREATED_DATE" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_BY_ID" INTEGER,
    "UPDATED_BY" VARCHAR(100),
    "UPDATED_DATE" TIMESTAMP(3),
    CONSTRAINT "HR_ATTENDANCE_pkey" PRIMARY KEY ("ATTENDANCE_ID"),
    CONSTRAINT "HR_ATTENDANCE_EMPLOYEE_ID_fkey" FOREIGN KEY ("EMPLOYEE_ID") REFERENCES "HR_EMPLOYEES"("EMPLOYEE_ID") ON DELETE RESTRICT ON UPDATE CASCADE
);
CREATE UNIQUE INDEX IF NOT EXISTS "HR_ATTENDANCE_EMPLOYEE_ID_WORK_DATE_key" ON "HR_ATTENDANCE"("EMPLOYEE_ID", "WORK_DATE");
CREATE INDEX IF NOT EXISTS "HR_ATTENDANCE_WORK_DATE_idx" ON "HR_ATTENDANCE"("WORK_DATE");
CREATE INDEX IF NOT EXISTS "HR_ATTENDANCE_STATUS_idx" ON "HR_ATTENDANCE"("STATUS");

CREATE TABLE IF NOT EXISTS "HR_LEAVE_REQUESTS" (
    "LEAVE_ID" SERIAL NOT NULL,
    "EMPLOYEE_ID" INTEGER NOT NULL,
    "LEAVE_TYPE_ID" INTEGER,
    "LEAVE_TYPE" VARCHAR(40) NOT NULL,
    "START_DATE" DATE NOT NULL,
    "END_DATE" DATE NOT NULL,
    "DAYS" DECIMAL(6,1) NOT NULL,
    "REASON" TEXT,
    "STATUS" VARCHAR(30) NOT NULL DEFAULT 'Pending',
    "APPROVED_BY_ID" INTEGER,
    "APPROVED_BY" VARCHAR(100),
    "APPROVED_AT" TIMESTAMP(3),
    "DECISION_NOTE" TEXT,
    "CREATED_BY_ID" INTEGER,
    "CREATED_BY" VARCHAR(100),
    "CREATED_DATE" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_BY_ID" INTEGER,
    "UPDATED_BY" VARCHAR(100),
    "UPDATED_DATE" TIMESTAMP(3),
    CONSTRAINT "HR_LEAVE_REQUESTS_pkey" PRIMARY KEY ("LEAVE_ID"),
    CONSTRAINT "HR_LEAVE_REQUESTS_EMPLOYEE_ID_fkey" FOREIGN KEY ("EMPLOYEE_ID") REFERENCES "HR_EMPLOYEES"("EMPLOYEE_ID") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "HR_LEAVE_REQUESTS_LEAVE_TYPE_ID_fkey" FOREIGN KEY ("LEAVE_TYPE_ID") REFERENCES "HR_LEAVE_TYPES"("LEAVE_TYPE_ID") ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE INDEX IF NOT EXISTS "HR_LEAVE_REQUESTS_EMPLOYEE_ID_idx" ON "HR_LEAVE_REQUESTS"("EMPLOYEE_ID");
CREATE INDEX IF NOT EXISTS "HR_LEAVE_REQUESTS_STATUS_idx" ON "HR_LEAVE_REQUESTS"("STATUS");
CREATE INDEX IF NOT EXISTS "HR_LEAVE_REQUESTS_START_DATE_END_DATE_idx" ON "HR_LEAVE_REQUESTS"("START_DATE", "END_DATE");

CREATE TABLE IF NOT EXISTS "HR_APPRAISALS" (
    "APPRAISAL_ID" SERIAL NOT NULL,
    "EMPLOYEE_ID" INTEGER NOT NULL,
    "PERIOD_LABEL" VARCHAR(40) NOT NULL,
    "ATTENDANCE_SCORE" INTEGER NOT NULL DEFAULT 0,
    "PRODUCTIVITY_SCORE" INTEGER NOT NULL DEFAULT 0,
    "EFFICIENCY_SCORE" INTEGER NOT NULL DEFAULT 0,
    "COMPLIANCE_SCORE" INTEGER NOT NULL DEFAULT 0,
    "PERFORMANCE_SCORE" INTEGER NOT NULL DEFAULT 0,
    "BAND" VARCHAR(30),
    "COMMENTS" TEXT,
    "STATUS" VARCHAR(20) NOT NULL DEFAULT 'Draft',
    "REVIEWER_ID" INTEGER,
    "REVIEWER_NAME" VARCHAR(150),
    "CREATED_BY_ID" INTEGER,
    "CREATED_BY" VARCHAR(100),
    "CREATED_DATE" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_BY_ID" INTEGER,
    "UPDATED_BY" VARCHAR(100),
    "UPDATED_DATE" TIMESTAMP(3),
    CONSTRAINT "HR_APPRAISALS_pkey" PRIMARY KEY ("APPRAISAL_ID"),
    CONSTRAINT "HR_APPRAISALS_EMPLOYEE_ID_fkey" FOREIGN KEY ("EMPLOYEE_ID") REFERENCES "HR_EMPLOYEES"("EMPLOYEE_ID") ON DELETE RESTRICT ON UPDATE CASCADE
);
CREATE INDEX IF NOT EXISTS "HR_APPRAISALS_EMPLOYEE_ID_idx" ON "HR_APPRAISALS"("EMPLOYEE_ID");
CREATE INDEX IF NOT EXISTS "HR_APPRAISALS_PERIOD_LABEL_idx" ON "HR_APPRAISALS"("PERIOD_LABEL");

CREATE TABLE IF NOT EXISTS "HR_DISCIPLINARY" (
    "CASE_ID" SERIAL NOT NULL,
    "EMPLOYEE_ID" INTEGER NOT NULL,
    "TITLE" VARCHAR(200) NOT NULL,
    "DESCRIPTION" TEXT,
    "STATUS" VARCHAR(30) NOT NULL DEFAULT 'Open',
    "SEVERITY" VARCHAR(30),
    "OUTCOME" TEXT,
    "OPENED_DATE" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "CLOSED_DATE" TIMESTAMP(3),
    "CREATED_BY_ID" INTEGER,
    "CREATED_BY" VARCHAR(100),
    "CREATED_DATE" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_BY_ID" INTEGER,
    "UPDATED_BY" VARCHAR(100),
    "UPDATED_DATE" TIMESTAMP(3),
    CONSTRAINT "HR_DISCIPLINARY_pkey" PRIMARY KEY ("CASE_ID"),
    CONSTRAINT "HR_DISCIPLINARY_EMPLOYEE_ID_fkey" FOREIGN KEY ("EMPLOYEE_ID") REFERENCES "HR_EMPLOYEES"("EMPLOYEE_ID") ON DELETE RESTRICT ON UPDATE CASCADE
);
CREATE INDEX IF NOT EXISTS "HR_DISCIPLINARY_EMPLOYEE_ID_idx" ON "HR_DISCIPLINARY"("EMPLOYEE_ID");
CREATE INDEX IF NOT EXISTS "HR_DISCIPLINARY_STATUS_idx" ON "HR_DISCIPLINARY"("STATUS");

CREATE TABLE IF NOT EXISTS "HR_DOCUMENTS" (
    "DOCUMENT_ID" SERIAL NOT NULL,
    "EMPLOYEE_ID" INTEGER NOT NULL,
    "TITLE" VARCHAR(200) NOT NULL,
    "DOC_TYPE" VARCHAR(80),
    "FILE_URL" VARCHAR(500),
    "STORAGE_KEY" VARCHAR(255),
    "STATUS" VARCHAR(20) NOT NULL DEFAULT 'Active',
    "CREATED_BY_ID" INTEGER,
    "CREATED_BY" VARCHAR(100),
    "CREATED_DATE" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_BY_ID" INTEGER,
    "UPDATED_BY" VARCHAR(100),
    "UPDATED_DATE" TIMESTAMP(3),
    CONSTRAINT "HR_DOCUMENTS_pkey" PRIMARY KEY ("DOCUMENT_ID"),
    CONSTRAINT "HR_DOCUMENTS_EMPLOYEE_ID_fkey" FOREIGN KEY ("EMPLOYEE_ID") REFERENCES "HR_EMPLOYEES"("EMPLOYEE_ID") ON DELETE RESTRICT ON UPDATE CASCADE
);
CREATE INDEX IF NOT EXISTS "HR_DOCUMENTS_EMPLOYEE_ID_idx" ON "HR_DOCUMENTS"("EMPLOYEE_ID");
CREATE INDEX IF NOT EXISTS "HR_DOCUMENTS_STATUS_idx" ON "HR_DOCUMENTS"("STATUS");

CREATE TABLE IF NOT EXISTS "HR_PAYROLL_RUNS" (
    "RUN_ID" SERIAL NOT NULL,
    "PERIOD_YEAR" INTEGER NOT NULL,
    "PERIOD_MONTH" INTEGER NOT NULL,
    "STATUS" VARCHAR(20) NOT NULL DEFAULT 'Draft',
    "TOTAL_GROSS" DECIMAL(16,2) NOT NULL DEFAULT 0,
    "TOTAL_NET" DECIMAL(16,2) NOT NULL DEFAULT 0,
    "LOCKED_AT" TIMESTAMP(3),
    "LOCKED_BY_ID" INTEGER,
    "LOCKED_BY" VARCHAR(100),
    "CREATED_BY_ID" INTEGER,
    "CREATED_BY" VARCHAR(100),
    "CREATED_DATE" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_BY_ID" INTEGER,
    "UPDATED_BY" VARCHAR(100),
    "UPDATED_DATE" TIMESTAMP(3),
    CONSTRAINT "HR_PAYROLL_RUNS_pkey" PRIMARY KEY ("RUN_ID")
);
CREATE UNIQUE INDEX IF NOT EXISTS "HR_PAYROLL_RUNS_PERIOD_YEAR_PERIOD_MONTH_key" ON "HR_PAYROLL_RUNS"("PERIOD_YEAR", "PERIOD_MONTH");
CREATE INDEX IF NOT EXISTS "HR_PAYROLL_RUNS_STATUS_idx" ON "HR_PAYROLL_RUNS"("STATUS");

CREATE TABLE IF NOT EXISTS "HR_PAYROLL_LINES" (
    "LINE_ID" SERIAL NOT NULL,
    "RUN_ID" INTEGER NOT NULL,
    "EMPLOYEE_ID" INTEGER NOT NULL,
    "BASIC" DECIMAL(14,2) NOT NULL DEFAULT 0,
    "ALLOWANCES" DECIMAL(14,2) NOT NULL DEFAULT 0,
    "DEDUCTIONS" DECIMAL(14,2) NOT NULL DEFAULT 0,
    "PAYE" DECIMAL(14,2) NOT NULL DEFAULT 0,
    "PENSION" DECIMAL(14,2) NOT NULL DEFAULT 0,
    "NET_PAY" DECIMAL(14,2) NOT NULL DEFAULT 0,
    "STATUS" VARCHAR(20) NOT NULL DEFAULT 'Pending',
    CONSTRAINT "HR_PAYROLL_LINES_pkey" PRIMARY KEY ("LINE_ID"),
    CONSTRAINT "HR_PAYROLL_LINES_RUN_ID_fkey" FOREIGN KEY ("RUN_ID") REFERENCES "HR_PAYROLL_RUNS"("RUN_ID") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "HR_PAYROLL_LINES_EMPLOYEE_ID_fkey" FOREIGN KEY ("EMPLOYEE_ID") REFERENCES "HR_EMPLOYEES"("EMPLOYEE_ID") ON DELETE RESTRICT ON UPDATE CASCADE
);
CREATE UNIQUE INDEX IF NOT EXISTS "HR_PAYROLL_LINES_RUN_ID_EMPLOYEE_ID_key" ON "HR_PAYROLL_LINES"("RUN_ID", "EMPLOYEE_ID");
CREATE INDEX IF NOT EXISTS "HR_PAYROLL_LINES_EMPLOYEE_ID_idx" ON "HR_PAYROLL_LINES"("EMPLOYEE_ID");
