-- Add SOURCE to LAB_REQUESTS (Doctor | WalkIn)

ALTER TABLE "LAB_REQUESTS" ADD COLUMN IF NOT EXISTS "SOURCE" VARCHAR(50) NOT NULL DEFAULT 'Doctor';

CREATE INDEX IF NOT EXISTS "LAB_REQUESTS_SOURCE_idx" ON "LAB_REQUESTS"("SOURCE");
