-- HMO Integration Broker tables + Persons.HMO_ID FK to SERVICE_PAYERS

-- Null orphan HMO_ID values that do not match an existing payer
UPDATE "PERSONS" SET "HMO_ID" = NULL
WHERE "HMO_ID" IS NOT NULL
  AND NOT EXISTS (
    SELECT 1 FROM "SERVICE_PAYERS" sp WHERE sp."PAYER_ID" = "PERSONS"."HMO_ID"
  );

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'PERSONS_HMO_ID_fkey'
  ) THEN
    ALTER TABLE "PERSONS"
      ADD CONSTRAINT "PERSONS_HMO_ID_fkey"
      FOREIGN KEY ("HMO_ID") REFERENCES "SERVICE_PAYERS"("PAYER_ID")
      ON DELETE SET NULL ON UPDATE CASCADE;
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS "HMO_INTEGRATION_PROFILES" (
    "PROFILE_ID" SERIAL NOT NULL,
    "PAYER_ID" INTEGER NOT NULL,
    "ADAPTER_KEY" VARCHAR(40) NOT NULL,
    "STATUS" VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    "BASE_URL" VARCHAR(500),
    "CAPABILITIES" JSONB,
    "METADATA" JSONB,
    "CHECKLIST" JSONB,
    "CREATED_BY" VARCHAR(100),
    "CREATED_DATE" TIMESTAMP(3),
    "UPDATED_BY" VARCHAR(100),
    "UPDATED_DATE" TIMESTAMP(3),
    CONSTRAINT "HMO_INTEGRATION_PROFILES_pkey" PRIMARY KEY ("PROFILE_ID")
);

CREATE UNIQUE INDEX IF NOT EXISTS "HMO_INTEGRATION_PROFILES_PAYER_ID_key" ON "HMO_INTEGRATION_PROFILES"("PAYER_ID");
CREATE INDEX IF NOT EXISTS "HMO_INTEGRATION_PROFILES_ADAPTER_KEY_idx" ON "HMO_INTEGRATION_PROFILES"("ADAPTER_KEY");
CREATE INDEX IF NOT EXISTS "HMO_INTEGRATION_PROFILES_STATUS_idx" ON "HMO_INTEGRATION_PROFILES"("STATUS");

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'HMO_INTEGRATION_PROFILES_PAYER_ID_fkey'
  ) THEN
    ALTER TABLE "HMO_INTEGRATION_PROFILES"
      ADD CONSTRAINT "HMO_INTEGRATION_PROFILES_PAYER_ID_fkey"
      FOREIGN KEY ("PAYER_ID") REFERENCES "SERVICE_PAYERS"("PAYER_ID")
      ON DELETE RESTRICT ON UPDATE CASCADE;
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS "HMO_INTEGRATION_CREDENTIALS" (
    "CREDENTIAL_ID" SERIAL NOT NULL,
    "PROFILE_ID" INTEGER NOT NULL,
    "BRANCH_ID" INTEGER,
    "ENCRYPTED_BLOB" TEXT NOT NULL,
    "LABEL" VARCHAR(100),
    "STATUS" VARCHAR(20) NOT NULL DEFAULT 'Active',
    "CREATED_BY" VARCHAR(100),
    "CREATED_DATE" TIMESTAMP(3),
    "UPDATED_BY" VARCHAR(100),
    "UPDATED_DATE" TIMESTAMP(3),
    CONSTRAINT "HMO_INTEGRATION_CREDENTIALS_pkey" PRIMARY KEY ("CREDENTIAL_ID")
);

CREATE INDEX IF NOT EXISTS "HMO_INTEGRATION_CREDENTIALS_PROFILE_ID_idx" ON "HMO_INTEGRATION_CREDENTIALS"("PROFILE_ID");
CREATE INDEX IF NOT EXISTS "HMO_INTEGRATION_CREDENTIALS_BRANCH_ID_idx" ON "HMO_INTEGRATION_CREDENTIALS"("BRANCH_ID");
CREATE INDEX IF NOT EXISTS "HMO_INTEGRATION_CREDENTIALS_STATUS_idx" ON "HMO_INTEGRATION_CREDENTIALS"("STATUS");

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'HMO_INTEGRATION_CREDENTIALS_PROFILE_ID_fkey'
  ) THEN
    ALTER TABLE "HMO_INTEGRATION_CREDENTIALS"
      ADD CONSTRAINT "HMO_INTEGRATION_CREDENTIALS_PROFILE_ID_fkey"
      FOREIGN KEY ("PROFILE_ID") REFERENCES "HMO_INTEGRATION_PROFILES"("PROFILE_ID")
      ON DELETE CASCADE ON UPDATE CASCADE;
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS "PATIENT_HMO_COVERAGE" (
    "COVERAGE_ID" SERIAL NOT NULL,
    "PERSON_ID" INTEGER NOT NULL,
    "PAYER_ID" INTEGER NOT NULL,
    "MEMBER_NO" VARCHAR(80) NOT NULL,
    "PLAN_CODE" VARCHAR(60),
    "PLAN_NAME" VARCHAR(150),
    "EMPLOYER_NAME" VARCHAR(255),
    "PRINCIPAL_FLAG" VARCHAR(10),
    "VALID_FROM" TIMESTAMP(3),
    "VALID_TO" TIMESTAMP(3),
    "STATUS" VARCHAR(20) NOT NULL DEFAULT 'Active',
    "EXTERNAL_REF" VARCHAR(120),
    "CREATED_BY" VARCHAR(100),
    "CREATED_DATE" TIMESTAMP(3),
    "UPDATED_BY" VARCHAR(100),
    "UPDATED_DATE" TIMESTAMP(3),
    CONSTRAINT "PATIENT_HMO_COVERAGE_pkey" PRIMARY KEY ("COVERAGE_ID")
);

CREATE INDEX IF NOT EXISTS "PATIENT_HMO_COVERAGE_PERSON_ID_idx" ON "PATIENT_HMO_COVERAGE"("PERSON_ID");
CREATE INDEX IF NOT EXISTS "PATIENT_HMO_COVERAGE_PAYER_ID_idx" ON "PATIENT_HMO_COVERAGE"("PAYER_ID");
CREATE INDEX IF NOT EXISTS "PATIENT_HMO_COVERAGE_MEMBER_NO_idx" ON "PATIENT_HMO_COVERAGE"("MEMBER_NO");
CREATE INDEX IF NOT EXISTS "PATIENT_HMO_COVERAGE_STATUS_idx" ON "PATIENT_HMO_COVERAGE"("STATUS");
CREATE INDEX IF NOT EXISTS "PATIENT_HMO_COVERAGE_PERSON_ID_PAYER_ID_STATUS_idx" ON "PATIENT_HMO_COVERAGE"("PERSON_ID", "PAYER_ID", "STATUS");

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'PATIENT_HMO_COVERAGE_PERSON_ID_fkey'
  ) THEN
    ALTER TABLE "PATIENT_HMO_COVERAGE"
      ADD CONSTRAINT "PATIENT_HMO_COVERAGE_PERSON_ID_fkey"
      FOREIGN KEY ("PERSON_ID") REFERENCES "PERSONS"("PERSON_ID")
      ON DELETE RESTRICT ON UPDATE CASCADE;
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'PATIENT_HMO_COVERAGE_PAYER_ID_fkey'
  ) THEN
    ALTER TABLE "PATIENT_HMO_COVERAGE"
      ADD CONSTRAINT "PATIENT_HMO_COVERAGE_PAYER_ID_fkey"
      FOREIGN KEY ("PAYER_ID") REFERENCES "SERVICE_PAYERS"("PAYER_ID")
      ON DELETE RESTRICT ON UPDATE CASCADE;
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS "HMO_ELIGIBILITY_CHECKS" (
    "CHECK_ID" SERIAL NOT NULL,
    "PERSON_ID" INTEGER NOT NULL,
    "PAYER_ID" INTEGER NOT NULL,
    "COVERAGE_ID" INTEGER,
    "ENCOUNTER_ID" INTEGER,
    "MEMBER_NO" VARCHAR(80) NOT NULL,
    "STATUS" VARCHAR(20) NOT NULL,
    "MEMBER_NAME" VARCHAR(255),
    "MEMBER_DOB" TIMESTAMP(3),
    "MEMBER_GENDER" VARCHAR(20),
    "PHOTO_URL" VARCHAR(500),
    "PLAN_CODE" VARCHAR(60),
    "PLAN_NAME" VARCHAR(150),
    "EMPLOYER_NAME" VARCHAR(255),
    "VALID_FROM" TIMESTAMP(3),
    "VALID_TO" TIMESTAMP(3),
    "SOURCE_ADAPTER" VARCHAR(40) NOT NULL,
    "EXTERNAL_REF" VARCHAR(120),
    "RAW_RESPONSE" JSONB,
    "VERIFIED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "VERIFIED_BY" VARCHAR(100),
    "CREATED_DATE" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "HMO_ELIGIBILITY_CHECKS_pkey" PRIMARY KEY ("CHECK_ID")
);

CREATE INDEX IF NOT EXISTS "HMO_ELIGIBILITY_CHECKS_PERSON_ID_idx" ON "HMO_ELIGIBILITY_CHECKS"("PERSON_ID");
CREATE INDEX IF NOT EXISTS "HMO_ELIGIBILITY_CHECKS_PAYER_ID_idx" ON "HMO_ELIGIBILITY_CHECKS"("PAYER_ID");
CREATE INDEX IF NOT EXISTS "HMO_ELIGIBILITY_CHECKS_ENCOUNTER_ID_idx" ON "HMO_ELIGIBILITY_CHECKS"("ENCOUNTER_ID");
CREATE INDEX IF NOT EXISTS "HMO_ELIGIBILITY_CHECKS_STATUS_idx" ON "HMO_ELIGIBILITY_CHECKS"("STATUS");
CREATE INDEX IF NOT EXISTS "HMO_ELIGIBILITY_CHECKS_VERIFIED_AT_idx" ON "HMO_ELIGIBILITY_CHECKS"("VERIFIED_AT");

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'HMO_ELIGIBILITY_CHECKS_PERSON_ID_fkey'
  ) THEN
    ALTER TABLE "HMO_ELIGIBILITY_CHECKS"
      ADD CONSTRAINT "HMO_ELIGIBILITY_CHECKS_PERSON_ID_fkey"
      FOREIGN KEY ("PERSON_ID") REFERENCES "PERSONS"("PERSON_ID")
      ON DELETE RESTRICT ON UPDATE CASCADE;
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'HMO_ELIGIBILITY_CHECKS_PAYER_ID_fkey'
  ) THEN
    ALTER TABLE "HMO_ELIGIBILITY_CHECKS"
      ADD CONSTRAINT "HMO_ELIGIBILITY_CHECKS_PAYER_ID_fkey"
      FOREIGN KEY ("PAYER_ID") REFERENCES "SERVICE_PAYERS"("PAYER_ID")
      ON DELETE RESTRICT ON UPDATE CASCADE;
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS "HMO_BENEFIT_SNAPSHOTS" (
    "SNAPSHOT_ID" SERIAL NOT NULL,
    "PERSON_ID" INTEGER NOT NULL,
    "PAYER_ID" INTEGER NOT NULL,
    "MEMBER_NO" VARCHAR(80) NOT NULL,
    "PLAN_CODE" VARCHAR(60),
    "PLAN_NAME" VARCHAR(150),
    "BENEFITS" JSONB NOT NULL,
    "EXCLUSIONS" JSONB,
    "SOURCE_ADAPTER" VARCHAR(40) NOT NULL,
    "FETCHED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "EXPIRES_AT" TIMESTAMP(3),
    "CREATED_DATE" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "HMO_BENEFIT_SNAPSHOTS_pkey" PRIMARY KEY ("SNAPSHOT_ID")
);

CREATE INDEX IF NOT EXISTS "HMO_BENEFIT_SNAPSHOTS_PERSON_ID_PAYER_ID_idx" ON "HMO_BENEFIT_SNAPSHOTS"("PERSON_ID", "PAYER_ID");
CREATE INDEX IF NOT EXISTS "HMO_BENEFIT_SNAPSHOTS_EXPIRES_AT_idx" ON "HMO_BENEFIT_SNAPSHOTS"("EXPIRES_AT");

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'HMO_BENEFIT_SNAPSHOTS_PERSON_ID_fkey'
  ) THEN
    ALTER TABLE "HMO_BENEFIT_SNAPSHOTS"
      ADD CONSTRAINT "HMO_BENEFIT_SNAPSHOTS_PERSON_ID_fkey"
      FOREIGN KEY ("PERSON_ID") REFERENCES "PERSONS"("PERSON_ID")
      ON DELETE RESTRICT ON UPDATE CASCADE;
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'HMO_BENEFIT_SNAPSHOTS_PAYER_ID_fkey'
  ) THEN
    ALTER TABLE "HMO_BENEFIT_SNAPSHOTS"
      ADD CONSTRAINT "HMO_BENEFIT_SNAPSHOTS_PAYER_ID_fkey"
      FOREIGN KEY ("PAYER_ID") REFERENCES "SERVICE_PAYERS"("PAYER_ID")
      ON DELETE RESTRICT ON UPDATE CASCADE;
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS "HMO_AUTHORIZATIONS" (
    "AUTH_ID" SERIAL NOT NULL,
    "PERSON_ID" INTEGER NOT NULL,
    "PAYER_ID" INTEGER NOT NULL,
    "ENCOUNTER_ID" INTEGER,
    "ADMISSION_ID" INTEGER,
    "MEMBER_NO" VARCHAR(80) NOT NULL,
    "DIAGNOSIS_CODES" JSONB,
    "PROCEDURE_CODES" JSONB,
    "SERVICE_CODES" JSONB,
    "ESTIMATED_AMOUNT" DECIMAL(14,2),
    "APPROVED_AMOUNT" DECIMAL(14,2),
    "STATUS" VARCHAR(20) NOT NULL,
    "AUTH_CODE" VARCHAR(80),
    "EXTERNAL_REF" VARCHAR(120),
    "VALID_UNTIL" TIMESTAMP(3),
    "NOTES" TEXT,
    "SOURCE_ADAPTER" VARCHAR(40) NOT NULL,
    "IDEMPOTENCY_KEY" VARCHAR(80),
    "RAW_RESPONSE" JSONB,
    "REQUESTED_BY" VARCHAR(100),
    "REQUESTED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3),
    "CREATED_DATE" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "HMO_AUTHORIZATIONS_pkey" PRIMARY KEY ("AUTH_ID")
);

CREATE UNIQUE INDEX IF NOT EXISTS "HMO_AUTHORIZATIONS_IDEMPOTENCY_KEY_key" ON "HMO_AUTHORIZATIONS"("IDEMPOTENCY_KEY");
CREATE INDEX IF NOT EXISTS "HMO_AUTHORIZATIONS_PERSON_ID_idx" ON "HMO_AUTHORIZATIONS"("PERSON_ID");
CREATE INDEX IF NOT EXISTS "HMO_AUTHORIZATIONS_PAYER_ID_idx" ON "HMO_AUTHORIZATIONS"("PAYER_ID");
CREATE INDEX IF NOT EXISTS "HMO_AUTHORIZATIONS_STATUS_idx" ON "HMO_AUTHORIZATIONS"("STATUS");
CREATE INDEX IF NOT EXISTS "HMO_AUTHORIZATIONS_AUTH_CODE_idx" ON "HMO_AUTHORIZATIONS"("AUTH_CODE");
CREATE INDEX IF NOT EXISTS "HMO_AUTHORIZATIONS_EXTERNAL_REF_idx" ON "HMO_AUTHORIZATIONS"("EXTERNAL_REF");

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'HMO_AUTHORIZATIONS_PERSON_ID_fkey'
  ) THEN
    ALTER TABLE "HMO_AUTHORIZATIONS"
      ADD CONSTRAINT "HMO_AUTHORIZATIONS_PERSON_ID_fkey"
      FOREIGN KEY ("PERSON_ID") REFERENCES "PERSONS"("PERSON_ID")
      ON DELETE RESTRICT ON UPDATE CASCADE;
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'HMO_AUTHORIZATIONS_PAYER_ID_fkey'
  ) THEN
    ALTER TABLE "HMO_AUTHORIZATIONS"
      ADD CONSTRAINT "HMO_AUTHORIZATIONS_PAYER_ID_fkey"
      FOREIGN KEY ("PAYER_ID") REFERENCES "SERVICE_PAYERS"("PAYER_ID")
      ON DELETE RESTRICT ON UPDATE CASCADE;
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS "HMO_AUTHORIZATION_LINES" (
    "LINE_ID" SERIAL NOT NULL,
    "AUTH_ID" INTEGER NOT NULL,
    "SERVICE_CODE" VARCHAR(50),
    "DESCRIPTION" VARCHAR(255),
    "QUANTITY" INTEGER DEFAULT 1,
    "UNIT_AMOUNT" DECIMAL(14,2),
    "STATUS" VARCHAR(20),
    CONSTRAINT "HMO_AUTHORIZATION_LINES_pkey" PRIMARY KEY ("LINE_ID")
);

CREATE INDEX IF NOT EXISTS "HMO_AUTHORIZATION_LINES_AUTH_ID_idx" ON "HMO_AUTHORIZATION_LINES"("AUTH_ID");

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'HMO_AUTHORIZATION_LINES_AUTH_ID_fkey'
  ) THEN
    ALTER TABLE "HMO_AUTHORIZATION_LINES"
      ADD CONSTRAINT "HMO_AUTHORIZATION_LINES_AUTH_ID_fkey"
      FOREIGN KEY ("AUTH_ID") REFERENCES "HMO_AUTHORIZATIONS"("AUTH_ID")
      ON DELETE CASCADE ON UPDATE CASCADE;
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS "HMO_CLAIMS" (
    "CLAIM_ID" SERIAL NOT NULL,
    "PERSON_ID" INTEGER NOT NULL,
    "PAYER_ID" INTEGER NOT NULL,
    "AUTH_ID" INTEGER,
    "ENCOUNTER_ID" INTEGER,
    "ADMISSION_ID" INTEGER,
    "MEMBER_NO" VARCHAR(80) NOT NULL,
    "STATUS" VARCHAR(20) NOT NULL,
    "EXTERNAL_CLAIM_REF" VARCHAR(120),
    "TOTAL_AMOUNT" DECIMAL(14,2) NOT NULL,
    "PAYER_AMOUNT" DECIMAL(14,2),
    "PATIENT_AMOUNT" DECIMAL(14,2),
    "CURRENCY" VARCHAR(10) NOT NULL DEFAULT 'NGN',
    "DIAGNOSIS_CODES" JSONB,
    "VALIDATION_ERRORS" JSONB,
    "SOURCE_ADAPTER" VARCHAR(40) NOT NULL,
    "IDEMPOTENCY_KEY" VARCHAR(80),
    "RAW_RESPONSE" JSONB,
    "SUBMITTED_BY" VARCHAR(100),
    "SUBMITTED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3),
    "CREATED_DATE" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "HMO_CLAIMS_pkey" PRIMARY KEY ("CLAIM_ID")
);

CREATE UNIQUE INDEX IF NOT EXISTS "HMO_CLAIMS_IDEMPOTENCY_KEY_key" ON "HMO_CLAIMS"("IDEMPOTENCY_KEY");
CREATE INDEX IF NOT EXISTS "HMO_CLAIMS_PERSON_ID_idx" ON "HMO_CLAIMS"("PERSON_ID");
CREATE INDEX IF NOT EXISTS "HMO_CLAIMS_PAYER_ID_idx" ON "HMO_CLAIMS"("PAYER_ID");
CREATE INDEX IF NOT EXISTS "HMO_CLAIMS_STATUS_idx" ON "HMO_CLAIMS"("STATUS");
CREATE INDEX IF NOT EXISTS "HMO_CLAIMS_EXTERNAL_CLAIM_REF_idx" ON "HMO_CLAIMS"("EXTERNAL_CLAIM_REF");
CREATE INDEX IF NOT EXISTS "HMO_CLAIMS_SUBMITTED_AT_idx" ON "HMO_CLAIMS"("SUBMITTED_AT");

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'HMO_CLAIMS_PERSON_ID_fkey'
  ) THEN
    ALTER TABLE "HMO_CLAIMS"
      ADD CONSTRAINT "HMO_CLAIMS_PERSON_ID_fkey"
      FOREIGN KEY ("PERSON_ID") REFERENCES "PERSONS"("PERSON_ID")
      ON DELETE RESTRICT ON UPDATE CASCADE;
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'HMO_CLAIMS_PAYER_ID_fkey'
  ) THEN
    ALTER TABLE "HMO_CLAIMS"
      ADD CONSTRAINT "HMO_CLAIMS_PAYER_ID_fkey"
      FOREIGN KEY ("PAYER_ID") REFERENCES "SERVICE_PAYERS"("PAYER_ID")
      ON DELETE RESTRICT ON UPDATE CASCADE;
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS "HMO_CLAIM_LINES" (
    "LINE_ID" SERIAL NOT NULL,
    "CLAIM_ID" INTEGER NOT NULL,
    "SERVICE_CODE" VARCHAR(50),
    "DESCRIPTION" VARCHAR(255),
    "QUANTITY" INTEGER DEFAULT 1,
    "UNIT_AMOUNT" DECIMAL(14,2),
    "PAYER_AMOUNT" DECIMAL(14,2),
    "PATIENT_AMOUNT" DECIMAL(14,2),
    "BILL_LINE_REF" VARCHAR(100),
    CONSTRAINT "HMO_CLAIM_LINES_pkey" PRIMARY KEY ("LINE_ID")
);

CREATE INDEX IF NOT EXISTS "HMO_CLAIM_LINES_CLAIM_ID_idx" ON "HMO_CLAIM_LINES"("CLAIM_ID");

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'HMO_CLAIM_LINES_CLAIM_ID_fkey'
  ) THEN
    ALTER TABLE "HMO_CLAIM_LINES"
      ADD CONSTRAINT "HMO_CLAIM_LINES_CLAIM_ID_fkey"
      FOREIGN KEY ("CLAIM_ID") REFERENCES "HMO_CLAIMS"("CLAIM_ID")
      ON DELETE CASCADE ON UPDATE CASCADE;
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS "HMO_CLAIM_STATUS_EVENTS" (
    "EVENT_ID" SERIAL NOT NULL,
    "CLAIM_ID" INTEGER NOT NULL,
    "FROM_STATUS" VARCHAR(20),
    "TO_STATUS" VARCHAR(20) NOT NULL,
    "MESSAGE" VARCHAR(500),
    "SOURCE" VARCHAR(40),
    "RAW_PAYLOAD" JSONB,
    "CREATED_BY" VARCHAR(100),
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "HMO_CLAIM_STATUS_EVENTS_pkey" PRIMARY KEY ("EVENT_ID")
);

CREATE INDEX IF NOT EXISTS "HMO_CLAIM_STATUS_EVENTS_CLAIM_ID_idx" ON "HMO_CLAIM_STATUS_EVENTS"("CLAIM_ID");
CREATE INDEX IF NOT EXISTS "HMO_CLAIM_STATUS_EVENTS_CREATED_AT_idx" ON "HMO_CLAIM_STATUS_EVENTS"("CREATED_AT");

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'HMO_CLAIM_STATUS_EVENTS_CLAIM_ID_fkey'
  ) THEN
    ALTER TABLE "HMO_CLAIM_STATUS_EVENTS"
      ADD CONSTRAINT "HMO_CLAIM_STATUS_EVENTS_CLAIM_ID_fkey"
      FOREIGN KEY ("CLAIM_ID") REFERENCES "HMO_CLAIMS"("CLAIM_ID")
      ON DELETE CASCADE ON UPDATE CASCADE;
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS "HMO_INTEGRATION_LOGS" (
    "LOG_ID" SERIAL NOT NULL,
    "PAYER_ID" INTEGER,
    "ADAPTER_KEY" VARCHAR(40) NOT NULL,
    "OPERATION" VARCHAR(40) NOT NULL,
    "PERSON_ID" INTEGER,
    "SUCCESS" BOOLEAN NOT NULL DEFAULT false,
    "HTTP_STATUS" INTEGER,
    "DURATION_MS" INTEGER,
    "ERROR_MESSAGE" VARCHAR(500),
    "REQUEST_META" JSONB,
    "RESPONSE_META" JSONB,
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "HMO_INTEGRATION_LOGS_pkey" PRIMARY KEY ("LOG_ID")
);

CREATE INDEX IF NOT EXISTS "HMO_INTEGRATION_LOGS_ADAPTER_KEY_idx" ON "HMO_INTEGRATION_LOGS"("ADAPTER_KEY");
CREATE INDEX IF NOT EXISTS "HMO_INTEGRATION_LOGS_OPERATION_idx" ON "HMO_INTEGRATION_LOGS"("OPERATION");
CREATE INDEX IF NOT EXISTS "HMO_INTEGRATION_LOGS_PERSON_ID_idx" ON "HMO_INTEGRATION_LOGS"("PERSON_ID");
CREATE INDEX IF NOT EXISTS "HMO_INTEGRATION_LOGS_CREATED_AT_idx" ON "HMO_INTEGRATION_LOGS"("CREATED_AT");
