-- Pay-before-dispense fields on prescriptions + emergency receiver
-- QTY_RETURNED on Rx/sale lines + PHARMACY_RETURNS tables

ALTER TABLE "PRESCRIPTIONS" ADD COLUMN IF NOT EXISTS "PAYMENT_CHANNEL" VARCHAR(50);
ALTER TABLE "PRESCRIPTIONS" ADD COLUMN IF NOT EXISTS "PAYMENT_REF" VARCHAR(100);
ALTER TABLE "PRESCRIPTIONS" ADD COLUMN IF NOT EXISTS "PAID_AT" TIMESTAMP(3);
ALTER TABLE "PRESCRIPTIONS" ADD COLUMN IF NOT EXISTS "PAID_BY" VARCHAR(100);
ALTER TABLE "PRESCRIPTIONS" ADD COLUMN IF NOT EXISTS "PAID_BY_ID" INTEGER;
ALTER TABLE "PRESCRIPTIONS" ADD COLUMN IF NOT EXISTS "EMERGENCY_RECEIVED_BY" VARCHAR(100);
ALTER TABLE "PRESCRIPTIONS" ADD COLUMN IF NOT EXISTS "EMERGENCY_RECEIVED_BY_ID" INTEGER;
ALTER TABLE "PRESCRIPTIONS" ADD COLUMN IF NOT EXISTS "EMERGENCY_DISPENSED_AT" TIMESTAMP(3);
ALTER TABLE "PRESCRIPTIONS" ADD COLUMN IF NOT EXISTS "EMERGENCY_NOTE" TEXT;

ALTER TABLE "PRESCRIPTION_ITEMS" ADD COLUMN IF NOT EXISTS "QTY_RETURNED" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "PHARMACY_SALE_ITEMS" ADD COLUMN IF NOT EXISTS "QTY_RETURNED" INTEGER NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS "PHARMACY_RETURNS" (
    "RETURN_ID" SERIAL NOT NULL,
    "RETURN_NO" VARCHAR(50) NOT NULL,
    "SOURCE_TYPE" VARCHAR(30) NOT NULL,
    "SOURCE_ID" INTEGER NOT NULL,
    "PERSON_ID" INTEGER NOT NULL,
    "STATUS" VARCHAR(50) NOT NULL DEFAULT 'Completed',
    "REASON" TEXT NOT NULL,
    "RETURNED_BY_ROLE" VARCHAR(50) NOT NULL,
    "RETURNED_BY_NAME" VARCHAR(150) NOT NULL,
    "RECEIVED_BY" VARCHAR(100),
    "RECEIVED_BY_ID" INTEGER,
    "TOTAL_VALUE" DECIMAL(14,2) NOT NULL DEFAULT 0,
    "CREATED_BY_ID" INTEGER,
    "CREATED_BY" VARCHAR(100),
    "CREATED_DATE" TIMESTAMP(3),
    "UPDATED_BY_ID" INTEGER,
    "UPDATED_BY" VARCHAR(100),
    "UPDATED_DATE" TIMESTAMP(3),

    CONSTRAINT "PHARMACY_RETURNS_pkey" PRIMARY KEY ("RETURN_ID")
);

CREATE UNIQUE INDEX IF NOT EXISTS "PHARMACY_RETURNS_RETURN_NO_key" ON "PHARMACY_RETURNS"("RETURN_NO");
CREATE INDEX IF NOT EXISTS "PHARMACY_RETURNS_PERSON_ID_idx" ON "PHARMACY_RETURNS"("PERSON_ID");
CREATE INDEX IF NOT EXISTS "PHARMACY_RETURNS_SOURCE_TYPE_SOURCE_ID_idx" ON "PHARMACY_RETURNS"("SOURCE_TYPE", "SOURCE_ID");
CREATE INDEX IF NOT EXISTS "PHARMACY_RETURNS_CREATED_DATE_idx" ON "PHARMACY_RETURNS"("CREATED_DATE");
CREATE INDEX IF NOT EXISTS "PHARMACY_RETURNS_STATUS_idx" ON "PHARMACY_RETURNS"("STATUS");

CREATE TABLE IF NOT EXISTS "PHARMACY_RETURN_ITEMS" (
    "RETURN_ITEM_ID" SERIAL NOT NULL,
    "RETURN_ID" INTEGER NOT NULL,
    "DRUG_ID" INTEGER NOT NULL,
    "DRUG_NAME" VARCHAR(255) NOT NULL,
    "QUANTITY" INTEGER NOT NULL,
    "SOURCE_ITEM_ID" INTEGER NOT NULL,
    "UNIT_PRICE" DECIMAL(14,2) NOT NULL DEFAULT 0,

    CONSTRAINT "PHARMACY_RETURN_ITEMS_pkey" PRIMARY KEY ("RETURN_ITEM_ID")
);

CREATE INDEX IF NOT EXISTS "PHARMACY_RETURN_ITEMS_RETURN_ID_idx" ON "PHARMACY_RETURN_ITEMS"("RETURN_ID");
CREATE INDEX IF NOT EXISTS "PHARMACY_RETURN_ITEMS_DRUG_ID_idx" ON "PHARMACY_RETURN_ITEMS"("DRUG_ID");

DO $$ BEGIN
  ALTER TABLE "PHARMACY_RETURNS"
    ADD CONSTRAINT "PHARMACY_RETURNS_PERSON_ID_fkey"
    FOREIGN KEY ("PERSON_ID") REFERENCES "PERSONS"("PERSON_ID")
    ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "PHARMACY_RETURN_ITEMS"
    ADD CONSTRAINT "PHARMACY_RETURN_ITEMS_RETURN_ID_fkey"
    FOREIGN KEY ("RETURN_ID") REFERENCES "PHARMACY_RETURNS"("RETURN_ID")
    ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "PHARMACY_RETURN_ITEMS"
    ADD CONSTRAINT "PHARMACY_RETURN_ITEMS_DRUG_ID_fkey"
    FOREIGN KEY ("DRUG_ID") REFERENCES "DRUGS"("DRUG_ID")
    ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
