-- Non-clinical Phases F-K: Patient Portal (prefs only), General Stores,
-- Hospital SCM, Kitchen/Catering, Transport/Fleet.
-- Portal dashboard/appointments/invoices/labs/prescriptions are live reads
-- from existing tables — no new tables needed beyond PORTAL_PATIENT_PREFS.

-- ===================== Phase F: Patient Portal =====================

CREATE TABLE IF NOT EXISTS "PORTAL_PATIENT_PREFS" (
    "PERSON_ID" INTEGER NOT NULL,
    "NOTIFY_ENABLED" BOOLEAN NOT NULL DEFAULT true,
    "UPDATED_DATE" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "PORTAL_PATIENT_PREFS_pkey" PRIMARY KEY ("PERSON_ID"),
    CONSTRAINT "PORTAL_PATIENT_PREFS_PERSON_ID_fkey" FOREIGN KEY ("PERSON_ID") REFERENCES "PERSONS"("PERSON_ID") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- ===================== Phase H: General Stores =====================

CREATE TABLE IF NOT EXISTS "STORE_LOCATIONS" (
    "LOCATION_ID" SERIAL NOT NULL,
    "CODE" VARCHAR(40) NOT NULL,
    "NAME" VARCHAR(150) NOT NULL,
    "STATUS" VARCHAR(30) NOT NULL DEFAULT 'Active',
    "CREATED_BY_ID" INTEGER,
    "CREATED_BY" VARCHAR(100),
    "CREATED_DATE" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_BY_ID" INTEGER,
    "UPDATED_BY" VARCHAR(100),
    "UPDATED_DATE" TIMESTAMP(3),
    CONSTRAINT "STORE_LOCATIONS_pkey" PRIMARY KEY ("LOCATION_ID")
);
CREATE UNIQUE INDEX IF NOT EXISTS "STORE_LOCATIONS_CODE_key" ON "STORE_LOCATIONS"("CODE");
CREATE INDEX IF NOT EXISTS "STORE_LOCATIONS_STATUS_idx" ON "STORE_LOCATIONS"("STATUS");

CREATE TABLE IF NOT EXISTS "STORE_ITEM_CATEGORIES" (
    "CATEGORY_ID" SERIAL NOT NULL,
    "CODE" VARCHAR(40) NOT NULL,
    "NAME" VARCHAR(150) NOT NULL,
    "STATUS" VARCHAR(30) NOT NULL DEFAULT 'Active',
    "CREATED_BY_ID" INTEGER,
    "CREATED_BY" VARCHAR(100),
    "CREATED_DATE" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_BY_ID" INTEGER,
    "UPDATED_BY" VARCHAR(100),
    "UPDATED_DATE" TIMESTAMP(3),
    CONSTRAINT "STORE_ITEM_CATEGORIES_pkey" PRIMARY KEY ("CATEGORY_ID")
);
CREATE UNIQUE INDEX IF NOT EXISTS "STORE_ITEM_CATEGORIES_CODE_key" ON "STORE_ITEM_CATEGORIES"("CODE");
CREATE INDEX IF NOT EXISTS "STORE_ITEM_CATEGORIES_STATUS_idx" ON "STORE_ITEM_CATEGORIES"("STATUS");

CREATE TABLE IF NOT EXISTS "STORE_ITEMS" (
    "ITEM_ID" SERIAL NOT NULL,
    "SKU" VARCHAR(60) NOT NULL,
    "NAME" VARCHAR(255) NOT NULL,
    "CATEGORY_ID" INTEGER NOT NULL,
    "UNIT" VARCHAR(30) NOT NULL,
    "REORDER_LEVEL" INTEGER NOT NULL DEFAULT 0,
    "DESCRIPTION" TEXT,
    "STATUS" VARCHAR(30) NOT NULL DEFAULT 'Active',
    "CREATED_BY_ID" INTEGER,
    "CREATED_BY" VARCHAR(100),
    "CREATED_DATE" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_BY_ID" INTEGER,
    "UPDATED_BY" VARCHAR(100),
    "UPDATED_DATE" TIMESTAMP(3),
    CONSTRAINT "STORE_ITEMS_pkey" PRIMARY KEY ("ITEM_ID"),
    CONSTRAINT "STORE_ITEMS_CATEGORY_ID_fkey" FOREIGN KEY ("CATEGORY_ID") REFERENCES "STORE_ITEM_CATEGORIES"("CATEGORY_ID") ON DELETE RESTRICT ON UPDATE CASCADE
);
CREATE UNIQUE INDEX IF NOT EXISTS "STORE_ITEMS_SKU_key" ON "STORE_ITEMS"("SKU");
CREATE INDEX IF NOT EXISTS "STORE_ITEMS_CATEGORY_ID_idx" ON "STORE_ITEMS"("CATEGORY_ID");
CREATE INDEX IF NOT EXISTS "STORE_ITEMS_STATUS_idx" ON "STORE_ITEMS"("STATUS");
CREATE INDEX IF NOT EXISTS "STORE_ITEMS_NAME_idx" ON "STORE_ITEMS"("NAME");

CREATE TABLE IF NOT EXISTS "STORE_BATCHES" (
    "BATCH_ID" SERIAL NOT NULL,
    "ITEM_ID" INTEGER NOT NULL,
    "LOCATION_ID" INTEGER NOT NULL,
    "BATCH_NO" VARCHAR(100) NOT NULL,
    "EXPIRY_DATE" TIMESTAMP(3),
    "QTY_RECEIVED" INTEGER NOT NULL DEFAULT 0,
    "QTY_AVAILABLE" INTEGER NOT NULL DEFAULT 0,
    "UNIT_COST" DECIMAL(14,2),
    "STATUS" VARCHAR(30) NOT NULL DEFAULT 'Available',
    "CREATED_BY_ID" INTEGER,
    "CREATED_BY" VARCHAR(100),
    "CREATED_DATE" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_BY_ID" INTEGER,
    "UPDATED_BY" VARCHAR(100),
    "UPDATED_DATE" TIMESTAMP(3),
    CONSTRAINT "STORE_BATCHES_pkey" PRIMARY KEY ("BATCH_ID"),
    CONSTRAINT "STORE_BATCHES_ITEM_ID_fkey" FOREIGN KEY ("ITEM_ID") REFERENCES "STORE_ITEMS"("ITEM_ID") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "STORE_BATCHES_LOCATION_ID_fkey" FOREIGN KEY ("LOCATION_ID") REFERENCES "STORE_LOCATIONS"("LOCATION_ID") ON DELETE RESTRICT ON UPDATE CASCADE
);
CREATE INDEX IF NOT EXISTS "STORE_BATCHES_ITEM_ID_idx" ON "STORE_BATCHES"("ITEM_ID");
CREATE INDEX IF NOT EXISTS "STORE_BATCHES_LOCATION_ID_idx" ON "STORE_BATCHES"("LOCATION_ID");
CREATE INDEX IF NOT EXISTS "STORE_BATCHES_EXPIRY_DATE_idx" ON "STORE_BATCHES"("EXPIRY_DATE");
CREATE INDEX IF NOT EXISTS "STORE_BATCHES_STATUS_idx" ON "STORE_BATCHES"("STATUS");

CREATE TABLE IF NOT EXISTS "STORE_MOVEMENTS" (
    "MOVEMENT_ID" SERIAL NOT NULL,
    "ITEM_ID" INTEGER NOT NULL,
    "BATCH_ID" INTEGER,
    "LOCATION_ID" INTEGER,
    "TO_LOCATION_ID" INTEGER,
    "KIND" VARCHAR(20) NOT NULL,
    "QTY" INTEGER NOT NULL,
    "REF_TYPE" VARCHAR(40),
    "REF_ID" INTEGER,
    "REASON" TEXT,
    "ACTOR_ID" INTEGER,
    "ACTOR_LABEL" VARCHAR(150),
    "CREATED_DATE" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "STORE_MOVEMENTS_pkey" PRIMARY KEY ("MOVEMENT_ID"),
    CONSTRAINT "STORE_MOVEMENTS_ITEM_ID_fkey" FOREIGN KEY ("ITEM_ID") REFERENCES "STORE_ITEMS"("ITEM_ID") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "STORE_MOVEMENTS_BATCH_ID_fkey" FOREIGN KEY ("BATCH_ID") REFERENCES "STORE_BATCHES"("BATCH_ID") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "STORE_MOVEMENTS_LOCATION_ID_fkey" FOREIGN KEY ("LOCATION_ID") REFERENCES "STORE_LOCATIONS"("LOCATION_ID") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "STORE_MOVEMENTS_TO_LOCATION_ID_fkey" FOREIGN KEY ("TO_LOCATION_ID") REFERENCES "STORE_LOCATIONS"("LOCATION_ID") ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE INDEX IF NOT EXISTS "STORE_MOVEMENTS_ITEM_ID_idx" ON "STORE_MOVEMENTS"("ITEM_ID");
CREATE INDEX IF NOT EXISTS "STORE_MOVEMENTS_BATCH_ID_idx" ON "STORE_MOVEMENTS"("BATCH_ID");
CREATE INDEX IF NOT EXISTS "STORE_MOVEMENTS_KIND_idx" ON "STORE_MOVEMENTS"("KIND");
CREATE INDEX IF NOT EXISTS "STORE_MOVEMENTS_CREATED_DATE_idx" ON "STORE_MOVEMENTS"("CREATED_DATE");

CREATE TABLE IF NOT EXISTS "STORE_REQUISITIONS" (
    "REQUISITION_ID" SERIAL NOT NULL,
    "REQUISITION_NO" VARCHAR(50) NOT NULL,
    "FROM_DEPARTMENT" VARCHAR(150) NOT NULL,
    "LOCATION_ID" INTEGER,
    "STATUS" VARCHAR(30) NOT NULL DEFAULT 'Pending',
    "NOTES" TEXT,
    "REQUESTED_BY_ID" INTEGER,
    "REQUESTED_BY" VARCHAR(150),
    "APPROVED_BY_ID" INTEGER,
    "APPROVED_BY" VARCHAR(150),
    "APPROVED_AT" TIMESTAMP(3),
    "ISSUED_BY_ID" INTEGER,
    "ISSUED_BY" VARCHAR(150),
    "ISSUED_AT" TIMESTAMP(3),
    "DECISION_NOTE" TEXT,
    "CREATED_BY_ID" INTEGER,
    "CREATED_BY" VARCHAR(100),
    "CREATED_DATE" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_BY_ID" INTEGER,
    "UPDATED_BY" VARCHAR(100),
    "UPDATED_DATE" TIMESTAMP(3),
    CONSTRAINT "STORE_REQUISITIONS_pkey" PRIMARY KEY ("REQUISITION_ID"),
    CONSTRAINT "STORE_REQUISITIONS_LOCATION_ID_fkey" FOREIGN KEY ("LOCATION_ID") REFERENCES "STORE_LOCATIONS"("LOCATION_ID") ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE UNIQUE INDEX IF NOT EXISTS "STORE_REQUISITIONS_REQUISITION_NO_key" ON "STORE_REQUISITIONS"("REQUISITION_NO");
CREATE INDEX IF NOT EXISTS "STORE_REQUISITIONS_STATUS_idx" ON "STORE_REQUISITIONS"("STATUS");
CREATE INDEX IF NOT EXISTS "STORE_REQUISITIONS_LOCATION_ID_idx" ON "STORE_REQUISITIONS"("LOCATION_ID");
CREATE INDEX IF NOT EXISTS "STORE_REQUISITIONS_CREATED_DATE_idx" ON "STORE_REQUISITIONS"("CREATED_DATE");

CREATE TABLE IF NOT EXISTS "STORE_REQUISITION_LINES" (
    "LINE_ID" SERIAL NOT NULL,
    "REQUISITION_ID" INTEGER NOT NULL,
    "ITEM_ID" INTEGER NOT NULL,
    "QTY_REQUESTED" INTEGER NOT NULL,
    "QTY_APPROVED" INTEGER,
    "QTY_ISSUED" INTEGER NOT NULL DEFAULT 0,
    "NOTES" TEXT,
    CONSTRAINT "STORE_REQUISITION_LINES_pkey" PRIMARY KEY ("LINE_ID"),
    CONSTRAINT "STORE_REQUISITION_LINES_REQUISITION_ID_fkey" FOREIGN KEY ("REQUISITION_ID") REFERENCES "STORE_REQUISITIONS"("REQUISITION_ID") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "STORE_REQUISITION_LINES_ITEM_ID_fkey" FOREIGN KEY ("ITEM_ID") REFERENCES "STORE_ITEMS"("ITEM_ID") ON DELETE RESTRICT ON UPDATE CASCADE
);
CREATE INDEX IF NOT EXISTS "STORE_REQUISITION_LINES_REQUISITION_ID_idx" ON "STORE_REQUISITION_LINES"("REQUISITION_ID");
CREATE INDEX IF NOT EXISTS "STORE_REQUISITION_LINES_ITEM_ID_idx" ON "STORE_REQUISITION_LINES"("ITEM_ID");

-- ===================== Phase I: Hospital SCM =====================

CREATE TABLE IF NOT EXISTS "SCM_SUPPLIERS" (
    "SUPPLIER_ID" SERIAL NOT NULL,
    "NAME" VARCHAR(255) NOT NULL,
    "CONTACT_PERSON" VARCHAR(255),
    "PHONE" VARCHAR(50),
    "EMAIL" VARCHAR(255),
    "ADDRESS" VARCHAR(500),
    "NOTES" TEXT,
    "STATUS" VARCHAR(30) NOT NULL DEFAULT 'Active',
    "CREATED_BY_ID" INTEGER,
    "CREATED_BY" VARCHAR(100),
    "CREATED_DATE" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_BY_ID" INTEGER,
    "UPDATED_BY" VARCHAR(100),
    "UPDATED_DATE" TIMESTAMP(3),
    CONSTRAINT "SCM_SUPPLIERS_pkey" PRIMARY KEY ("SUPPLIER_ID")
);
CREATE INDEX IF NOT EXISTS "SCM_SUPPLIERS_NAME_idx" ON "SCM_SUPPLIERS"("NAME");
CREATE INDEX IF NOT EXISTS "SCM_SUPPLIERS_STATUS_idx" ON "SCM_SUPPLIERS"("STATUS");

CREATE TABLE IF NOT EXISTS "SCM_PURCHASE_ORDERS" (
    "PO_ID" SERIAL NOT NULL,
    "PO_NO" VARCHAR(50) NOT NULL,
    "SUPPLIER_ID" INTEGER NOT NULL,
    "TOTAL" DECIMAL(14,2) NOT NULL DEFAULT 0,
    "APPROVAL_STATUS" VARCHAR(30) NOT NULL DEFAULT 'Pending',
    "STATUS" VARCHAR(30) NOT NULL DEFAULT 'PendingApproval',
    "EXPECTED_DATE" TIMESTAMP(3),
    "NOTES" TEXT,
    "APPROVED_BY_ID" INTEGER,
    "APPROVED_BY" VARCHAR(150),
    "APPROVED_AT" TIMESTAMP(3),
    "CREATED_BY_ID" INTEGER,
    "CREATED_BY" VARCHAR(100),
    "CREATED_DATE" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_BY_ID" INTEGER,
    "UPDATED_BY" VARCHAR(100),
    "UPDATED_DATE" TIMESTAMP(3),
    CONSTRAINT "SCM_PURCHASE_ORDERS_pkey" PRIMARY KEY ("PO_ID"),
    CONSTRAINT "SCM_PURCHASE_ORDERS_SUPPLIER_ID_fkey" FOREIGN KEY ("SUPPLIER_ID") REFERENCES "SCM_SUPPLIERS"("SUPPLIER_ID") ON DELETE RESTRICT ON UPDATE CASCADE
);
CREATE UNIQUE INDEX IF NOT EXISTS "SCM_PURCHASE_ORDERS_PO_NO_key" ON "SCM_PURCHASE_ORDERS"("PO_NO");
CREATE INDEX IF NOT EXISTS "SCM_PURCHASE_ORDERS_SUPPLIER_ID_idx" ON "SCM_PURCHASE_ORDERS"("SUPPLIER_ID");
CREATE INDEX IF NOT EXISTS "SCM_PURCHASE_ORDERS_STATUS_idx" ON "SCM_PURCHASE_ORDERS"("STATUS");
CREATE INDEX IF NOT EXISTS "SCM_PURCHASE_ORDERS_APPROVAL_STATUS_idx" ON "SCM_PURCHASE_ORDERS"("APPROVAL_STATUS");
CREATE INDEX IF NOT EXISTS "SCM_PURCHASE_ORDERS_CREATED_DATE_idx" ON "SCM_PURCHASE_ORDERS"("CREATED_DATE");

CREATE TABLE IF NOT EXISTS "SCM_PO_LINES" (
    "LINE_ID" SERIAL NOT NULL,
    "PO_ID" INTEGER NOT NULL,
    "ITEM_ID" INTEGER NOT NULL,
    "QTY" INTEGER NOT NULL,
    "UNIT_COST" DECIMAL(14,2) NOT NULL DEFAULT 0,
    "QTY_RECEIVED" INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT "SCM_PO_LINES_pkey" PRIMARY KEY ("LINE_ID"),
    CONSTRAINT "SCM_PO_LINES_PO_ID_fkey" FOREIGN KEY ("PO_ID") REFERENCES "SCM_PURCHASE_ORDERS"("PO_ID") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "SCM_PO_LINES_ITEM_ID_fkey" FOREIGN KEY ("ITEM_ID") REFERENCES "STORE_ITEMS"("ITEM_ID") ON DELETE RESTRICT ON UPDATE CASCADE
);
CREATE INDEX IF NOT EXISTS "SCM_PO_LINES_PO_ID_idx" ON "SCM_PO_LINES"("PO_ID");
CREATE INDEX IF NOT EXISTS "SCM_PO_LINES_ITEM_ID_idx" ON "SCM_PO_LINES"("ITEM_ID");

CREATE TABLE IF NOT EXISTS "SCM_GRNS" (
    "GRN_ID" SERIAL NOT NULL,
    "GRN_NO" VARCHAR(50) NOT NULL,
    "PO_ID" INTEGER,
    "LOCATION_ID" INTEGER NOT NULL,
    "RECEIVED_BY_ID" INTEGER,
    "RECEIVED_BY" VARCHAR(150),
    "RECEIVED_DATE" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "NOTES" TEXT,
    "CREATED_BY_ID" INTEGER,
    "CREATED_BY" VARCHAR(100),
    "CREATED_DATE" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "SCM_GRNS_pkey" PRIMARY KEY ("GRN_ID"),
    CONSTRAINT "SCM_GRNS_PO_ID_fkey" FOREIGN KEY ("PO_ID") REFERENCES "SCM_PURCHASE_ORDERS"("PO_ID") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "SCM_GRNS_LOCATION_ID_fkey" FOREIGN KEY ("LOCATION_ID") REFERENCES "STORE_LOCATIONS"("LOCATION_ID") ON DELETE RESTRICT ON UPDATE CASCADE
);
CREATE UNIQUE INDEX IF NOT EXISTS "SCM_GRNS_GRN_NO_key" ON "SCM_GRNS"("GRN_NO");
CREATE INDEX IF NOT EXISTS "SCM_GRNS_PO_ID_idx" ON "SCM_GRNS"("PO_ID");
CREATE INDEX IF NOT EXISTS "SCM_GRNS_LOCATION_ID_idx" ON "SCM_GRNS"("LOCATION_ID");
CREATE INDEX IF NOT EXISTS "SCM_GRNS_RECEIVED_DATE_idx" ON "SCM_GRNS"("RECEIVED_DATE");

CREATE TABLE IF NOT EXISTS "SCM_GRN_LINES" (
    "LINE_ID" SERIAL NOT NULL,
    "GRN_ID" INTEGER NOT NULL,
    "ITEM_ID" INTEGER NOT NULL,
    "PO_LINE_ID" INTEGER,
    "BATCH_NO" VARCHAR(100) NOT NULL,
    "EXPIRY_DATE" TIMESTAMP(3),
    "QTY_RECEIVED" INTEGER NOT NULL DEFAULT 0,
    "QTY_DAMAGED" INTEGER NOT NULL DEFAULT 0,
    "QTY_ACCEPTED" INTEGER NOT NULL DEFAULT 0,
    "UNIT_COST" DECIMAL(14,2),
    "BATCH_ID" INTEGER,
    CONSTRAINT "SCM_GRN_LINES_pkey" PRIMARY KEY ("LINE_ID"),
    CONSTRAINT "SCM_GRN_LINES_GRN_ID_fkey" FOREIGN KEY ("GRN_ID") REFERENCES "SCM_GRNS"("GRN_ID") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "SCM_GRN_LINES_ITEM_ID_fkey" FOREIGN KEY ("ITEM_ID") REFERENCES "STORE_ITEMS"("ITEM_ID") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "SCM_GRN_LINES_PO_LINE_ID_fkey" FOREIGN KEY ("PO_LINE_ID") REFERENCES "SCM_PO_LINES"("LINE_ID") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "SCM_GRN_LINES_BATCH_ID_fkey" FOREIGN KEY ("BATCH_ID") REFERENCES "STORE_BATCHES"("BATCH_ID") ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE INDEX IF NOT EXISTS "SCM_GRN_LINES_GRN_ID_idx" ON "SCM_GRN_LINES"("GRN_ID");
CREATE INDEX IF NOT EXISTS "SCM_GRN_LINES_ITEM_ID_idx" ON "SCM_GRN_LINES"("ITEM_ID");
CREATE INDEX IF NOT EXISTS "SCM_GRN_LINES_PO_LINE_ID_idx" ON "SCM_GRN_LINES"("PO_LINE_ID");

-- ===================== Phase J: Kitchen / Catering =====================

CREATE TABLE IF NOT EXISTS "KITCHEN_MENUS" (
    "MENU_ID" SERIAL NOT NULL,
    "NAME" VARCHAR(200) NOT NULL,
    "MEAL_SLOT" VARCHAR(30) NOT NULL,
    "DESCRIPTION" TEXT,
    "DIET_TAGS" VARCHAR(255),
    "STATUS" VARCHAR(30) NOT NULL DEFAULT 'Active',
    "CREATED_BY_ID" INTEGER,
    "CREATED_BY" VARCHAR(100),
    "CREATED_DATE" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_BY_ID" INTEGER,
    "UPDATED_BY" VARCHAR(100),
    "UPDATED_DATE" TIMESTAMP(3),
    CONSTRAINT "KITCHEN_MENUS_pkey" PRIMARY KEY ("MENU_ID")
);
CREATE INDEX IF NOT EXISTS "KITCHEN_MENUS_MEAL_SLOT_idx" ON "KITCHEN_MENUS"("MEAL_SLOT");
CREATE INDEX IF NOT EXISTS "KITCHEN_MENUS_STATUS_idx" ON "KITCHEN_MENUS"("STATUS");

CREATE TABLE IF NOT EXISTS "KITCHEN_ORDERS" (
    "ORDER_ID" SERIAL NOT NULL,
    "ORDER_NO" VARCHAR(50) NOT NULL,
    "PERSON_ID" INTEGER,
    "ADMISSION_ID" INTEGER,
    "MENU_ID" INTEGER,
    "MEAL_SLOT" VARCHAR(30) NOT NULL,
    "WARD_LABEL" VARCHAR(150),
    "DIET_NOTES" TEXT,
    "QUANTITY" INTEGER NOT NULL DEFAULT 1,
    "STATUS" VARCHAR(30) NOT NULL DEFAULT 'Pending',
    "SCHEDULED_FOR" DATE,
    "SERVED_AT" TIMESTAMP(3),
    "REQUESTED_BY_ID" INTEGER,
    "REQUESTED_BY" VARCHAR(150),
    "CREATED_BY_ID" INTEGER,
    "CREATED_BY" VARCHAR(100),
    "CREATED_DATE" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_BY_ID" INTEGER,
    "UPDATED_BY" VARCHAR(100),
    "UPDATED_DATE" TIMESTAMP(3),
    CONSTRAINT "KITCHEN_ORDERS_pkey" PRIMARY KEY ("ORDER_ID"),
    CONSTRAINT "KITCHEN_ORDERS_MENU_ID_fkey" FOREIGN KEY ("MENU_ID") REFERENCES "KITCHEN_MENUS"("MENU_ID") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "KITCHEN_ORDERS_PERSON_ID_fkey" FOREIGN KEY ("PERSON_ID") REFERENCES "PERSONS"("PERSON_ID") ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE UNIQUE INDEX IF NOT EXISTS "KITCHEN_ORDERS_ORDER_NO_key" ON "KITCHEN_ORDERS"("ORDER_NO");
CREATE INDEX IF NOT EXISTS "KITCHEN_ORDERS_MENU_ID_idx" ON "KITCHEN_ORDERS"("MENU_ID");
CREATE INDEX IF NOT EXISTS "KITCHEN_ORDERS_PERSON_ID_idx" ON "KITCHEN_ORDERS"("PERSON_ID");
CREATE INDEX IF NOT EXISTS "KITCHEN_ORDERS_STATUS_idx" ON "KITCHEN_ORDERS"("STATUS");
CREATE INDEX IF NOT EXISTS "KITCHEN_ORDERS_MEAL_SLOT_idx" ON "KITCHEN_ORDERS"("MEAL_SLOT");
CREATE INDEX IF NOT EXISTS "KITCHEN_ORDERS_CREATED_DATE_idx" ON "KITCHEN_ORDERS"("CREATED_DATE");

CREATE TABLE IF NOT EXISTS "KITCHEN_WASTAGE" (
    "WASTAGE_ID" SERIAL NOT NULL,
    "MENU_ID" INTEGER,
    "ITEM_NAME" VARCHAR(200) NOT NULL,
    "QUANTITY" DECIMAL(10,2) NOT NULL,
    "UNIT" VARCHAR(30),
    "REASON" TEXT,
    "RECORDED_BY_ID" INTEGER,
    "RECORDED_BY" VARCHAR(150),
    "RECORDED_DATE" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "KITCHEN_WASTAGE_pkey" PRIMARY KEY ("WASTAGE_ID"),
    CONSTRAINT "KITCHEN_WASTAGE_MENU_ID_fkey" FOREIGN KEY ("MENU_ID") REFERENCES "KITCHEN_MENUS"("MENU_ID") ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE INDEX IF NOT EXISTS "KITCHEN_WASTAGE_MENU_ID_idx" ON "KITCHEN_WASTAGE"("MENU_ID");
CREATE INDEX IF NOT EXISTS "KITCHEN_WASTAGE_RECORDED_DATE_idx" ON "KITCHEN_WASTAGE"("RECORDED_DATE");

-- ===================== Phase K: Transport / Fleet =====================

CREATE TABLE IF NOT EXISTS "FLEET_VEHICLES" (
    "VEHICLE_ID" SERIAL NOT NULL,
    "REG_NO" VARCHAR(40) NOT NULL,
    "TYPE" VARCHAR(30) NOT NULL,
    "MODEL" VARCHAR(100),
    "STATUS" VARCHAR(30) NOT NULL DEFAULT 'Available',
    "INSURANCE_EXPIRY" DATE,
    "REGISTRATION_EXPIRY" DATE,
    "NOTES" TEXT,
    "CREATED_BY_ID" INTEGER,
    "CREATED_BY" VARCHAR(100),
    "CREATED_DATE" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_BY_ID" INTEGER,
    "UPDATED_BY" VARCHAR(100),
    "UPDATED_DATE" TIMESTAMP(3),
    CONSTRAINT "FLEET_VEHICLES_pkey" PRIMARY KEY ("VEHICLE_ID")
);
CREATE UNIQUE INDEX IF NOT EXISTS "FLEET_VEHICLES_REG_NO_key" ON "FLEET_VEHICLES"("REG_NO");
CREATE INDEX IF NOT EXISTS "FLEET_VEHICLES_STATUS_idx" ON "FLEET_VEHICLES"("STATUS");
CREATE INDEX IF NOT EXISTS "FLEET_VEHICLES_TYPE_idx" ON "FLEET_VEHICLES"("TYPE");

CREATE TABLE IF NOT EXISTS "FLEET_DRIVERS" (
    "DRIVER_ID" SERIAL NOT NULL,
    "NAME" VARCHAR(150) NOT NULL,
    "PHONE" VARCHAR(50),
    "LICENSE_NO" VARCHAR(100),
    "LICENSE_EXPIRY" DATE,
    "STATUS" VARCHAR(30) NOT NULL DEFAULT 'Active',
    "CREATED_BY_ID" INTEGER,
    "CREATED_BY" VARCHAR(100),
    "CREATED_DATE" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_BY_ID" INTEGER,
    "UPDATED_BY" VARCHAR(100),
    "UPDATED_DATE" TIMESTAMP(3),
    CONSTRAINT "FLEET_DRIVERS_pkey" PRIMARY KEY ("DRIVER_ID")
);
CREATE INDEX IF NOT EXISTS "FLEET_DRIVERS_STATUS_idx" ON "FLEET_DRIVERS"("STATUS");

CREATE TABLE IF NOT EXISTS "FLEET_TRIP_REQUESTS" (
    "REQUEST_ID" SERIAL NOT NULL,
    "REQUEST_NO" VARCHAR(50) NOT NULL,
    "PERSON_ID" INTEGER,
    "REQUESTED_BY_ID" INTEGER,
    "REQUESTED_BY" VARCHAR(150),
    "DEPARTMENT" VARCHAR(150),
    "PURPOSE" TEXT NOT NULL,
    "PICKUP_LOCATION" VARCHAR(255),
    "DESTINATION" VARCHAR(255) NOT NULL,
    "REQUESTED_DATE" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "PRIORITY" VARCHAR(30) NOT NULL DEFAULT 'Routine',
    "STATUS" VARCHAR(30) NOT NULL DEFAULT 'Pending',
    "DECISION_NOTE" TEXT,
    "APPROVED_BY_ID" INTEGER,
    "APPROVED_BY" VARCHAR(150),
    "APPROVED_AT" TIMESTAMP(3),
    "CREATED_BY_ID" INTEGER,
    "CREATED_BY" VARCHAR(100),
    "CREATED_DATE" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_BY_ID" INTEGER,
    "UPDATED_BY" VARCHAR(100),
    "UPDATED_DATE" TIMESTAMP(3),
    CONSTRAINT "FLEET_TRIP_REQUESTS_pkey" PRIMARY KEY ("REQUEST_ID"),
    CONSTRAINT "FLEET_TRIP_REQUESTS_PERSON_ID_fkey" FOREIGN KEY ("PERSON_ID") REFERENCES "PERSONS"("PERSON_ID") ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE UNIQUE INDEX IF NOT EXISTS "FLEET_TRIP_REQUESTS_REQUEST_NO_key" ON "FLEET_TRIP_REQUESTS"("REQUEST_NO");
CREATE INDEX IF NOT EXISTS "FLEET_TRIP_REQUESTS_STATUS_idx" ON "FLEET_TRIP_REQUESTS"("STATUS");
CREATE INDEX IF NOT EXISTS "FLEET_TRIP_REQUESTS_PERSON_ID_idx" ON "FLEET_TRIP_REQUESTS"("PERSON_ID");
CREATE INDEX IF NOT EXISTS "FLEET_TRIP_REQUESTS_CREATED_DATE_idx" ON "FLEET_TRIP_REQUESTS"("CREATED_DATE");

CREATE TABLE IF NOT EXISTS "FLEET_TRIPS" (
    "TRIP_ID" SERIAL NOT NULL,
    "TRIP_NO" VARCHAR(50) NOT NULL,
    "REQUEST_ID" INTEGER,
    "VEHICLE_ID" INTEGER NOT NULL,
    "DRIVER_ID" INTEGER NOT NULL,
    "PURPOSE" TEXT NOT NULL,
    "FROM_LOCATION" VARCHAR(255),
    "TO_LOCATION" VARCHAR(255) NOT NULL,
    "START_AT" TIMESTAMP(3),
    "END_AT" TIMESTAMP(3),
    "MILEAGE_START" INTEGER,
    "MILEAGE_END" INTEGER,
    "STATUS" VARCHAR(30) NOT NULL DEFAULT 'Scheduled',
    "NOTES" TEXT,
    "CREATED_BY_ID" INTEGER,
    "CREATED_BY" VARCHAR(100),
    "CREATED_DATE" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_BY_ID" INTEGER,
    "UPDATED_BY" VARCHAR(100),
    "UPDATED_DATE" TIMESTAMP(3),
    CONSTRAINT "FLEET_TRIPS_pkey" PRIMARY KEY ("TRIP_ID"),
    CONSTRAINT "FLEET_TRIPS_REQUEST_ID_fkey" FOREIGN KEY ("REQUEST_ID") REFERENCES "FLEET_TRIP_REQUESTS"("REQUEST_ID") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "FLEET_TRIPS_VEHICLE_ID_fkey" FOREIGN KEY ("VEHICLE_ID") REFERENCES "FLEET_VEHICLES"("VEHICLE_ID") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "FLEET_TRIPS_DRIVER_ID_fkey" FOREIGN KEY ("DRIVER_ID") REFERENCES "FLEET_DRIVERS"("DRIVER_ID") ON DELETE RESTRICT ON UPDATE CASCADE
);
CREATE UNIQUE INDEX IF NOT EXISTS "FLEET_TRIPS_TRIP_NO_key" ON "FLEET_TRIPS"("TRIP_NO");
CREATE INDEX IF NOT EXISTS "FLEET_TRIPS_VEHICLE_ID_idx" ON "FLEET_TRIPS"("VEHICLE_ID");
CREATE INDEX IF NOT EXISTS "FLEET_TRIPS_DRIVER_ID_idx" ON "FLEET_TRIPS"("DRIVER_ID");
CREATE INDEX IF NOT EXISTS "FLEET_TRIPS_REQUEST_ID_idx" ON "FLEET_TRIPS"("REQUEST_ID");
CREATE INDEX IF NOT EXISTS "FLEET_TRIPS_STATUS_idx" ON "FLEET_TRIPS"("STATUS");

CREATE TABLE IF NOT EXISTS "FLEET_FUEL_LOGS" (
    "FUEL_ID" SERIAL NOT NULL,
    "VEHICLE_ID" INTEGER NOT NULL,
    "TRIP_ID" INTEGER,
    "LITERS" DECIMAL(10,2) NOT NULL,
    "COST" DECIMAL(14,2) NOT NULL,
    "FILLED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "RECORDED_BY_ID" INTEGER,
    "RECORDED_BY" VARCHAR(150),
    "NOTES" TEXT,
    "CREATED_DATE" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "FLEET_FUEL_LOGS_pkey" PRIMARY KEY ("FUEL_ID"),
    CONSTRAINT "FLEET_FUEL_LOGS_VEHICLE_ID_fkey" FOREIGN KEY ("VEHICLE_ID") REFERENCES "FLEET_VEHICLES"("VEHICLE_ID") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "FLEET_FUEL_LOGS_TRIP_ID_fkey" FOREIGN KEY ("TRIP_ID") REFERENCES "FLEET_TRIPS"("TRIP_ID") ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE INDEX IF NOT EXISTS "FLEET_FUEL_LOGS_VEHICLE_ID_idx" ON "FLEET_FUEL_LOGS"("VEHICLE_ID");
CREATE INDEX IF NOT EXISTS "FLEET_FUEL_LOGS_FILLED_AT_idx" ON "FLEET_FUEL_LOGS"("FILLED_AT");

CREATE TABLE IF NOT EXISTS "FLEET_MAINTENANCE" (
    "MAINT_ID" SERIAL NOT NULL,
    "VEHICLE_ID" INTEGER NOT NULL,
    "TYPE" VARCHAR(30) NOT NULL,
    "DESCRIPTION" TEXT,
    "COST" DECIMAL(14,2),
    "STATUS" VARCHAR(20) NOT NULL DEFAULT 'Open',
    "SCHEDULED_DATE" DATE,
    "COMPLETED_DATE" DATE,
    "CREATED_BY_ID" INTEGER,
    "CREATED_BY" VARCHAR(100),
    "CREATED_DATE" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_BY_ID" INTEGER,
    "UPDATED_BY" VARCHAR(100),
    "UPDATED_DATE" TIMESTAMP(3),
    CONSTRAINT "FLEET_MAINTENANCE_pkey" PRIMARY KEY ("MAINT_ID"),
    CONSTRAINT "FLEET_MAINTENANCE_VEHICLE_ID_fkey" FOREIGN KEY ("VEHICLE_ID") REFERENCES "FLEET_VEHICLES"("VEHICLE_ID") ON DELETE RESTRICT ON UPDATE CASCADE
);
CREATE INDEX IF NOT EXISTS "FLEET_MAINTENANCE_VEHICLE_ID_idx" ON "FLEET_MAINTENANCE"("VEHICLE_ID");
CREATE INDEX IF NOT EXISTS "FLEET_MAINTENANCE_STATUS_idx" ON "FLEET_MAINTENANCE"("STATUS");

-- ===================== Seed reference data =====================

INSERT INTO "STORE_LOCATIONS" ("CODE", "NAME", "STATUS", "CREATED_BY", "CREATED_DATE")
VALUES
  ('CENTRAL', 'Central Store', 'Active', 'SYSTEM', CURRENT_TIMESTAMP),
  ('WARD', 'Ward Store', 'Active', 'SYSTEM', CURRENT_TIMESTAMP),
  ('CSSD', 'CSSD Store', 'Active', 'SYSTEM', CURRENT_TIMESTAMP)
ON CONFLICT ("CODE") DO NOTHING;

INSERT INTO "STORE_ITEM_CATEGORIES" ("CODE", "NAME", "STATUS", "CREATED_BY", "CREATED_DATE")
VALUES
  ('MEDICAL_CONSUMABLES', 'Medical Consumables', 'Active', 'SYSTEM', CURRENT_TIMESTAMP),
  ('OFFICE', 'Office Supplies', 'Active', 'SYSTEM', CURRENT_TIMESTAMP),
  ('CLEANING', 'Cleaning', 'Active', 'SYSTEM', CURRENT_TIMESTAMP),
  ('STATIONERY', 'Stationery', 'Active', 'SYSTEM', CURRENT_TIMESTAMP),
  ('EQUIPMENT', 'Equipment', 'Active', 'SYSTEM', CURRENT_TIMESTAMP),
  ('MAINTENANCE', 'Maintenance', 'Active', 'SYSTEM', CURRENT_TIMESTAMP),
  ('PPE', 'PPE', 'Active', 'SYSTEM', CURRENT_TIMESTAMP),
  ('OTHER', 'Other', 'Active', 'SYSTEM', CURRENT_TIMESTAMP)
ON CONFLICT ("CODE") DO NOTHING;
