-- Cashier ops: payment receipts, refunds, discounts/waivers, shifts

CREATE TABLE IF NOT EXISTS "CASHIER_PAYMENT_RECEIPTS" (
  "RECEIPT_ID" SERIAL PRIMARY KEY,
  "RECEIPT_NO" VARCHAR(50) NOT NULL,
  "SOURCE_TYPE" VARCHAR(30) NOT NULL,
  "SOURCE_ID" INTEGER NOT NULL,
  "PERSON_ID" INTEGER NOT NULL,
  "AMOUNT" DECIMAL(14,2) NOT NULL,
  "CHANNEL" VARCHAR(40) NOT NULL,
  "PAYMENT_REF" VARCHAR(100),
  "CASHIER_USER_ID" INTEGER,
  "CASHIER_LABEL" VARCHAR(150),
  "PAID_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "STATUS" VARCHAR(30) NOT NULL DEFAULT 'Captured',
  "AMOUNT_REFUNDED" DECIMAL(14,2) NOT NULL DEFAULT 0,
  "PATIENT_NAME" VARCHAR(200),
  "SOURCE_REF" VARCHAR(80),
  "CREATED_BY_ID" INTEGER,
  "CREATED_BY" VARCHAR(100),
  "CREATED_DATE" TIMESTAMP(3),
  "UPDATED_BY_ID" INTEGER,
  "UPDATED_BY" VARCHAR(100),
  "UPDATED_DATE" TIMESTAMP(3),
  "DELETED_FLAG" VARCHAR(1) DEFAULT 'N'
);

CREATE UNIQUE INDEX IF NOT EXISTS "CASHIER_PAYMENT_RECEIPTS_RECEIPT_NO_key" ON "CASHIER_PAYMENT_RECEIPTS"("RECEIPT_NO");
CREATE UNIQUE INDEX IF NOT EXISTS "CASHIER_PAYMENT_RECEIPTS_SOURCE_TYPE_SOURCE_ID_key" ON "CASHIER_PAYMENT_RECEIPTS"("SOURCE_TYPE", "SOURCE_ID");
CREATE INDEX IF NOT EXISTS "CASHIER_PAYMENT_RECEIPTS_PERSON_ID_idx" ON "CASHIER_PAYMENT_RECEIPTS"("PERSON_ID");
CREATE INDEX IF NOT EXISTS "CASHIER_PAYMENT_RECEIPTS_STATUS_idx" ON "CASHIER_PAYMENT_RECEIPTS"("STATUS");
CREATE INDEX IF NOT EXISTS "CASHIER_PAYMENT_RECEIPTS_PAID_AT_idx" ON "CASHIER_PAYMENT_RECEIPTS"("PAID_AT");
CREATE INDEX IF NOT EXISTS "CASHIER_PAYMENT_RECEIPTS_CASHIER_USER_ID_idx" ON "CASHIER_PAYMENT_RECEIPTS"("CASHIER_USER_ID");

CREATE TABLE IF NOT EXISTS "CASHIER_REFUND_REQUESTS" (
  "REFUND_ID" SERIAL PRIMARY KEY,
  "REFUND_NO" VARCHAR(50) NOT NULL,
  "RECEIPT_ID" INTEGER NOT NULL,
  "AMOUNT" DECIMAL(14,2) NOT NULL,
  "KIND" VARCHAR(20) NOT NULL,
  "METHOD" VARCHAR(40) NOT NULL,
  "REASON" TEXT NOT NULL,
  "STATUS" VARCHAR(20) NOT NULL DEFAULT 'Pending',
  "REQUESTED_BY_ID" INTEGER,
  "REQUESTED_BY" VARCHAR(150),
  "APPROVED_BY_ID" INTEGER,
  "APPROVED_BY" VARCHAR(150),
  "APPROVED_AT" TIMESTAMP(3),
  "CREATED_BY_ID" INTEGER,
  "CREATED_BY" VARCHAR(100),
  "CREATED_DATE" TIMESTAMP(3),
  "UPDATED_BY_ID" INTEGER,
  "UPDATED_BY" VARCHAR(100),
  "UPDATED_DATE" TIMESTAMP(3),
  "DELETED_FLAG" VARCHAR(1) DEFAULT 'N',
  CONSTRAINT "CASHIER_REFUND_REQUESTS_RECEIPT_ID_fkey"
    FOREIGN KEY ("RECEIPT_ID") REFERENCES "CASHIER_PAYMENT_RECEIPTS"("RECEIPT_ID")
    ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS "CASHIER_REFUND_REQUESTS_REFUND_NO_key" ON "CASHIER_REFUND_REQUESTS"("REFUND_NO");
CREATE INDEX IF NOT EXISTS "CASHIER_REFUND_REQUESTS_RECEIPT_ID_idx" ON "CASHIER_REFUND_REQUESTS"("RECEIPT_ID");
CREATE INDEX IF NOT EXISTS "CASHIER_REFUND_REQUESTS_STATUS_idx" ON "CASHIER_REFUND_REQUESTS"("STATUS");
CREATE INDEX IF NOT EXISTS "CASHIER_REFUND_REQUESTS_CREATED_DATE_idx" ON "CASHIER_REFUND_REQUESTS"("CREATED_DATE");

CREATE TABLE IF NOT EXISTS "CASHIER_DISCOUNT_REQUESTS" (
  "DISCOUNT_ID" SERIAL PRIMARY KEY,
  "DISCOUNT_NO" VARCHAR(50) NOT NULL,
  "SOURCE_TYPE" VARCHAR(30) NOT NULL,
  "SOURCE_ID" INTEGER NOT NULL,
  "PERSON_ID" INTEGER NOT NULL,
  "PATIENT_NAME" VARCHAR(200),
  "SOURCE_REF" VARCHAR(80),
  "DISC_KIND" VARCHAR(20) NOT NULL,
  "VALUE" DECIMAL(14,2),
  "CATEGORY" VARCHAR(80) NOT NULL,
  "REASON" TEXT NOT NULL,
  "COMPUTED_AMOUNT" DECIMAL(14,2) NOT NULL,
  "BILL_AMOUNT" DECIMAL(14,2) NOT NULL,
  "STATUS" VARCHAR(20) NOT NULL DEFAULT 'Pending',
  "REQUESTED_BY_ID" INTEGER,
  "REQUESTED_BY" VARCHAR(150),
  "APPROVED_BY_ID" INTEGER,
  "APPROVED_BY" VARCHAR(150),
  "APPROVED_AT" TIMESTAMP(3),
  "CREATED_BY_ID" INTEGER,
  "CREATED_BY" VARCHAR(100),
  "CREATED_DATE" TIMESTAMP(3),
  "UPDATED_BY_ID" INTEGER,
  "UPDATED_BY" VARCHAR(100),
  "UPDATED_DATE" TIMESTAMP(3),
  "DELETED_FLAG" VARCHAR(1) DEFAULT 'N'
);

CREATE UNIQUE INDEX IF NOT EXISTS "CASHIER_DISCOUNT_REQUESTS_DISCOUNT_NO_key" ON "CASHIER_DISCOUNT_REQUESTS"("DISCOUNT_NO");
CREATE INDEX IF NOT EXISTS "CASHIER_DISCOUNT_REQUESTS_SOURCE_TYPE_SOURCE_ID_idx" ON "CASHIER_DISCOUNT_REQUESTS"("SOURCE_TYPE", "SOURCE_ID");
CREATE INDEX IF NOT EXISTS "CASHIER_DISCOUNT_REQUESTS_STATUS_idx" ON "CASHIER_DISCOUNT_REQUESTS"("STATUS");
CREATE INDEX IF NOT EXISTS "CASHIER_DISCOUNT_REQUESTS_PERSON_ID_idx" ON "CASHIER_DISCOUNT_REQUESTS"("PERSON_ID");
CREATE INDEX IF NOT EXISTS "CASHIER_DISCOUNT_REQUESTS_CREATED_DATE_idx" ON "CASHIER_DISCOUNT_REQUESTS"("CREATED_DATE");

CREATE TABLE IF NOT EXISTS "CASHIER_SHIFTS" (
  "SHIFT_ID" SERIAL PRIMARY KEY,
  "SHIFT_NO" VARCHAR(50) NOT NULL,
  "CASHIER_USER_ID" INTEGER NOT NULL,
  "CASHIER_LABEL" VARCHAR(150) NOT NULL,
  "OPENING_FLOAT" DECIMAL(14,2) NOT NULL,
  "OPENED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "CLOSED_AT" TIMESTAMP(3),
  "STATUS" VARCHAR(20) NOT NULL DEFAULT 'Open',
  "ACTUAL_CASH" DECIMAL(14,2),
  "VARIANCE" DECIMAL(14,2),
  "NOTE" TEXT,
  "TOTALS_JSON" JSONB,
  "APPROVED_BY_ID" INTEGER,
  "APPROVED_BY" VARCHAR(150),
  "APPROVED_AT" TIMESTAMP(3),
  "CREATED_BY_ID" INTEGER,
  "CREATED_BY" VARCHAR(100),
  "CREATED_DATE" TIMESTAMP(3),
  "UPDATED_BY_ID" INTEGER,
  "UPDATED_BY" VARCHAR(100),
  "UPDATED_DATE" TIMESTAMP(3),
  "DELETED_FLAG" VARCHAR(1) DEFAULT 'N'
);

CREATE UNIQUE INDEX IF NOT EXISTS "CASHIER_SHIFTS_SHIFT_NO_key" ON "CASHIER_SHIFTS"("SHIFT_NO");
CREATE INDEX IF NOT EXISTS "CASHIER_SHIFTS_CASHIER_USER_ID_idx" ON "CASHIER_SHIFTS"("CASHIER_USER_ID");
CREATE INDEX IF NOT EXISTS "CASHIER_SHIFTS_STATUS_idx" ON "CASHIER_SHIFTS"("STATUS");
CREATE INDEX IF NOT EXISTS "CASHIER_SHIFTS_OPENED_AT_idx" ON "CASHIER_SHIFTS"("OPENED_AT");
