-- Doctor admission requests (pending queue — no payment / bed assignment).

CREATE TABLE IF NOT EXISTS "ADMISSION_REQUESTS" (
    "ADMISSION_REQUEST_ID" SERIAL NOT NULL,
    "REQUEST_NO" VARCHAR(50) NOT NULL,
    "PERSON_ID" INTEGER NOT NULL,
    "ENCOUNTER_ID" INTEGER,
    "WARD_ID" INTEGER,
    "WARD_PREFERENCE" VARCHAR(150),
    "PRIORITY" VARCHAR(30) NOT NULL DEFAULT 'Routine',
    "PRIORITY_REASON" TEXT,
    "ADMISSION_TYPE" VARCHAR(80),
    "ESTIMATED_LOS" VARCHAR(80),
    "PROVISIONAL_DIAGNOSIS" TEXT,
    "SECONDARY_DIAGNOSIS" TEXT,
    "CLINICAL_INDICATION" TEXT,
    "MENTAL_HEALTH_RISK" TEXT,
    "PHYSICAL_HEALTH_RISK" TEXT,
    "TREATMENT_PLAN" TEXT,
    "REQUIRED_MONITORING" VARCHAR(255),
    "NURSING_OBSERVATION" VARCHAR(50),
    "ISOLATION_REQUIRED" BOOLEAN NOT NULL DEFAULT false,
    "FALL_RISK" BOOLEAN NOT NULL DEFAULT false,
    "SUICIDE_RISK" BOOLEAN NOT NULL DEFAULT false,
    "VIOLENCE_RISK" BOOLEAN NOT NULL DEFAULT false,
    "WITHDRAWAL_RISK" BOOLEAN NOT NULL DEFAULT false,
    "SPECIAL_BED" VARCHAR(100),
    "CONSENT_STATUS" VARCHAR(80),
    "NOK_INFORMED" VARCHAR(50),
    "CLINIC_DEPARTMENT" VARCHAR(100),
    "DOCTOR_NOTE" TEXT,
    "STATUS" VARCHAR(40) NOT NULL DEFAULT 'Submitted',
    "REJECTION_REASON" TEXT,
    "REQUESTED_BY_USER_ID" INTEGER,
    "REQUESTED_BY" VARCHAR(150),
    "CREATED_BY_ID" INTEGER,
    "UPDATED_BY_ID" INTEGER,
    "CREATED_BY" VARCHAR(100),
    "CREATED_DATE" TIMESTAMP(3),
    "UPDATED_BY" VARCHAR(100),
    "UPDATED_DATE" TIMESTAMP(3),

    CONSTRAINT "ADMISSION_REQUESTS_pkey" PRIMARY KEY ("ADMISSION_REQUEST_ID")
);

CREATE UNIQUE INDEX IF NOT EXISTS "ADMISSION_REQUESTS_REQUEST_NO_key" ON "ADMISSION_REQUESTS"("REQUEST_NO");
CREATE INDEX IF NOT EXISTS "ADMISSION_REQUESTS_PERSON_ID_idx" ON "ADMISSION_REQUESTS"("PERSON_ID");
CREATE INDEX IF NOT EXISTS "ADMISSION_REQUESTS_STATUS_idx" ON "ADMISSION_REQUESTS"("STATUS");
CREATE INDEX IF NOT EXISTS "ADMISSION_REQUESTS_REQUESTED_BY_USER_ID_idx" ON "ADMISSION_REQUESTS"("REQUESTED_BY_USER_ID");
CREATE INDEX IF NOT EXISTS "ADMISSION_REQUESTS_CREATED_DATE_idx" ON "ADMISSION_REQUESTS"("CREATED_DATE");

DO $$ BEGIN
  ALTER TABLE "ADMISSION_REQUESTS" ADD CONSTRAINT "ADMISSION_REQUESTS_PERSON_ID_fkey"
    FOREIGN KEY ("PERSON_ID") REFERENCES "PERSONS"("PERSON_ID") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "ADMISSION_REQUESTS" ADD CONSTRAINT "ADMISSION_REQUESTS_WARD_ID_fkey"
    FOREIGN KEY ("WARD_ID") REFERENCES "WARDS"("WARD_ID") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
