-- Laboratory blood bank inventory + request / crossmatch workflow

CREATE TABLE IF NOT EXISTS "BLOOD_UNITS" (
    "BLOOD_UNIT_ID" SERIAL NOT NULL,
    "UNIT_NO" VARCHAR(50) NOT NULL,
    "BLOOD_GROUP" VARCHAR(10) NOT NULL,
    "COMPONENT" VARCHAR(50) NOT NULL,
    "EXPIRY_DATE" DATE NOT NULL,
    "STATUS" VARCHAR(50) NOT NULL DEFAULT 'Available',
    "DONOR_LABEL" VARCHAR(150),
    "NOTES" TEXT,
    "CREATED_BY_ID" INTEGER,
    "CREATED_BY" VARCHAR(100),
    "CREATED_DATE" TIMESTAMP(3),
    "UPDATED_BY_ID" INTEGER,
    "UPDATED_BY" VARCHAR(100),
    "UPDATED_DATE" TIMESTAMP(3),
    CONSTRAINT "BLOOD_UNITS_pkey" PRIMARY KEY ("BLOOD_UNIT_ID")
);

CREATE UNIQUE INDEX IF NOT EXISTS "BLOOD_UNITS_UNIT_NO_key" ON "BLOOD_UNITS"("UNIT_NO");
CREATE INDEX IF NOT EXISTS "BLOOD_UNITS_BLOOD_GROUP_idx" ON "BLOOD_UNITS"("BLOOD_GROUP");
CREATE INDEX IF NOT EXISTS "BLOOD_UNITS_STATUS_idx" ON "BLOOD_UNITS"("STATUS");
CREATE INDEX IF NOT EXISTS "BLOOD_UNITS_EXPIRY_DATE_idx" ON "BLOOD_UNITS"("EXPIRY_DATE");

CREATE TABLE IF NOT EXISTS "BLOOD_REQUESTS" (
    "BLOOD_REQUEST_ID" SERIAL NOT NULL,
    "REQUEST_NO" VARCHAR(50) NOT NULL,
    "PERSON_ID" INTEGER NOT NULL,
    "BLOOD_GROUP" VARCHAR(10) NOT NULL,
    "UNITS_REQUESTED" INTEGER NOT NULL,
    "DEPARTMENT" VARCHAR(100) NOT NULL,
    "DOCTOR_LABEL" VARCHAR(150),
    "STATUS" VARCHAR(50) NOT NULL DEFAULT 'Pending',
    "CROSS_MATCH_RESULT" VARCHAR(50),
    "NOTES" TEXT,
    "REJECT_REASON" VARCHAR(255),
    "ISSUED_AT" TIMESTAMP(3),
    "ISSUED_BY" VARCHAR(100),
    "COMPLETED_AT" TIMESTAMP(3),
    "COMPLETED_BY" VARCHAR(100),
    "CREATED_BY_ID" INTEGER,
    "CREATED_BY" VARCHAR(100),
    "CREATED_DATE" TIMESTAMP(3),
    "UPDATED_BY_ID" INTEGER,
    "UPDATED_BY" VARCHAR(100),
    "UPDATED_DATE" TIMESTAMP(3),
    CONSTRAINT "BLOOD_REQUESTS_pkey" PRIMARY KEY ("BLOOD_REQUEST_ID")
);

CREATE UNIQUE INDEX IF NOT EXISTS "BLOOD_REQUESTS_REQUEST_NO_key" ON "BLOOD_REQUESTS"("REQUEST_NO");
CREATE INDEX IF NOT EXISTS "BLOOD_REQUESTS_PERSON_ID_idx" ON "BLOOD_REQUESTS"("PERSON_ID");
CREATE INDEX IF NOT EXISTS "BLOOD_REQUESTS_STATUS_idx" ON "BLOOD_REQUESTS"("STATUS");
CREATE INDEX IF NOT EXISTS "BLOOD_REQUESTS_BLOOD_GROUP_idx" ON "BLOOD_REQUESTS"("BLOOD_GROUP");
CREATE INDEX IF NOT EXISTS "BLOOD_REQUESTS_CREATED_DATE_idx" ON "BLOOD_REQUESTS"("CREATED_DATE");

CREATE TABLE IF NOT EXISTS "BLOOD_REQUEST_EVENTS" (
    "EVENT_ID" SERIAL NOT NULL,
    "BLOOD_REQUEST_ID" INTEGER NOT NULL,
    "ACTION" VARCHAR(100) NOT NULL,
    "REASON" VARCHAR(255),
    "ACTOR_LABEL" VARCHAR(100),
    "ACTOR_ID" INTEGER,
    "CREATED_DATE" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "BLOOD_REQUEST_EVENTS_pkey" PRIMARY KEY ("EVENT_ID")
);

CREATE INDEX IF NOT EXISTS "BLOOD_REQUEST_EVENTS_BLOOD_REQUEST_ID_idx" ON "BLOOD_REQUEST_EVENTS"("BLOOD_REQUEST_ID");
CREATE INDEX IF NOT EXISTS "BLOOD_REQUEST_EVENTS_CREATED_DATE_idx" ON "BLOOD_REQUEST_EVENTS"("CREATED_DATE");

CREATE TABLE IF NOT EXISTS "BLOOD_CROSSMATCHES" (
    "CROSSMATCH_ID" SERIAL NOT NULL,
    "CROSSMATCH_NO" VARCHAR(50) NOT NULL,
    "BLOOD_REQUEST_ID" INTEGER,
    "BLOOD_UNIT_ID" INTEGER,
    "PERSON_LABEL" VARCHAR(200),
    "BLOOD_GROUP" VARCHAR(10) NOT NULL,
    "RESULT" VARCHAR(50) NOT NULL DEFAULT 'Pending',
    "NOTES" TEXT,
    "CREATED_BY_ID" INTEGER,
    "CREATED_BY" VARCHAR(100),
    "CREATED_DATE" TIMESTAMP(3),
    CONSTRAINT "BLOOD_CROSSMATCHES_pkey" PRIMARY KEY ("CROSSMATCH_ID")
);

CREATE UNIQUE INDEX IF NOT EXISTS "BLOOD_CROSSMATCHES_CROSSMATCH_NO_key" ON "BLOOD_CROSSMATCHES"("CROSSMATCH_NO");
CREATE INDEX IF NOT EXISTS "BLOOD_CROSSMATCHES_BLOOD_REQUEST_ID_idx" ON "BLOOD_CROSSMATCHES"("BLOOD_REQUEST_ID");
CREATE INDEX IF NOT EXISTS "BLOOD_CROSSMATCHES_BLOOD_UNIT_ID_idx" ON "BLOOD_CROSSMATCHES"("BLOOD_UNIT_ID");
CREATE INDEX IF NOT EXISTS "BLOOD_CROSSMATCHES_RESULT_idx" ON "BLOOD_CROSSMATCHES"("RESULT");
CREATE INDEX IF NOT EXISTS "BLOOD_CROSSMATCHES_CREATED_DATE_idx" ON "BLOOD_CROSSMATCHES"("CREATED_DATE");

DO $$ BEGIN
  ALTER TABLE "BLOOD_REQUESTS" ADD CONSTRAINT "BLOOD_REQUESTS_PERSON_ID_fkey"
    FOREIGN KEY ("PERSON_ID") REFERENCES "PERSONS"("PERSON_ID") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "BLOOD_REQUEST_EVENTS" ADD CONSTRAINT "BLOOD_REQUEST_EVENTS_BLOOD_REQUEST_ID_fkey"
    FOREIGN KEY ("BLOOD_REQUEST_ID") REFERENCES "BLOOD_REQUESTS"("BLOOD_REQUEST_ID") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "BLOOD_CROSSMATCHES" ADD CONSTRAINT "BLOOD_CROSSMATCHES_BLOOD_REQUEST_ID_fkey"
    FOREIGN KEY ("BLOOD_REQUEST_ID") REFERENCES "BLOOD_REQUESTS"("BLOOD_REQUEST_ID") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "BLOOD_CROSSMATCHES" ADD CONSTRAINT "BLOOD_CROSSMATCHES_BLOOD_UNIT_ID_fkey"
    FOREIGN KEY ("BLOOD_UNIT_ID") REFERENCES "BLOOD_UNITS"("BLOOD_UNIT_ID") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
