-- Expand ENCOUNTERS clinical note sections for full doctor documentation.
ALTER TABLE "ENCOUNTERS" ADD COLUMN IF NOT EXISTS "PAST_MEDICAL_HISTORY" TEXT;
ALTER TABLE "ENCOUNTERS" ADD COLUMN IF NOT EXISTS "DRUG_HISTORY" TEXT;
ALTER TABLE "ENCOUNTERS" ADD COLUMN IF NOT EXISTS "ALLERGY_HISTORY" TEXT;
ALTER TABLE "ENCOUNTERS" ADD COLUMN IF NOT EXISTS "FAMILY_HISTORY" TEXT;
ALTER TABLE "ENCOUNTERS" ADD COLUMN IF NOT EXISTS "SOCIAL_HISTORY" TEXT;
ALTER TABLE "ENCOUNTERS" ADD COLUMN IF NOT EXISTS "FOLLOW_UP_PLAN" TEXT;
