-- Pharmacy hospital-level alert thresholds (singleton)

CREATE TABLE IF NOT EXISTS "PHARMACY_SETTINGS" (
    "SETTINGS_ID" INTEGER NOT NULL DEFAULT 1,
    "DEFAULT_REORDER_LEVEL" INTEGER NOT NULL DEFAULT 50,
    "EXPIRING_SOON_DAYS" INTEGER NOT NULL DEFAULT 180,
    "EXPIRY_CRITICAL_DAYS" INTEGER NOT NULL DEFAULT 30,
    "EXPIRY_WARNING_DAYS" INTEGER NOT NULL DEFAULT 90,
    "RECEIVE_STOCK_WARN_DAYS" INTEGER NOT NULL DEFAULT 180,
    "RECENTLY_RECEIVED_DAYS" INTEGER NOT NULL DEFAULT 7,
    "CONTROLLED_REQUIRES_WITNESS" VARCHAR(1) NOT NULL DEFAULT 'Y',
    "LOW_STOCK_ALERT_ENABLED" VARCHAR(1) NOT NULL DEFAULT 'Y',
    "EXPIRY_ALERT_ENABLED" VARCHAR(1) NOT NULL DEFAULT 'Y',
    "UPDATED_BY_ID" INTEGER,
    "UPDATED_BY" VARCHAR(100),
    "UPDATED_DATE" TIMESTAMP(3),
    "CREATED_DATE" TIMESTAMP(3),

    CONSTRAINT "PHARMACY_SETTINGS_pkey" PRIMARY KEY ("SETTINGS_ID")
);

INSERT INTO "PHARMACY_SETTINGS" ("SETTINGS_ID", "CREATED_DATE")
VALUES (1, CURRENT_TIMESTAMP)
ON CONFLICT ("SETTINGS_ID") DO NOTHING;
