-- Pharmacy procurement + inventory:
-- SUPPLIERS, DRUGS, DRUG_BATCHES (expiry/amount per batch),
-- PURCHASE_REQUESTS, PURCHASE_ORDERS, PURCHASE_ORDER_ITEMS, GOODS_RECEIVED_NOTES

-- CreateTable
CREATE TABLE IF NOT EXISTS "SUPPLIERS" (
    "SUPPLIER_ID" SERIAL NOT NULL,
    "NAME" VARCHAR(255) NOT NULL,
    "CONTACT_PERSON" VARCHAR(255),
    "PHONE" VARCHAR(50),
    "EMAIL" VARCHAR(255),
    "ADDRESS" VARCHAR(500),
    "CATEGORIES" VARCHAR(500),
    "PERFORMANCE" INTEGER NOT NULL DEFAULT 0,
    "STATUS" VARCHAR(50) NOT NULL DEFAULT 'Active',
    "NOTES" TEXT,
    "CREATED_BY_ID" INTEGER,
    "CREATED_BY" VARCHAR(100),
    "CREATED_DATE" TIMESTAMP(3),
    "UPDATED_BY_ID" INTEGER,
    "UPDATED_BY" VARCHAR(100),
    "UPDATED_DATE" TIMESTAMP(3),

    CONSTRAINT "SUPPLIERS_pkey" PRIMARY KEY ("SUPPLIER_ID")
);

CREATE INDEX IF NOT EXISTS "SUPPLIERS_NAME_idx" ON "SUPPLIERS"("NAME");
CREATE INDEX IF NOT EXISTS "SUPPLIERS_STATUS_idx" ON "SUPPLIERS"("STATUS");

-- CreateTable
CREATE TABLE IF NOT EXISTS "DRUGS" (
    "DRUG_ID" SERIAL NOT NULL,
    "NAME" VARCHAR(255) NOT NULL,
    "GENERIC_NAME" VARCHAR(255),
    "CATEGORY" VARCHAR(100),
    "FORM" VARCHAR(50),
    "STRENGTH" VARCHAR(100),
    "UNIT" VARCHAR(50),
    "UNIT_PRICE" DECIMAL(14,2) NOT NULL DEFAULT 0,
    "REORDER_LEVEL" INTEGER NOT NULL DEFAULT 0,
    "SHELF" VARCHAR(50),
    "CONTROLLED_FLAG" VARCHAR(10) NOT NULL DEFAULT 'N',
    "STATUS" VARCHAR(50) NOT NULL DEFAULT 'Active',
    "SUPPLIER_ID" INTEGER,
    "CREATED_BY_ID" INTEGER,
    "CREATED_BY" VARCHAR(100),
    "CREATED_DATE" TIMESTAMP(3),
    "UPDATED_BY_ID" INTEGER,
    "UPDATED_BY" VARCHAR(100),
    "UPDATED_DATE" TIMESTAMP(3),

    CONSTRAINT "DRUGS_pkey" PRIMARY KEY ("DRUG_ID")
);

CREATE INDEX IF NOT EXISTS "DRUGS_NAME_idx" ON "DRUGS"("NAME");
CREATE INDEX IF NOT EXISTS "DRUGS_CATEGORY_idx" ON "DRUGS"("CATEGORY");
CREATE INDEX IF NOT EXISTS "DRUGS_SUPPLIER_ID_idx" ON "DRUGS"("SUPPLIER_ID");
CREATE INDEX IF NOT EXISTS "DRUGS_STATUS_idx" ON "DRUGS"("STATUS");

-- CreateTable
CREATE TABLE IF NOT EXISTS "DRUG_BATCHES" (
    "BATCH_ID" SERIAL NOT NULL,
    "DRUG_ID" INTEGER NOT NULL,
    "BATCH_NO" VARCHAR(100) NOT NULL,
    "MFG_DATE" TIMESTAMP(3),
    "EXPIRY_DATE" TIMESTAMP(3),
    "QTY_RECEIVED" INTEGER NOT NULL DEFAULT 0,
    "QTY_AVAILABLE" INTEGER NOT NULL DEFAULT 0,
    "UNIT_COST" DECIMAL(14,2),
    "SELLING_PRICE" DECIMAL(14,2),
    "LOCATION" VARCHAR(100),
    "GRN_ID" INTEGER,
    "STATUS" VARCHAR(50) NOT NULL DEFAULT 'Available',
    "CREATED_BY_ID" INTEGER,
    "CREATED_BY" VARCHAR(100),
    "CREATED_DATE" TIMESTAMP(3),
    "UPDATED_BY_ID" INTEGER,
    "UPDATED_BY" VARCHAR(100),
    "UPDATED_DATE" TIMESTAMP(3),

    CONSTRAINT "DRUG_BATCHES_pkey" PRIMARY KEY ("BATCH_ID")
);

CREATE INDEX IF NOT EXISTS "DRUG_BATCHES_DRUG_ID_idx" ON "DRUG_BATCHES"("DRUG_ID");
CREATE INDEX IF NOT EXISTS "DRUG_BATCHES_EXPIRY_DATE_idx" ON "DRUG_BATCHES"("EXPIRY_DATE");
CREATE INDEX IF NOT EXISTS "DRUG_BATCHES_STATUS_idx" ON "DRUG_BATCHES"("STATUS");

-- CreateTable
CREATE TABLE IF NOT EXISTS "PURCHASE_REQUESTS" (
    "REQUEST_ID" SERIAL NOT NULL,
    "REQUEST_NO" VARCHAR(50) NOT NULL,
    "DRUG_ID" INTEGER NOT NULL,
    "QTY" INTEGER NOT NULL,
    "PRIORITY" VARCHAR(50) NOT NULL DEFAULT 'Normal',
    "STATUS" VARCHAR(50) NOT NULL DEFAULT 'Submitted',
    "REASON" VARCHAR(500),
    "NOTE" TEXT,
    "REQUESTED_BY" VARCHAR(100),
    "APPROVED_BY" VARCHAR(100),
    "APPROVED_DATE" TIMESTAMP(3),
    "CREATED_BY_ID" INTEGER,
    "CREATED_BY" VARCHAR(100),
    "CREATED_DATE" TIMESTAMP(3),
    "UPDATED_BY_ID" INTEGER,
    "UPDATED_BY" VARCHAR(100),
    "UPDATED_DATE" TIMESTAMP(3),

    CONSTRAINT "PURCHASE_REQUESTS_pkey" PRIMARY KEY ("REQUEST_ID")
);

CREATE UNIQUE INDEX IF NOT EXISTS "PURCHASE_REQUESTS_REQUEST_NO_key" ON "PURCHASE_REQUESTS"("REQUEST_NO");
CREATE INDEX IF NOT EXISTS "PURCHASE_REQUESTS_DRUG_ID_idx" ON "PURCHASE_REQUESTS"("DRUG_ID");
CREATE INDEX IF NOT EXISTS "PURCHASE_REQUESTS_STATUS_idx" ON "PURCHASE_REQUESTS"("STATUS");
CREATE INDEX IF NOT EXISTS "PURCHASE_REQUESTS_PRIORITY_idx" ON "PURCHASE_REQUESTS"("PRIORITY");
CREATE INDEX IF NOT EXISTS "PURCHASE_REQUESTS_CREATED_DATE_idx" ON "PURCHASE_REQUESTS"("CREATED_DATE");

-- CreateTable
CREATE TABLE IF NOT EXISTS "PURCHASE_ORDERS" (
    "PO_ID" SERIAL NOT NULL,
    "PO_NO" VARCHAR(50) NOT NULL,
    "SUPPLIER_ID" INTEGER NOT NULL,
    "TOTAL" DECIMAL(14,2) NOT NULL DEFAULT 0,
    "APPROVAL_STATUS" VARCHAR(50) NOT NULL DEFAULT 'Pending',
    "DELIVERY_STATUS" VARCHAR(50) NOT NULL DEFAULT 'Not Sent',
    "STATUS" VARCHAR(50) NOT NULL DEFAULT 'Pending Approval',
    "EXPECTED_DATE" TIMESTAMP(3),
    "PAYMENT_TERMS" VARCHAR(100),
    "NOTES" TEXT,
    "APPROVED_BY" VARCHAR(100),
    "APPROVED_DATE" TIMESTAMP(3),
    "CREATED_BY_ID" INTEGER,
    "CREATED_BY" VARCHAR(100),
    "CREATED_DATE" TIMESTAMP(3),
    "UPDATED_BY_ID" INTEGER,
    "UPDATED_BY" VARCHAR(100),
    "UPDATED_DATE" TIMESTAMP(3),

    CONSTRAINT "PURCHASE_ORDERS_pkey" PRIMARY KEY ("PO_ID")
);

CREATE UNIQUE INDEX IF NOT EXISTS "PURCHASE_ORDERS_PO_NO_key" ON "PURCHASE_ORDERS"("PO_NO");
CREATE INDEX IF NOT EXISTS "PURCHASE_ORDERS_SUPPLIER_ID_idx" ON "PURCHASE_ORDERS"("SUPPLIER_ID");
CREATE INDEX IF NOT EXISTS "PURCHASE_ORDERS_STATUS_idx" ON "PURCHASE_ORDERS"("STATUS");
CREATE INDEX IF NOT EXISTS "PURCHASE_ORDERS_APPROVAL_STATUS_idx" ON "PURCHASE_ORDERS"("APPROVAL_STATUS");
CREATE INDEX IF NOT EXISTS "PURCHASE_ORDERS_CREATED_DATE_idx" ON "PURCHASE_ORDERS"("CREATED_DATE");

-- CreateTable
CREATE TABLE IF NOT EXISTS "PURCHASE_ORDER_ITEMS" (
    "PO_ITEM_ID" SERIAL NOT NULL,
    "PO_ID" INTEGER NOT NULL,
    "DRUG_ID" INTEGER NOT NULL,
    "QTY" INTEGER NOT NULL,
    "UNIT_COST" DECIMAL(14,2) NOT NULL DEFAULT 0,
    "QTY_RECEIVED" INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT "PURCHASE_ORDER_ITEMS_pkey" PRIMARY KEY ("PO_ITEM_ID")
);

CREATE INDEX IF NOT EXISTS "PURCHASE_ORDER_ITEMS_PO_ID_idx" ON "PURCHASE_ORDER_ITEMS"("PO_ID");
CREATE INDEX IF NOT EXISTS "PURCHASE_ORDER_ITEMS_DRUG_ID_idx" ON "PURCHASE_ORDER_ITEMS"("DRUG_ID");

-- CreateTable
CREATE TABLE IF NOT EXISTS "GOODS_RECEIVED_NOTES" (
    "GRN_ID" SERIAL NOT NULL,
    "GRN_NO" VARCHAR(50) NOT NULL,
    "PO_ID" INTEGER,
    "DRUG_ID" INTEGER NOT NULL,
    "BATCH_NO" VARCHAR(100) NOT NULL,
    "MFG_DATE" TIMESTAMP(3),
    "EXPIRY_DATE" TIMESTAMP(3),
    "QTY_ORDERED" INTEGER NOT NULL DEFAULT 0,
    "QTY_RECEIVED" INTEGER NOT NULL DEFAULT 0,
    "QTY_DAMAGED" INTEGER NOT NULL DEFAULT 0,
    "QTY_ACCEPTED" INTEGER NOT NULL DEFAULT 0,
    "UNIT_COST" DECIMAL(14,2),
    "LOCATION" VARCHAR(100),
    "RECEIVED_BY" VARCHAR(100),
    "RECEIVED_DATE" TIMESTAMP(3),
    "CREATED_BY_ID" INTEGER,
    "CREATED_BY" VARCHAR(100),
    "CREATED_DATE" TIMESTAMP(3),

    CONSTRAINT "GOODS_RECEIVED_NOTES_pkey" PRIMARY KEY ("GRN_ID")
);

CREATE UNIQUE INDEX IF NOT EXISTS "GOODS_RECEIVED_NOTES_GRN_NO_key" ON "GOODS_RECEIVED_NOTES"("GRN_NO");
CREATE INDEX IF NOT EXISTS "GOODS_RECEIVED_NOTES_PO_ID_idx" ON "GOODS_RECEIVED_NOTES"("PO_ID");
CREATE INDEX IF NOT EXISTS "GOODS_RECEIVED_NOTES_DRUG_ID_idx" ON "GOODS_RECEIVED_NOTES"("DRUG_ID");
CREATE INDEX IF NOT EXISTS "GOODS_RECEIVED_NOTES_RECEIVED_DATE_idx" ON "GOODS_RECEIVED_NOTES"("RECEIVED_DATE");

-- Foreign keys (idempotent)
DO $$ BEGIN
  ALTER TABLE "DRUGS" ADD CONSTRAINT "DRUGS_SUPPLIER_ID_fkey"
    FOREIGN KEY ("SUPPLIER_ID") REFERENCES "SUPPLIERS"("SUPPLIER_ID") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "DRUG_BATCHES" ADD CONSTRAINT "DRUG_BATCHES_DRUG_ID_fkey"
    FOREIGN KEY ("DRUG_ID") REFERENCES "DRUGS"("DRUG_ID") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "DRUG_BATCHES" ADD CONSTRAINT "DRUG_BATCHES_GRN_ID_fkey"
    FOREIGN KEY ("GRN_ID") REFERENCES "GOODS_RECEIVED_NOTES"("GRN_ID") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "PURCHASE_REQUESTS" ADD CONSTRAINT "PURCHASE_REQUESTS_DRUG_ID_fkey"
    FOREIGN KEY ("DRUG_ID") REFERENCES "DRUGS"("DRUG_ID") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "PURCHASE_ORDERS" ADD CONSTRAINT "PURCHASE_ORDERS_SUPPLIER_ID_fkey"
    FOREIGN KEY ("SUPPLIER_ID") REFERENCES "SUPPLIERS"("SUPPLIER_ID") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "PURCHASE_ORDER_ITEMS" ADD CONSTRAINT "PURCHASE_ORDER_ITEMS_PO_ID_fkey"
    FOREIGN KEY ("PO_ID") REFERENCES "PURCHASE_ORDERS"("PO_ID") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "PURCHASE_ORDER_ITEMS" ADD CONSTRAINT "PURCHASE_ORDER_ITEMS_DRUG_ID_fkey"
    FOREIGN KEY ("DRUG_ID") REFERENCES "DRUGS"("DRUG_ID") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "GOODS_RECEIVED_NOTES" ADD CONSTRAINT "GOODS_RECEIVED_NOTES_PO_ID_fkey"
    FOREIGN KEY ("PO_ID") REFERENCES "PURCHASE_ORDERS"("PO_ID") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "GOODS_RECEIVED_NOTES" ADD CONSTRAINT "GOODS_RECEIVED_NOTES_DRUG_ID_fkey"
    FOREIGN KEY ("DRUG_ID") REFERENCES "DRUGS"("DRUG_ID") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
