-- AlterTable
ALTER TABLE "AUDITS" ADD COLUMN IF NOT EXISTS "AUDIT_TYPE" VARCHAR(100);
ALTER TABLE "AUDITS" ADD COLUMN IF NOT EXISTS "ENTITY" VARCHAR(100);
ALTER TABLE "AUDITS" ADD COLUMN IF NOT EXISTS "ENTITY_ID" VARCHAR(100);

CREATE INDEX IF NOT EXISTS "AUDITS_AUDIT_TYPE_idx" ON "AUDITS"("AUDIT_TYPE");

-- CreateTable
CREATE TABLE IF NOT EXISTS "TRIAGE" (
    "TRIAGE_ID" SERIAL NOT NULL,
    "PERSON_ID" INTEGER NOT NULL,
    "QUEUE_NO" VARCHAR(50) NOT NULL,
    "CLINIC" VARCHAR(100),
    "STATUS" VARCHAR(50) NOT NULL,
    "PRIORITY" VARCHAR(50) NOT NULL DEFAULT 'Routine',
    "PRIORITY_REASON" VARCHAR(500),
    "PATIENT_TYPE" VARCHAR(50),
    "ARRIVAL_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "WEIGHT_KG" DECIMAL(8,2),
    "HEIGHT_CM" DECIMAL(8,2),
    "BMI" DECIMAL(8,2),
    "BLOOD_PRESSURE" VARCHAR(20),
    "TEMPERATURE_C" DECIMAL(5,2),
    "PULSE_BPM" INTEGER,
    "RESPIRATORY_RATE" INTEGER,
    "SPO2_PCT" DECIMAL(5,2),
    "NOTES" TEXT,
    "CREATED_BY_ID" INTEGER,
    "UPDATED_BY_ID" INTEGER,
    "CREATED_BY" VARCHAR(100),
    "CREATED_DATE" TIMESTAMP(3),
    "UPDATED_BY" VARCHAR(100),
    "UPDATED_DATE" TIMESTAMP(3),

    CONSTRAINT "TRIAGE_pkey" PRIMARY KEY ("TRIAGE_ID")
);

CREATE UNIQUE INDEX IF NOT EXISTS "TRIAGE_QUEUE_NO_key" ON "TRIAGE"("QUEUE_NO");
CREATE INDEX IF NOT EXISTS "TRIAGE_PERSON_ID_idx" ON "TRIAGE"("PERSON_ID");
CREATE INDEX IF NOT EXISTS "TRIAGE_STATUS_idx" ON "TRIAGE"("STATUS");
CREATE INDEX IF NOT EXISTS "TRIAGE_PRIORITY_idx" ON "TRIAGE"("PRIORITY");
CREATE INDEX IF NOT EXISTS "TRIAGE_ARRIVAL_AT_idx" ON "TRIAGE"("ARRIVAL_AT");
CREATE INDEX IF NOT EXISTS "TRIAGE_CLINIC_idx" ON "TRIAGE"("CLINIC");

DO $$ BEGIN
  ALTER TABLE "TRIAGE" ADD CONSTRAINT "TRIAGE_PERSON_ID_fkey"
    FOREIGN KEY ("PERSON_ID") REFERENCES "PERSONS"("PERSON_ID") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "TRIAGE" ADD CONSTRAINT "TRIAGE_CREATED_BY_ID_fkey"
    FOREIGN KEY ("CREATED_BY_ID") REFERENCES "USERS"("USER_ID") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "TRIAGE" ADD CONSTRAINT "TRIAGE_UPDATED_BY_ID_fkey"
    FOREIGN KEY ("UPDATED_BY_ID") REFERENCES "USERS"("USER_ID") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
