-- Doctor research registry, trials, clinical audit projects

CREATE TABLE IF NOT EXISTS "RESEARCH_REGISTRY_ENTRIES" (
    "ENTRY_ID" SERIAL PRIMARY KEY,
    "PERSON_ID" INTEGER,
    "PATIENT_LABEL" VARCHAR(200) NOT NULL,
    "DIAGNOSIS" VARCHAR(255) NOT NULL,
    "ELIGIBILITY" VARCHAR(50) NOT NULL DEFAULT 'Eligible',
    "CONSENT" VARCHAR(30) NOT NULL DEFAULT 'Pending',
    "ENROLLED_BY" VARCHAR(150),
    "STUDY_GROUP" VARCHAR(200) NOT NULL,
    "STATUS" VARCHAR(30) NOT NULL DEFAULT 'Active',
    "CLINIC" VARCHAR(30) NOT NULL DEFAULT 'OPC',
    "CREATED_BY_ID" INTEGER,
    "CREATED_BY" VARCHAR(100),
    "CREATED_DATE" TIMESTAMP(3),
    "UPDATED_BY_ID" INTEGER,
    "UPDATED_BY" VARCHAR(100),
    "UPDATED_DATE" TIMESTAMP(3),
    "DELETED_FLAG" VARCHAR(1) DEFAULT 'N'
);

CREATE INDEX IF NOT EXISTS "RESEARCH_REGISTRY_ENTRIES_STATUS_idx" ON "RESEARCH_REGISTRY_ENTRIES"("STATUS");
CREATE INDEX IF NOT EXISTS "RESEARCH_REGISTRY_ENTRIES_CLINIC_idx" ON "RESEARCH_REGISTRY_ENTRIES"("CLINIC");
CREATE INDEX IF NOT EXISTS "RESEARCH_REGISTRY_ENTRIES_CREATED_DATE_idx" ON "RESEARCH_REGISTRY_ENTRIES"("CREATED_DATE");

CREATE TABLE IF NOT EXISTS "RESEARCH_TRIALS" (
    "TRIAL_ID" SERIAL PRIMARY KEY,
    "NAME" VARCHAR(255) NOT NULL,
    "PI" VARCHAR(150) NOT NULL,
    "ELIGIBLE_COUNT" INTEGER NOT NULL DEFAULT 0,
    "ENROLLED_COUNT" INTEGER NOT NULL DEFAULT 0,
    "START_DATE" TIMESTAMP(3),
    "STATUS" VARCHAR(30) NOT NULL DEFAULT 'Recruiting',
    "CREATED_BY_ID" INTEGER,
    "CREATED_BY" VARCHAR(100),
    "CREATED_DATE" TIMESTAMP(3),
    "UPDATED_BY_ID" INTEGER,
    "UPDATED_BY" VARCHAR(100),
    "UPDATED_DATE" TIMESTAMP(3),
    "DELETED_FLAG" VARCHAR(1) DEFAULT 'N'
);

CREATE INDEX IF NOT EXISTS "RESEARCH_TRIALS_STATUS_idx" ON "RESEARCH_TRIALS"("STATUS");
CREATE INDEX IF NOT EXISTS "RESEARCH_TRIALS_CREATED_DATE_idx" ON "RESEARCH_TRIALS"("CREATED_DATE");

CREATE TABLE IF NOT EXISTS "CLINICAL_AUDIT_PROJECTS" (
    "PROJECT_ID" SERIAL PRIMARY KEY,
    "TITLE" VARCHAR(255) NOT NULL,
    "DEPARTMENT" VARCHAR(150) NOT NULL,
    "LEAD" VARCHAR(150) NOT NULL,
    "INDICATOR" VARCHAR(255) NOT NULL,
    "STANDARD" VARCHAR(100) NOT NULL,
    "PERFORMANCE" VARCHAR(100),
    "STATUS" VARCHAR(30) NOT NULL DEFAULT 'Planning',
    "CREATED_BY_ID" INTEGER,
    "CREATED_BY" VARCHAR(100),
    "CREATED_DATE" TIMESTAMP(3),
    "UPDATED_BY_ID" INTEGER,
    "UPDATED_BY" VARCHAR(100),
    "UPDATED_DATE" TIMESTAMP(3),
    "DELETED_FLAG" VARCHAR(1) DEFAULT 'N'
);

CREATE INDEX IF NOT EXISTS "CLINICAL_AUDIT_PROJECTS_STATUS_idx" ON "CLINICAL_AUDIT_PROJECTS"("STATUS");
CREATE INDEX IF NOT EXISTS "CLINICAL_AUDIT_PROJECTS_DEPARTMENT_idx" ON "CLINICAL_AUDIT_PROJECTS"("DEPARTMENT");
CREATE INDEX IF NOT EXISTS "CLINICAL_AUDIT_PROJECTS_CREATED_DATE_idx" ON "CLINICAL_AUDIT_PROJECTS"("CREATED_DATE");
