-- Imaging study files for radiology image upload (Azure Blob / local storage)

CREATE TABLE IF NOT EXISTS "IMAGING_STUDY_FILES" (
    "FILE_ID" SERIAL NOT NULL,
    "IMAGING_REQUEST_ID" INTEGER NOT NULL,
    "STUDY_UID" VARCHAR(120),
    "KIND" VARCHAR(40) NOT NULL DEFAULT 'preview',
    "ORIGINAL_NAME" VARCHAR(255) NOT NULL,
    "CONTENT_TYPE" VARCHAR(120) NOT NULL,
    "SIZE_BYTES" INTEGER NOT NULL DEFAULT 0,
    "STORAGE_PROVIDER" VARCHAR(20) NOT NULL,
    "BLOB_PATH" VARCHAR(500) NOT NULL,
    "UPLOADED_BY_ID" INTEGER,
    "UPLOADED_BY" VARCHAR(120),
    "CREATED_DATE" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "IMAGING_STUDY_FILES_pkey" PRIMARY KEY ("FILE_ID")
);

CREATE INDEX IF NOT EXISTS "IMAGING_STUDY_FILES_IMAGING_REQUEST_ID_idx" ON "IMAGING_STUDY_FILES"("IMAGING_REQUEST_ID");
CREATE INDEX IF NOT EXISTS "IMAGING_STUDY_FILES_STUDY_UID_idx" ON "IMAGING_STUDY_FILES"("STUDY_UID");
CREATE INDEX IF NOT EXISTS "IMAGING_STUDY_FILES_KIND_idx" ON "IMAGING_STUDY_FILES"("KIND");

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'IMAGING_STUDY_FILES_IMAGING_REQUEST_ID_fkey'
  ) THEN
    ALTER TABLE "IMAGING_STUDY_FILES"
      ADD CONSTRAINT "IMAGING_STUDY_FILES_IMAGING_REQUEST_ID_fkey"
      FOREIGN KEY ("IMAGING_REQUEST_ID") REFERENCES "IMAGING_REQUESTS"("IMAGING_REQUEST_ID")
      ON DELETE CASCADE ON UPDATE CASCADE;
  END IF;
END $$;
