-- Walk-in pharmacy sales: request → cashier pay → dispense

CREATE TABLE IF NOT EXISTS "PHARMACY_SALES" (
    "SALE_ID" SERIAL NOT NULL,
    "SALE_NO" VARCHAR(50) NOT NULL,
    "PERSON_ID" INTEGER NOT NULL,
    "STATUS" VARCHAR(50) NOT NULL DEFAULT 'Awaiting Payment',
    "PAYMENT_STATUS" VARCHAR(50) NOT NULL DEFAULT 'Unpaid',
    "PAYMENT_CHANNEL" VARCHAR(50),
    "PAYMENT_REF" VARCHAR(100),
    "PAID_AT" TIMESTAMP(3),
    "PAID_BY" VARCHAR(100),
    "PAID_BY_ID" INTEGER,
    "TOTAL" DECIMAL(14,2) NOT NULL DEFAULT 0,
    "NOTES" TEXT,
    "DISPENSED_AT" TIMESTAMP(3),
    "DISPENSED_BY" VARCHAR(100),
    "DISPENSED_BY_ID" INTEGER,
    "CREATED_BY_ID" INTEGER,
    "CREATED_BY" VARCHAR(100),
    "CREATED_DATE" TIMESTAMP(3),
    "UPDATED_BY_ID" INTEGER,
    "UPDATED_BY" VARCHAR(100),
    "UPDATED_DATE" TIMESTAMP(3),

    CONSTRAINT "PHARMACY_SALES_pkey" PRIMARY KEY ("SALE_ID")
);

CREATE UNIQUE INDEX IF NOT EXISTS "PHARMACY_SALES_SALE_NO_key" ON "PHARMACY_SALES"("SALE_NO");
CREATE INDEX IF NOT EXISTS "PHARMACY_SALES_PERSON_ID_idx" ON "PHARMACY_SALES"("PERSON_ID");
CREATE INDEX IF NOT EXISTS "PHARMACY_SALES_STATUS_idx" ON "PHARMACY_SALES"("STATUS");
CREATE INDEX IF NOT EXISTS "PHARMACY_SALES_PAYMENT_STATUS_idx" ON "PHARMACY_SALES"("PAYMENT_STATUS");
CREATE INDEX IF NOT EXISTS "PHARMACY_SALES_CREATED_DATE_idx" ON "PHARMACY_SALES"("CREATED_DATE");

CREATE TABLE IF NOT EXISTS "PHARMACY_SALE_ITEMS" (
    "ITEM_ID" SERIAL NOT NULL,
    "SALE_ID" INTEGER NOT NULL,
    "DRUG_ID" INTEGER NOT NULL,
    "DRUG_NAME" VARCHAR(255) NOT NULL,
    "STRENGTH" VARCHAR(100),
    "FORM" VARCHAR(50),
    "UNIT" VARCHAR(50),
    "QUANTITY" INTEGER NOT NULL,
    "QTY_DISPENSED" INTEGER NOT NULL DEFAULT 0,
    "UNIT_PRICE" DECIMAL(14,2) NOT NULL DEFAULT 0,
    "LINE_STATUS" VARCHAR(50) NOT NULL DEFAULT 'Active',

    CONSTRAINT "PHARMACY_SALE_ITEMS_pkey" PRIMARY KEY ("ITEM_ID")
);

CREATE INDEX IF NOT EXISTS "PHARMACY_SALE_ITEMS_SALE_ID_idx" ON "PHARMACY_SALE_ITEMS"("SALE_ID");
CREATE INDEX IF NOT EXISTS "PHARMACY_SALE_ITEMS_DRUG_ID_idx" ON "PHARMACY_SALE_ITEMS"("DRUG_ID");

DO $$ BEGIN
  ALTER TABLE "PHARMACY_SALES"
    ADD CONSTRAINT "PHARMACY_SALES_PERSON_ID_fkey"
    FOREIGN KEY ("PERSON_ID") REFERENCES "PERSONS"("PERSON_ID")
    ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "PHARMACY_SALE_ITEMS"
    ADD CONSTRAINT "PHARMACY_SALE_ITEMS_SALE_ID_fkey"
    FOREIGN KEY ("SALE_ID") REFERENCES "PHARMACY_SALES"("SALE_ID")
    ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "PHARMACY_SALE_ITEMS"
    ADD CONSTRAINT "PHARMACY_SALE_ITEMS_DRUG_ID_fkey"
    FOREIGN KEY ("DRUG_ID") REFERENCES "DRUGS"("DRUG_ID")
    ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
