export const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  BOARD: 'BOARD',
  CMD: 'CMD',
  ADMIN: 'ADMIN',
  FINANCE: 'FINANCE',
  HR: 'HR',
  DOCTOR: 'DOCTOR',
  NURSE: 'NURSE',
  PHARMACIST: 'PHARMACIST',
  LAB: 'LAB',
  RADIOLOGY: 'RADIOLOGY',
  PSYCHIATRIC_OPC: 'PSYCHIATRIC_OPC',
  PSYCHOLOGY: 'PSYCHOLOGY',
  CHILD_ADOLESCENT: 'CHILD_ADOLESCENT',
  ADDICTION_REHAB: 'ADDICTION_REHAB',
  PSYCHOGERIATRICS: 'PSYCHOGERIATRICS',
  PHYSIOTHERAPY: 'PHYSIOTHERAPY',
  SPEECH_THERAPY: 'SPEECH_THERAPY',
  NUTRITION: 'NUTRITION',
  SOCIAL_WORK: 'SOCIAL_WORK',
  ICU: 'ICU',
  CASHIER: 'CASHIER',
  RECORDS: 'RECORDS',
  IT: 'IT',
  STAFF: 'STAFF',
  STUDENT: 'STUDENT',
  PATIENT: 'PATIENT',
} as const;

export type RoleName = (typeof ROLES)[keyof typeof ROLES];

export const ALL_ROLES: RoleName[] = Object.values(ROLES);
