-- Join table for drugs each supplier supplies (by DRUG_ID).
-- Needed because the earlier pharmacy migration was applied before SUPPLIER_DRUGS
-- existed in the SQL file (CREATE TABLE IF NOT EXISTS left the old SUPPLIERS shape).

CREATE TABLE IF NOT EXISTS "SUPPLIER_DRUGS" (
    "SUPPLIER_DRUG_ID" SERIAL NOT NULL,
    "SUPPLIER_ID" INTEGER NOT NULL,
    "DRUG_ID" INTEGER NOT NULL,

    CONSTRAINT "SUPPLIER_DRUGS_pkey" PRIMARY KEY ("SUPPLIER_DRUG_ID")
);

CREATE UNIQUE INDEX IF NOT EXISTS "SUPPLIER_DRUGS_SUPPLIER_ID_DRUG_ID_key"
  ON "SUPPLIER_DRUGS"("SUPPLIER_ID", "DRUG_ID");
CREATE INDEX IF NOT EXISTS "SUPPLIER_DRUGS_DRUG_ID_idx" ON "SUPPLIER_DRUGS"("DRUG_ID");

DO $$ BEGIN
  ALTER TABLE "SUPPLIER_DRUGS" ADD CONSTRAINT "SUPPLIER_DRUGS_SUPPLIER_ID_fkey"
    FOREIGN KEY ("SUPPLIER_ID") REFERENCES "SUPPLIERS"("SUPPLIER_ID") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "SUPPLIER_DRUGS" ADD CONSTRAINT "SUPPLIER_DRUGS_DRUG_ID_fkey"
    FOREIGN KEY ("DRUG_ID") REFERENCES "DRUGS"("DRUG_ID") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- Legacy free-text categories column is no longer in the Prisma model.
ALTER TABLE "SUPPLIERS" DROP COLUMN IF EXISTS "CATEGORIES";
