-- Public appointment booking: capacity limits + patient linkage + mock OTP verifications

ALTER TABLE "SERVICE_BOOKING_SETTINGS"
  ADD COLUMN IF NOT EXISTS "STAFF_POOL_SIZE" INTEGER NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS "ONLINE_SLOT_LIMIT" INTEGER NOT NULL DEFAULT 1;

ALTER TABLE "SERVICE_BOOKINGS"
  ADD COLUMN IF NOT EXISTS "PERSON_ID" INTEGER,
  ADD COLUMN IF NOT EXISTS "PATIENT_TYPE" VARCHAR(20) NOT NULL DEFAULT 'NEW',
  ADD COLUMN IF NOT EXISTS "PAYMENT_STATUS" VARCHAR(30) NOT NULL DEFAULT 'Pending',
  ADD COLUMN IF NOT EXISTS "FEE_BREAKDOWN" JSONB,
  ADD COLUMN IF NOT EXISTS "VERIFICATION_ID" VARCHAR(80);

CREATE INDEX IF NOT EXISTS "SERVICE_BOOKINGS_PERSON_ID_idx" ON "SERVICE_BOOKINGS"("PERSON_ID");
CREATE INDEX IF NOT EXISTS "SERVICE_BOOKINGS_PAYMENT_STATUS_idx" ON "SERVICE_BOOKINGS"("PAYMENT_STATUS");

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'SERVICE_BOOKINGS_PERSON_ID_fkey'
  ) THEN
    ALTER TABLE "SERVICE_BOOKINGS"
      ADD CONSTRAINT "SERVICE_BOOKINGS_PERSON_ID_fkey"
      FOREIGN KEY ("PERSON_ID") REFERENCES "PERSONS"("PERSON_ID")
      ON DELETE SET NULL ON UPDATE CASCADE;
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS "PUBLIC_BOOKING_VERIFICATIONS" (
  "VERIFICATION_ID" SERIAL PRIMARY KEY,
  "TOKEN" VARCHAR(80) NOT NULL,
  "PERSON_ID" INTEGER NOT NULL,
  "PHONE" VARCHAR(40) NOT NULL,
  "EMAIL" VARCHAR(255),
  "CODE" VARCHAR(10) NOT NULL,
  "EXPIRES_AT" TIMESTAMP(3) NOT NULL,
  "VERIFIED_AT" TIMESTAMP(3),
  "CREATED_DATE" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PUBLIC_BOOKING_VERIFICATIONS_TOKEN_key" UNIQUE ("TOKEN"),
  CONSTRAINT "PUBLIC_BOOKING_VERIFICATIONS_PERSON_ID_fkey"
    FOREIGN KEY ("PERSON_ID") REFERENCES "PERSONS"("PERSON_ID")
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS "PUBLIC_BOOKING_VERIFICATIONS_PERSON_ID_idx"
  ON "PUBLIC_BOOKING_VERIFICATIONS"("PERSON_ID");
CREATE INDEX IF NOT EXISTS "PUBLIC_BOOKING_VERIFICATIONS_PHONE_idx"
  ON "PUBLIC_BOOKING_VERIFICATIONS"("PHONE");
CREATE INDEX IF NOT EXISTS "PUBLIC_BOOKING_VERIFICATIONS_EXPIRES_AT_idx"
  ON "PUBLIC_BOOKING_VERIFICATIONS"("EXPIRES_AT");
