-- Imaging catalog + doctor imaging requests (pay-before-process)

CREATE TABLE IF NOT EXISTS "IMAGING_STUDIES" (
  "IMAGING_STUDY_ID" SERIAL PRIMARY KEY,
  "STUDY_CODE" VARCHAR(50) NOT NULL,
  "NAME" VARCHAR(255) NOT NULL,
  "MODALITY" VARCHAR(50) NOT NULL,
  "BODY_REGION" VARCHAR(100),
  "TURNAROUND" VARCHAR(50),
  "UNIT_PRICE" DECIMAL(14,2) NOT NULL,
  "STATUS" VARCHAR(50) NOT NULL DEFAULT 'Active',
  "CREATED_BY_ID" INTEGER,
  "CREATED_BY" VARCHAR(100),
  "CREATED_DATE" TIMESTAMP(3),
  "UPDATED_BY_ID" INTEGER,
  "UPDATED_BY" VARCHAR(100),
  "UPDATED_DATE" TIMESTAMP(3)
);
CREATE UNIQUE INDEX IF NOT EXISTS "IMAGING_STUDIES_STUDY_CODE_key" ON "IMAGING_STUDIES"("STUDY_CODE");
CREATE INDEX IF NOT EXISTS "IMAGING_STUDIES_MODALITY_idx" ON "IMAGING_STUDIES"("MODALITY");
CREATE INDEX IF NOT EXISTS "IMAGING_STUDIES_STATUS_idx" ON "IMAGING_STUDIES"("STATUS");
CREATE INDEX IF NOT EXISTS "IMAGING_STUDIES_NAME_idx" ON "IMAGING_STUDIES"("NAME");

CREATE TABLE IF NOT EXISTS "IMAGING_REQUESTS" (
  "IMAGING_REQUEST_ID" SERIAL PRIMARY KEY,
  "REQUEST_NO" VARCHAR(50) NOT NULL,
  "PERSON_ID" INTEGER NOT NULL,
  "ENCOUNTER_ID" INTEGER,
  "DOCTOR_ID" INTEGER NOT NULL,
  "SOURCE" VARCHAR(50) NOT NULL DEFAULT 'Doctor',
  "PRIORITY" VARCHAR(50) NOT NULL DEFAULT 'Routine',
  "CLINICAL_INDICATION" TEXT,
  "CLINICAL_NOTES" TEXT,
  "CONTRAST" VARCHAR(50),
  "STATUS" VARCHAR(50) NOT NULL DEFAULT 'Sent',
  "PAYMENT_STATUS" VARCHAR(50) NOT NULL DEFAULT 'Unpaid',
  "PAYMENT_CHANNEL" VARCHAR(50),
  "PAYMENT_REF" VARCHAR(100),
  "PAID_AT" TIMESTAMP(3),
  "PAID_BY" VARCHAR(100),
  "TOTAL_AMOUNT" DECIMAL(14,2) NOT NULL DEFAULT 0,
  "REJECTION_REASON" TEXT,
  "CREATED_BY_ID" INTEGER,
  "CREATED_BY" VARCHAR(100),
  "CREATED_DATE" TIMESTAMP(3),
  "UPDATED_BY_ID" INTEGER,
  "UPDATED_BY" VARCHAR(100),
  "UPDATED_DATE" TIMESTAMP(3),
  CONSTRAINT "IMAGING_REQUESTS_PERSON_ID_fkey"
    FOREIGN KEY ("PERSON_ID") REFERENCES "PERSONS"("PERSON_ID") ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT "IMAGING_REQUESTS_ENCOUNTER_ID_fkey"
    FOREIGN KEY ("ENCOUNTER_ID") REFERENCES "ENCOUNTERS"("ENCOUNTER_ID") ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT "IMAGING_REQUESTS_DOCTOR_ID_fkey"
    FOREIGN KEY ("DOCTOR_ID") REFERENCES "USERS"("USER_ID") ON DELETE RESTRICT ON UPDATE CASCADE
);
CREATE UNIQUE INDEX IF NOT EXISTS "IMAGING_REQUESTS_REQUEST_NO_key" ON "IMAGING_REQUESTS"("REQUEST_NO");
CREATE INDEX IF NOT EXISTS "IMAGING_REQUESTS_PERSON_ID_idx" ON "IMAGING_REQUESTS"("PERSON_ID");
CREATE INDEX IF NOT EXISTS "IMAGING_REQUESTS_ENCOUNTER_ID_idx" ON "IMAGING_REQUESTS"("ENCOUNTER_ID");
CREATE INDEX IF NOT EXISTS "IMAGING_REQUESTS_DOCTOR_ID_idx" ON "IMAGING_REQUESTS"("DOCTOR_ID");
CREATE INDEX IF NOT EXISTS "IMAGING_REQUESTS_STATUS_idx" ON "IMAGING_REQUESTS"("STATUS");
CREATE INDEX IF NOT EXISTS "IMAGING_REQUESTS_PAYMENT_STATUS_idx" ON "IMAGING_REQUESTS"("PAYMENT_STATUS");
CREATE INDEX IF NOT EXISTS "IMAGING_REQUESTS_SOURCE_idx" ON "IMAGING_REQUESTS"("SOURCE");
CREATE INDEX IF NOT EXISTS "IMAGING_REQUESTS_CREATED_DATE_idx" ON "IMAGING_REQUESTS"("CREATED_DATE");

CREATE TABLE IF NOT EXISTS "IMAGING_REQUEST_ITEMS" (
  "ITEM_ID" SERIAL PRIMARY KEY,
  "IMAGING_REQUEST_ID" INTEGER NOT NULL,
  "IMAGING_STUDY_ID" INTEGER NOT NULL,
  "STUDY_CODE" VARCHAR(50) NOT NULL,
  "STUDY_NAME" VARCHAR(255) NOT NULL,
  "MODALITY" VARCHAR(50) NOT NULL,
  "BODY_REGION" VARCHAR(100),
  "UNIT_PRICE" DECIMAL(14,2) NOT NULL,
  "LINE_NOTES" TEXT,
  CONSTRAINT "IMAGING_REQUEST_ITEMS_IMAGING_REQUEST_ID_fkey"
    FOREIGN KEY ("IMAGING_REQUEST_ID") REFERENCES "IMAGING_REQUESTS"("IMAGING_REQUEST_ID") ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT "IMAGING_REQUEST_ITEMS_IMAGING_STUDY_ID_fkey"
    FOREIGN KEY ("IMAGING_STUDY_ID") REFERENCES "IMAGING_STUDIES"("IMAGING_STUDY_ID") ON DELETE RESTRICT ON UPDATE CASCADE
);
CREATE INDEX IF NOT EXISTS "IMAGING_REQUEST_ITEMS_IMAGING_REQUEST_ID_idx" ON "IMAGING_REQUEST_ITEMS"("IMAGING_REQUEST_ID");
CREATE INDEX IF NOT EXISTS "IMAGING_REQUEST_ITEMS_IMAGING_STUDY_ID_idx" ON "IMAGING_REQUEST_ITEMS"("IMAGING_STUDY_ID");

-- Standard priced catalog for testing (idempotent)
INSERT INTO "IMAGING_STUDIES" ("STUDY_CODE", "NAME", "MODALITY", "BODY_REGION", "TURNAROUND", "UNIT_PRICE", "STATUS", "CREATED_BY", "CREATED_DATE")
VALUES
  ('XR-CHEST-PA', 'Chest X-Ray PA', 'X-Ray', 'Chest', 'Same day', 8500, 'Active', 'SYSTEM', NOW()),
  ('XR-SKULL', 'Skull X-Ray', 'X-Ray', 'Head', 'Same day', 8500, 'Active', 'SYSTEM', NOW()),
  ('XR-SPINE', 'Spine X-Ray', 'X-Ray', 'Spine', 'Same day', 8500, 'Active', 'SYSTEM', NOW()),
  ('XR-ABDO', 'Abdominal X-Ray', 'X-Ray', 'Abdomen', 'Same day', 8500, 'Active', 'SYSTEM', NOW()),
  ('USS-ABDO', 'Abdominal Ultrasound', 'Ultrasound', 'Abdomen', '24h', 12000, 'Active', 'SYSTEM', NOW()),
  ('USS-PELV', 'Pelvic Ultrasound', 'Ultrasound', 'Pelvis', '24h', 12000, 'Active', 'SYSTEM', NOW()),
  ('USS-OBS', 'Obstetric Ultrasound', 'Ultrasound', 'Pelvis', '24h', 15000, 'Active', 'SYSTEM', NOW()),
  ('CT-HEAD', 'CT Head', 'CT Scan', 'Head', '24h', 45000, 'Active', 'SYSTEM', NOW()),
  ('CT-CHEST', 'CT Chest', 'CT Scan', 'Chest', '24h', 55000, 'Active', 'SYSTEM', NOW()),
  ('CT-ABDO', 'CT Abdomen', 'CT Scan', 'Abdomen', '24h', 60000, 'Active', 'SYSTEM', NOW()),
  ('MRI-BRAIN', 'MRI Brain', 'MRI', 'Head', '48h', 120000, 'Active', 'SYSTEM', NOW()),
  ('MRI-SPINE', 'MRI Spine', 'MRI', 'Spine', '48h', 130000, 'Active', 'SYSTEM', NOW()),
  ('ECG-12', '12-Lead ECG', 'ECG', 'Chest', 'Same day', 5500, 'Active', 'SYSTEM', NOW()),
  ('EEG-STD', 'Standard EEG', 'EEG', 'Head', '48h', 25000, 'Active', 'SYSTEM', NOW()),
  ('MAMMO', 'Mammography', 'Mammography', 'Breast', '24h', 18000, 'Active', 'SYSTEM', NOW()),
  ('FLURO', 'Fluoroscopy', 'Fluoroscopy', 'Other', '24h', 30000, 'Active', 'SYSTEM', NOW()),
  ('ECHO', 'Echocardiography', 'Echocardiography', 'Chest', '24h', 22000, 'Active', 'SYSTEM', NOW()),
  ('PORT-XR', 'Portable X-Ray', 'Portable', 'Other', 'Same day', 15000, 'Active', 'SYSTEM', NOW())
ON CONFLICT ("STUDY_CODE") DO UPDATE SET
  "NAME" = EXCLUDED."NAME",
  "MODALITY" = EXCLUDED."MODALITY",
  "BODY_REGION" = EXCLUDED."BODY_REGION",
  "UNIT_PRICE" = EXCLUDED."UNIT_PRICE",
  "STATUS" = 'Active',
  "UPDATED_BY" = 'SYSTEM',
  "UPDATED_DATE" = NOW();
