-- Cashier settings singleton + seed defaults

CREATE TABLE IF NOT EXISTS "CASHIER_SETTINGS" (
  "SETTINGS_ID" INTEGER PRIMARY KEY DEFAULT 1,
  "CASH_ENABLED" VARCHAR(1) NOT NULL DEFAULT 'Y',
  "POS_ENABLED" VARCHAR(1) NOT NULL DEFAULT 'Y',
  "BANK_TRANSFER_ENABLED" VARCHAR(1) NOT NULL DEFAULT 'Y',
  "ONLINE_CARD_ENABLED" VARCHAR(1) NOT NULL DEFAULT 'Y',
  "WALLET_ENABLED" VARCHAR(1) NOT NULL DEFAULT 'Y',
  "NHIA_ENABLED" VARCHAR(1) NOT NULL DEFAULT 'Y',
  "HMO_ENABLED" VARCHAR(1) NOT NULL DEFAULT 'Y',
  "REQUIRE_OPEN_SHIFT" VARCHAR(1) NOT NULL DEFAULT 'N',
  "VARIANCE_TOLERANCE" DECIMAL(14,2) NOT NULL DEFAULT 0,
  "REPRINT_WATERMARK" VARCHAR(1) NOT NULL DEFAULT 'Y',
  "UPDATED_BY_ID" INTEGER,
  "UPDATED_BY" VARCHAR(100),
  "UPDATED_DATE" TIMESTAMP(3),
  "CREATED_DATE" TIMESTAMP(3)
);

INSERT INTO "CASHIER_SETTINGS" ("SETTINGS_ID", "CREATED_DATE")
VALUES (1, CURRENT_TIMESTAMP)
ON CONFLICT ("SETTINGS_ID") DO NOTHING;
