-- Discharge drafts (doctor → cashier payment clearance → Records finalize)

CREATE TABLE IF NOT EXISTS "DISCHARGE_DRAFTS" (
    "DRAFT_ID" SERIAL NOT NULL,
    "DRAFT_NO" VARCHAR(50) NOT NULL,
    "PERSON_ID" INTEGER NOT NULL,
    "ADMISSION_ID" INTEGER NOT NULL,
    "STATUS" VARCHAR(40) NOT NULL DEFAULT 'Draft',
    "ADMISSION_DIAGNOSIS" TEXT,
    "FINAL_DIAGNOSIS" TEXT,
    "REASON_FOR_ADMISSION" TEXT,
    "CLINICAL_SUMMARY" TEXT,
    "INVESTIGATIONS" TEXT,
    "TREATMENT_GIVEN" TEXT,
    "DISCHARGE_MEDICATIONS" TEXT,
    "MEDICATIONS_CHANGED" TEXT,
    "FOLLOW_UP_PLAN" TEXT,
    "NEXT_APPOINTMENT" VARCHAR(255),
    "PATIENT_EDUCATION" TEXT,
    "RISK_SAFETY_NOTES" TEXT,
    "DISCHARGE_TYPE" VARCHAR(50),
    "RETURN_REASON" TEXT,
    "REQUESTED_BY_USER_ID" INTEGER,
    "SUBMITTED_AT" TIMESTAMP(3),
    "PAYMENT_CLEARED_BY_USER_ID" INTEGER,
    "PAYMENT_CLEARED_AT" TIMESTAMP(3),
    "FINALIZED_BY_USER_ID" INTEGER,
    "FINALIZED_AT" TIMESTAMP(3),
    "CREATED_BY_ID" INTEGER,
    "CREATED_BY" VARCHAR(100),
    "CREATED_DATE" TIMESTAMP(3),
    "UPDATED_BY_ID" INTEGER,
    "UPDATED_BY" VARCHAR(100),
    "UPDATED_DATE" TIMESTAMP(3),
    CONSTRAINT "DISCHARGE_DRAFTS_pkey" PRIMARY KEY ("DRAFT_ID")
);

CREATE UNIQUE INDEX IF NOT EXISTS "DISCHARGE_DRAFTS_DRAFT_NO_key" ON "DISCHARGE_DRAFTS"("DRAFT_NO");
CREATE INDEX IF NOT EXISTS "DISCHARGE_DRAFTS_PERSON_ID_idx" ON "DISCHARGE_DRAFTS"("PERSON_ID");
CREATE INDEX IF NOT EXISTS "DISCHARGE_DRAFTS_ADMISSION_ID_idx" ON "DISCHARGE_DRAFTS"("ADMISSION_ID");
CREATE INDEX IF NOT EXISTS "DISCHARGE_DRAFTS_STATUS_idx" ON "DISCHARGE_DRAFTS"("STATUS");
CREATE INDEX IF NOT EXISTS "DISCHARGE_DRAFTS_REQUESTED_BY_USER_ID_idx" ON "DISCHARGE_DRAFTS"("REQUESTED_BY_USER_ID");
CREATE INDEX IF NOT EXISTS "DISCHARGE_DRAFTS_CREATED_DATE_idx" ON "DISCHARGE_DRAFTS"("CREATED_DATE");

DO $$ BEGIN
  ALTER TABLE "DISCHARGE_DRAFTS" ADD CONSTRAINT "DISCHARGE_DRAFTS_PERSON_ID_fkey"
    FOREIGN KEY ("PERSON_ID") REFERENCES "PERSONS"("PERSON_ID") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "DISCHARGE_DRAFTS" ADD CONSTRAINT "DISCHARGE_DRAFTS_ADMISSION_ID_fkey"
    FOREIGN KEY ("ADMISSION_ID") REFERENCES "ADMISSIONS"("ADMISSION_ID") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "DISCHARGE_DRAFTS" ADD CONSTRAINT "DISCHARGE_DRAFTS_REQUESTED_BY_USER_ID_fkey"
    FOREIGN KEY ("REQUESTED_BY_USER_ID") REFERENCES "USERS"("USER_ID") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "DISCHARGE_DRAFT_EVENTS" (
    "EVENT_ID" SERIAL NOT NULL,
    "DRAFT_ID" INTEGER NOT NULL,
    "EVENT_TYPE" VARCHAR(50) NOT NULL,
    "ACTOR_USER_ID" INTEGER,
    "ACTOR_LABEL" VARCHAR(150),
    "NOTE" TEXT,
    "OLD_STATUS" VARCHAR(40),
    "NEW_STATUS" VARCHAR(40),
    "CREATED_DATE" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "DISCHARGE_DRAFT_EVENTS_pkey" PRIMARY KEY ("EVENT_ID")
);

CREATE INDEX IF NOT EXISTS "DISCHARGE_DRAFT_EVENTS_DRAFT_ID_idx" ON "DISCHARGE_DRAFT_EVENTS"("DRAFT_ID");
CREATE INDEX IF NOT EXISTS "DISCHARGE_DRAFT_EVENTS_CREATED_DATE_idx" ON "DISCHARGE_DRAFT_EVENTS"("CREATED_DATE");

DO $$ BEGIN
  ALTER TABLE "DISCHARGE_DRAFT_EVENTS" ADD CONSTRAINT "DISCHARGE_DRAFT_EVENTS_DRAFT_ID_fkey"
    FOREIGN KEY ("DRAFT_ID") REFERENCES "DISCHARGE_DRAFTS"("DRAFT_ID") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
