-- Master Service Catalog + link domain catalogs.
-- Extends legacy DEPARTMENTS; creates SERVICE_* / MASTER_SERVICES tables.
-- Backfills MasterServices from LAB_TESTS, IMAGING_STUDIES, ADMISSION_BILLING_ITEMS.

-- DEPARTMENTS may be missing on DBs that never applied the legacy init table.
CREATE TABLE IF NOT EXISTS "DEPARTMENTS" (
    "DEPARTMENT_ID" SERIAL NOT NULL,
    "NAME" VARCHAR(255),
    "CODE" VARCHAR(40),
    "STATUS" VARCHAR(30) NOT NULL DEFAULT 'Active',
    "CREATED_BY" VARCHAR(100),
    "CREATED_DATE" TIMESTAMP(3),
    "UPDATED_BY" VARCHAR(100),
    "UPDATED_DATE" TIMESTAMP(3),
    CONSTRAINT "DEPARTMENTS_pkey" PRIMARY KEY ("DEPARTMENT_ID")
);

-- Extend legacy DEPARTMENTS (init only had DEPARTMENT_ID + NAME)
ALTER TABLE "DEPARTMENTS" ADD COLUMN IF NOT EXISTS "CODE" VARCHAR(40);
ALTER TABLE "DEPARTMENTS" ADD COLUMN IF NOT EXISTS "STATUS" VARCHAR(30) NOT NULL DEFAULT 'Active';
ALTER TABLE "DEPARTMENTS" ADD COLUMN IF NOT EXISTS "CREATED_BY" VARCHAR(100);
ALTER TABLE "DEPARTMENTS" ADD COLUMN IF NOT EXISTS "CREATED_DATE" TIMESTAMP(3);
ALTER TABLE "DEPARTMENTS" ADD COLUMN IF NOT EXISTS "UPDATED_BY" VARCHAR(100);
ALTER TABLE "DEPARTMENTS" ADD COLUMN IF NOT EXISTS "UPDATED_DATE" TIMESTAMP(3);

CREATE UNIQUE INDEX IF NOT EXISTS "DEPARTMENTS_CODE_key" ON "DEPARTMENTS"("CODE");
CREATE INDEX IF NOT EXISTS "DEPARTMENTS_STATUS_idx" ON "DEPARTMENTS"("STATUS");
CREATE INDEX IF NOT EXISTS "DEPARTMENTS_NAME_idx" ON "DEPARTMENTS"("NAME");

CREATE TABLE IF NOT EXISTS "SERVICE_CATEGORIES" (
    "CATEGORY_ID" SERIAL NOT NULL,
    "CODE" VARCHAR(40) NOT NULL,
    "NAME" VARCHAR(150) NOT NULL,
    "STATUS" VARCHAR(30) NOT NULL DEFAULT 'Active',
    "CREATED_BY" VARCHAR(100),
    "CREATED_DATE" TIMESTAMP(3),
    "UPDATED_BY" VARCHAR(100),
    "UPDATED_DATE" TIMESTAMP(3),
    CONSTRAINT "SERVICE_CATEGORIES_pkey" PRIMARY KEY ("CATEGORY_ID")
);

CREATE UNIQUE INDEX IF NOT EXISTS "SERVICE_CATEGORIES_CODE_key" ON "SERVICE_CATEGORIES"("CODE");
CREATE INDEX IF NOT EXISTS "SERVICE_CATEGORIES_STATUS_idx" ON "SERVICE_CATEGORIES"("STATUS");

CREATE TABLE IF NOT EXISTS "MASTER_SERVICES" (
    "SERVICE_ID" SERIAL NOT NULL,
    "SERVICE_CODE" VARCHAR(50) NOT NULL,
    "CATEGORY_ID" INTEGER NOT NULL,
    "DEPARTMENT_ID" INTEGER NOT NULL,
    "NAME" VARCHAR(255) NOT NULL,
    "DESCRIPTION" TEXT,
    "DURATION_MINUTES" INTEGER,
    "GENERAL_PRICE" DECIMAL(14,2),
    "STAFF_PRICE" DECIMAL(14,2),
    "ONLINE_BOOKABLE" BOOLEAN NOT NULL DEFAULT false,
    "APPOINTMENT_REQUIRED" BOOLEAN NOT NULL DEFAULT false,
    "REQUIRES_DOCTOR_ORDER" BOOLEAN NOT NULL DEFAULT true,
    "INSURANCE_ELIGIBLE" BOOLEAN NOT NULL DEFAULT true,
    "AGE_RESTRICTION" VARCHAR(100),
    "GENDER_RESTRICTION" VARCHAR(30),
    "STATUS" VARCHAR(40) NOT NULL DEFAULT 'PENDING_PRICING',
    "CREATED_BY_ID" INTEGER,
    "CREATED_BY" VARCHAR(100),
    "CREATED_DATE" TIMESTAMP(3),
    "UPDATED_BY_ID" INTEGER,
    "UPDATED_BY" VARCHAR(100),
    "UPDATED_DATE" TIMESTAMP(3),
    CONSTRAINT "MASTER_SERVICES_pkey" PRIMARY KEY ("SERVICE_ID")
);

CREATE UNIQUE INDEX IF NOT EXISTS "MASTER_SERVICES_SERVICE_CODE_key" ON "MASTER_SERVICES"("SERVICE_CODE");
CREATE INDEX IF NOT EXISTS "MASTER_SERVICES_CATEGORY_ID_idx" ON "MASTER_SERVICES"("CATEGORY_ID");
CREATE INDEX IF NOT EXISTS "MASTER_SERVICES_DEPARTMENT_ID_idx" ON "MASTER_SERVICES"("DEPARTMENT_ID");
CREATE INDEX IF NOT EXISTS "MASTER_SERVICES_STATUS_idx" ON "MASTER_SERVICES"("STATUS");
CREATE INDEX IF NOT EXISTS "MASTER_SERVICES_NAME_idx" ON "MASTER_SERVICES"("NAME");

CREATE TABLE IF NOT EXISTS "SERVICE_PAYERS" (
    "PAYER_ID" SERIAL NOT NULL,
    "PAYER_TYPE" VARCHAR(30) NOT NULL,
    "CODE" VARCHAR(40) NOT NULL,
    "NAME" VARCHAR(255) NOT NULL,
    "STATUS" VARCHAR(30) NOT NULL DEFAULT 'Active',
    "CREATED_BY" VARCHAR(100),
    "CREATED_DATE" TIMESTAMP(3),
    "UPDATED_BY" VARCHAR(100),
    "UPDATED_DATE" TIMESTAMP(3),
    CONSTRAINT "SERVICE_PAYERS_pkey" PRIMARY KEY ("PAYER_ID")
);

CREATE UNIQUE INDEX IF NOT EXISTS "SERVICE_PAYERS_CODE_key" ON "SERVICE_PAYERS"("CODE");
CREATE INDEX IF NOT EXISTS "SERVICE_PAYERS_PAYER_TYPE_idx" ON "SERVICE_PAYERS"("PAYER_TYPE");
CREATE INDEX IF NOT EXISTS "SERVICE_PAYERS_STATUS_idx" ON "SERVICE_PAYERS"("STATUS");

CREATE TABLE IF NOT EXISTS "SERVICE_PAYER_PRICES" (
    "PAYER_PRICE_ID" SERIAL NOT NULL,
    "SERVICE_ID" INTEGER NOT NULL,
    "PAYER_ID" INTEGER NOT NULL,
    "AMOUNT" DECIMAL(14,2) NOT NULL,
    "EFFECTIVE_FROM" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "EFFECTIVE_TO" TIMESTAMP(3),
    "STATUS" VARCHAR(30) NOT NULL DEFAULT 'Active',
    "CREATED_BY_ID" INTEGER,
    "CREATED_BY" VARCHAR(100),
    "CREATED_DATE" TIMESTAMP(3),
    "UPDATED_BY_ID" INTEGER,
    "UPDATED_BY" VARCHAR(100),
    "UPDATED_DATE" TIMESTAMP(3),
    CONSTRAINT "SERVICE_PAYER_PRICES_pkey" PRIMARY KEY ("PAYER_PRICE_ID")
);

CREATE INDEX IF NOT EXISTS "SERVICE_PAYER_PRICES_SERVICE_ID_idx" ON "SERVICE_PAYER_PRICES"("SERVICE_ID");
CREATE INDEX IF NOT EXISTS "SERVICE_PAYER_PRICES_PAYER_ID_idx" ON "SERVICE_PAYER_PRICES"("PAYER_ID");
CREATE INDEX IF NOT EXISTS "SERVICE_PAYER_PRICES_STATUS_idx" ON "SERVICE_PAYER_PRICES"("STATUS");
CREATE INDEX IF NOT EXISTS "SERVICE_PAYER_PRICES_SERVICE_ID_PAYER_ID_STATUS_idx" ON "SERVICE_PAYER_PRICES"("SERVICE_ID", "PAYER_ID", "STATUS");

CREATE TABLE IF NOT EXISTS "SERVICE_PRICE_APPROVALS" (
    "APPROVAL_ID" SERIAL NOT NULL,
    "SERVICE_ID" INTEGER NOT NULL,
    "ACTION" VARCHAR(40) NOT NULL,
    "ACTOR_USER_ID" INTEGER,
    "ACTOR_LABEL" VARCHAR(100),
    "NOTES" TEXT,
    "PRICE_SNAPSHOT" JSONB,
    "CREATED_DATE" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "SERVICE_PRICE_APPROVALS_pkey" PRIMARY KEY ("APPROVAL_ID")
);

CREATE INDEX IF NOT EXISTS "SERVICE_PRICE_APPROVALS_SERVICE_ID_idx" ON "SERVICE_PRICE_APPROVALS"("SERVICE_ID");
CREATE INDEX IF NOT EXISTS "SERVICE_PRICE_APPROVALS_ACTION_idx" ON "SERVICE_PRICE_APPROVALS"("ACTION");
CREATE INDEX IF NOT EXISTS "SERVICE_PRICE_APPROVALS_CREATED_DATE_idx" ON "SERVICE_PRICE_APPROVALS"("CREATED_DATE");

-- FKs (idempotent via DO blocks)
DO $$ BEGIN
  ALTER TABLE "MASTER_SERVICES" ADD CONSTRAINT "MASTER_SERVICES_CATEGORY_ID_fkey"
    FOREIGN KEY ("CATEGORY_ID") REFERENCES "SERVICE_CATEGORIES"("CATEGORY_ID") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "MASTER_SERVICES" ADD CONSTRAINT "MASTER_SERVICES_DEPARTMENT_ID_fkey"
    FOREIGN KEY ("DEPARTMENT_ID") REFERENCES "DEPARTMENTS"("DEPARTMENT_ID") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "SERVICE_PAYER_PRICES" ADD CONSTRAINT "SERVICE_PAYER_PRICES_SERVICE_ID_fkey"
    FOREIGN KEY ("SERVICE_ID") REFERENCES "MASTER_SERVICES"("SERVICE_ID") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "SERVICE_PAYER_PRICES" ADD CONSTRAINT "SERVICE_PAYER_PRICES_PAYER_ID_fkey"
    FOREIGN KEY ("PAYER_ID") REFERENCES "SERVICE_PAYERS"("PAYER_ID") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "SERVICE_PRICE_APPROVALS" ADD CONSTRAINT "SERVICE_PRICE_APPROVALS_SERVICE_ID_fkey"
    FOREIGN KEY ("SERVICE_ID") REFERENCES "MASTER_SERVICES"("SERVICE_ID") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

ALTER TABLE "LAB_TESTS" ADD COLUMN IF NOT EXISTS "SERVICE_ID" INTEGER;
ALTER TABLE "IMAGING_STUDIES" ADD COLUMN IF NOT EXISTS "SERVICE_ID" INTEGER;
ALTER TABLE "ADMISSION_BILLING_ITEMS" ADD COLUMN IF NOT EXISTS "SERVICE_ID" INTEGER;

CREATE INDEX IF NOT EXISTS "LAB_TESTS_SERVICE_ID_idx" ON "LAB_TESTS"("SERVICE_ID");
CREATE INDEX IF NOT EXISTS "IMAGING_STUDIES_SERVICE_ID_idx" ON "IMAGING_STUDIES"("SERVICE_ID");
CREATE INDEX IF NOT EXISTS "ADMISSION_BILLING_ITEMS_SERVICE_ID_idx" ON "ADMISSION_BILLING_ITEMS"("SERVICE_ID");

DO $$ BEGIN
  ALTER TABLE "LAB_TESTS" ADD CONSTRAINT "LAB_TESTS_SERVICE_ID_fkey"
    FOREIGN KEY ("SERVICE_ID") REFERENCES "MASTER_SERVICES"("SERVICE_ID") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "IMAGING_STUDIES" ADD CONSTRAINT "IMAGING_STUDIES_SERVICE_ID_fkey"
    FOREIGN KEY ("SERVICE_ID") REFERENCES "MASTER_SERVICES"("SERVICE_ID") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "ADMISSION_BILLING_ITEMS" ADD CONSTRAINT "ADMISSION_BILLING_ITEMS_SERVICE_ID_fkey"
    FOREIGN KEY ("SERVICE_ID") REFERENCES "MASTER_SERVICES"("SERVICE_ID") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- Seed categories
INSERT INTO "SERVICE_CATEGORIES" ("CODE", "NAME", "STATUS", "CREATED_BY", "CREATED_DATE")
VALUES
  ('CONSULTATION', 'Consultation', 'Active', 'migration', NOW()),
  ('LABORATORY', 'Laboratory', 'Active', 'migration', NOW()),
  ('RADIOLOGY', 'Radiology', 'Active', 'migration', NOW()),
  ('PHARMACY', 'Pharmacy', 'Active', 'migration', NOW()),
  ('PHYSIOTHERAPY', 'Physiotherapy', 'Active', 'migration', NOW()),
  ('DENTAL', 'Dental', 'Active', 'migration', NOW()),
  ('EYE_CLINIC', 'Eye Clinic', 'Active', 'migration', NOW()),
  ('PSYCHOLOGY', 'Psychology', 'Active', 'migration', NOW()),
  ('OCCUPATIONAL_THERAPY', 'Occupational Therapy', 'Active', 'migration', NOW()),
  ('SPEECH_THERAPY', 'Speech Therapy', 'Active', 'migration', NOW()),
  ('PSYCHIATRY', 'Psychiatry', 'Active', 'migration', NOW()),
  ('EMERGENCY', 'Emergency', 'Active', 'migration', NOW()),
  ('ADMISSION', 'Admission', 'Active', 'migration', NOW()),
  ('WARD_CHARGES', 'Ward Charges', 'Active', 'migration', NOW()),
  ('THEATRE', 'Theatre', 'Active', 'migration', NOW()),
  ('VACCINATION', 'Vaccination', 'Active', 'migration', NOW()),
  ('PROCEDURE', 'Procedure', 'Active', 'migration', NOW()),
  ('MEDICAL_CERTIFICATE', 'Medical Certificate', 'Active', 'migration', NOW()),
  ('CARD_FEE', 'Card Fee', 'Active', 'migration', NOW()),
  ('REGISTRATION_FEE', 'Registration Fee', 'Active', 'migration', NOW()),
  ('HOME_CARE', 'Home Care', 'Active', 'migration', NOW()),
  ('TELEMEDICINE', 'Telemedicine', 'Active', 'migration', NOW())
ON CONFLICT ("CODE") DO NOTHING;

-- Seed core departments (upsert by CODE when null name-only rows may exist)
INSERT INTO "DEPARTMENTS" ("NAME", "CODE", "STATUS", "CREATED_BY", "CREATED_DATE")
SELECT v.name, v.code, 'Active', 'migration', NOW()
FROM (VALUES
  ('Laboratory', 'LAB'),
  ('Radiology', 'RAD'),
  ('Admissions', 'ADM'),
  ('GMPC', 'GMPC'),
  ('OPC Psychiatry', 'OPC'),
  ('Child Psychiatry', 'CAP'),
  ('Psychology', 'PSY'),
  ('Addiction Services', 'ADD'),
  ('Pharmacy', 'PHARM'),
  ('Emergency', 'ER'),
  ('Telepsychiatry', 'TELE')
) AS v(name, code)
WHERE NOT EXISTS (SELECT 1 FROM "DEPARTMENTS" d WHERE d."CODE" = v.code);

-- Default NHIA payer
INSERT INTO "SERVICE_PAYERS" ("PAYER_TYPE", "CODE", "NAME", "STATUS", "CREATED_BY", "CREATED_DATE")
VALUES ('NHIA', 'NHIA-DEFAULT', 'NHIA / NHIS (Default)', 'Active', 'migration', NOW())
ON CONFLICT ("CODE") DO NOTHING;

-- Backfill MasterServices from LAB_TESTS
INSERT INTO "MASTER_SERVICES" (
  "SERVICE_CODE", "CATEGORY_ID", "DEPARTMENT_ID", "NAME", "DESCRIPTION",
  "GENERAL_PRICE", "STAFF_PRICE", "REQUIRES_DOCTOR_ORDER", "STATUS",
  "CREATED_BY", "CREATED_DATE"
)
SELECT
  'SVC-LAB-' || LPAD(lt."LAB_TEST_ID"::text, 4, '0'),
  (SELECT "CATEGORY_ID" FROM "SERVICE_CATEGORIES" WHERE "CODE" = 'LABORATORY' LIMIT 1),
  (SELECT "DEPARTMENT_ID" FROM "DEPARTMENTS" WHERE "CODE" = 'LAB' LIMIT 1),
  lt."NAME",
  'Migrated from LAB_TESTS ' || lt."TEST_CODE",
  lt."UNIT_PRICE",
  ROUND(lt."UNIT_PRICE" * 0.7, 2),
  true,
  'ACTIVE',
  'migration',
  NOW()
FROM "LAB_TESTS" lt
WHERE lt."SERVICE_ID" IS NULL
  AND NOT EXISTS (
    SELECT 1 FROM "MASTER_SERVICES" ms
    WHERE ms."SERVICE_CODE" = 'SVC-LAB-' || LPAD(lt."LAB_TEST_ID"::text, 4, '0')
  );

UPDATE "LAB_TESTS" lt
SET "SERVICE_ID" = ms."SERVICE_ID"
FROM "MASTER_SERVICES" ms
WHERE ms."SERVICE_CODE" = 'SVC-LAB-' || LPAD(lt."LAB_TEST_ID"::text, 4, '0')
  AND lt."SERVICE_ID" IS NULL;

-- Backfill from IMAGING_STUDIES
INSERT INTO "MASTER_SERVICES" (
  "SERVICE_CODE", "CATEGORY_ID", "DEPARTMENT_ID", "NAME", "DESCRIPTION",
  "GENERAL_PRICE", "STAFF_PRICE", "REQUIRES_DOCTOR_ORDER", "STATUS",
  "CREATED_BY", "CREATED_DATE"
)
SELECT
  'SVC-RAD-' || LPAD(im."IMAGING_STUDY_ID"::text, 4, '0'),
  (SELECT "CATEGORY_ID" FROM "SERVICE_CATEGORIES" WHERE "CODE" = 'RADIOLOGY' LIMIT 1),
  (SELECT "DEPARTMENT_ID" FROM "DEPARTMENTS" WHERE "CODE" = 'RAD' LIMIT 1),
  im."NAME",
  'Migrated from IMAGING_STUDIES ' || im."STUDY_CODE",
  im."UNIT_PRICE",
  ROUND(im."UNIT_PRICE" * 0.7, 2),
  true,
  'ACTIVE',
  'migration',
  NOW()
FROM "IMAGING_STUDIES" im
WHERE im."SERVICE_ID" IS NULL
  AND NOT EXISTS (
    SELECT 1 FROM "MASTER_SERVICES" ms
    WHERE ms."SERVICE_CODE" = 'SVC-RAD-' || LPAD(im."IMAGING_STUDY_ID"::text, 4, '0')
  );

UPDATE "IMAGING_STUDIES" im
SET "SERVICE_ID" = ms."SERVICE_ID"
FROM "MASTER_SERVICES" ms
WHERE ms."SERVICE_CODE" = 'SVC-RAD-' || LPAD(im."IMAGING_STUDY_ID"::text, 4, '0')
  AND im."SERVICE_ID" IS NULL;

-- Backfill from ADMISSION_BILLING_ITEMS
INSERT INTO "MASTER_SERVICES" (
  "SERVICE_CODE", "CATEGORY_ID", "DEPARTMENT_ID", "NAME", "DESCRIPTION",
  "GENERAL_PRICE", "STAFF_PRICE", "REQUIRES_DOCTOR_ORDER", "STATUS",
  "CREATED_BY", "CREATED_DATE"
)
SELECT
  'SVC-ADM-' || LPAD(ab."ITEM_ID"::text, 4, '0'),
  (SELECT "CATEGORY_ID" FROM "SERVICE_CATEGORIES" WHERE "CODE" = 'ADMISSION' LIMIT 1),
  (SELECT "DEPARTMENT_ID" FROM "DEPARTMENTS" WHERE "CODE" = 'ADM' LIMIT 1),
  ab."NAME",
  'Migrated from ADMISSION_BILLING_ITEMS ' || ab."ITEM_CODE",
  ab."UNIT_PRICE",
  ROUND(ab."UNIT_PRICE" * 0.7, 2),
  false,
  'ACTIVE',
  'migration',
  NOW()
FROM "ADMISSION_BILLING_ITEMS" ab
WHERE ab."SERVICE_ID" IS NULL
  AND NOT EXISTS (
    SELECT 1 FROM "MASTER_SERVICES" ms
    WHERE ms."SERVICE_CODE" = 'SVC-ADM-' || LPAD(ab."ITEM_ID"::text, 4, '0')
  );

UPDATE "ADMISSION_BILLING_ITEMS" ab
SET "SERVICE_ID" = ms."SERVICE_ID"
FROM "MASTER_SERVICES" ms
WHERE ms."SERVICE_CODE" = 'SVC-ADM-' || LPAD(ab."ITEM_ID"::text, 4, '0')
  AND ab."SERVICE_ID" IS NULL;

-- Extra FE-mock style services (consultations / therapy / telemedicine / ward day)
INSERT INTO "MASTER_SERVICES" (
  "SERVICE_CODE", "CATEGORY_ID", "DEPARTMENT_ID", "NAME", "DESCRIPTION",
  "DURATION_MINUTES", "GENERAL_PRICE", "STAFF_PRICE",
  "ONLINE_BOOKABLE", "APPOINTMENT_REQUIRED", "REQUIRES_DOCTOR_ORDER",
  "STATUS", "CREATED_BY", "CREATED_DATE"
)
SELECT v.code, c."CATEGORY_ID", d."DEPARTMENT_ID", v.name, v.descr,
       v.duration, v.price, ROUND(v.price * 0.7, 2),
       v.online, v.appt, v.order_req, 'ACTIVE', 'migration', NOW()
FROM (VALUES
  ('SVC-CON-GMPC', 'CONSULTATION', 'GMPC', 'GMPC General Consultation', 'General medical psychiatry clinic consultation', 20, 5000::numeric, true, true, false),
  ('SVC-CON-OPC', 'CONSULTATION', 'OPC', 'OPC Psychiatry Consultation', 'Outpatient psychiatry consultation', 30, 12000::numeric, true, true, false),
  ('SVC-CON-CAP', 'CONSULTATION', 'CAP', 'Child Psychiatry Consultation', 'Child & adolescent psychiatry consultation', 45, 15000::numeric, true, true, false),
  ('SVC-PSY-CBT', 'PSYCHOLOGY', 'PSY', 'CBT Session (45m)', 'Cognitive behavioural therapy session', 45, 18000::numeric, true, true, false),
  ('SVC-ADD-GRP', 'PSYCHOLOGY', 'ADD', 'Addiction Group Therapy', 'Group therapy for addiction services', 60, 8000::numeric, true, true, false),
  ('SVC-PRC-ECT', 'PROCEDURE', 'OPC', 'ECT Session', 'Electroconvulsive therapy session', 60, 35000::numeric, false, true, true),
  ('SVC-TEL-PSY', 'TELEMEDICINE', 'TELE', 'Telepsychiatry (30m)', 'Remote psychiatry consultation', 30, 10000::numeric, true, true, false),
  ('SVC-WRD-GEN', 'WARD_CHARGES', 'ADM', 'General Ward (per day)', 'General ward daily charge', NULL, 8000::numeric, false, false, false),
  ('SVC-WRD-PVT', 'WARD_CHARGES', 'ADM', 'Private Ward (per day)', 'Private ward daily charge', NULL, 25000::numeric, false, false, false)
) AS v(code, cat, dept, name, descr, duration, price, online, appt, order_req)
JOIN "SERVICE_CATEGORIES" c ON c."CODE" = v.cat
JOIN "DEPARTMENTS" d ON d."CODE" = v.dept
WHERE NOT EXISTS (SELECT 1 FROM "MASTER_SERVICES" ms WHERE ms."SERVICE_CODE" = v.code);
