-- Clinical pharmacy: patient allergies, configurable interaction rules, alert worklist

CREATE TABLE IF NOT EXISTS "PATIENT_ALLERGIES" (
    "ALLERGY_ID" SERIAL PRIMARY KEY,
    "PERSON_ID" INTEGER NOT NULL,
    "SUBSTANCE" VARCHAR(150) NOT NULL,
    "REACTION" VARCHAR(255),
    "SEVERITY" VARCHAR(30) NOT NULL DEFAULT 'Moderate',
    "STATUS" VARCHAR(30) NOT NULL DEFAULT 'Active',
    "CREATED_BY_ID" INTEGER,
    "CREATED_BY" VARCHAR(100),
    "CREATED_DATE" TIMESTAMP(3),
    "UPDATED_BY_ID" INTEGER,
    "UPDATED_BY" VARCHAR(100),
    "UPDATED_DATE" TIMESTAMP(3),
    "DELETED_FLAG" VARCHAR(1) DEFAULT 'N'
);

CREATE INDEX IF NOT EXISTS "PATIENT_ALLERGIES_PERSON_ID_idx" ON "PATIENT_ALLERGIES"("PERSON_ID");
CREATE INDEX IF NOT EXISTS "PATIENT_ALLERGIES_STATUS_idx" ON "PATIENT_ALLERGIES"("STATUS");
CREATE INDEX IF NOT EXISTS "PATIENT_ALLERGIES_SUBSTANCE_idx" ON "PATIENT_ALLERGIES"("SUBSTANCE");

CREATE TABLE IF NOT EXISTS "DRUG_INTERACTION_RULES" (
    "RULE_ID" SERIAL PRIMARY KEY,
    "CODE" VARCHAR(80) NOT NULL,
    "DRUG_A_ID" INTEGER,
    "DRUG_B_ID" INTEGER,
    "DRUG_A_NAME" VARCHAR(255),
    "DRUG_B_NAME" VARCHAR(255),
    "ALERT_TYPE" VARCHAR(40) NOT NULL,
    "SEVERITY" VARCHAR(30) NOT NULL DEFAULT 'Moderate',
    "MESSAGE" TEXT NOT NULL,
    "STATUS" VARCHAR(30) NOT NULL DEFAULT 'Active',
    "CREATED_BY_ID" INTEGER,
    "CREATED_BY" VARCHAR(100),
    "CREATED_DATE" TIMESTAMP(3),
    "UPDATED_BY_ID" INTEGER,
    "UPDATED_BY" VARCHAR(100),
    "UPDATED_DATE" TIMESTAMP(3),
    "DELETED_FLAG" VARCHAR(1) DEFAULT 'N'
);

CREATE UNIQUE INDEX IF NOT EXISTS "DRUG_INTERACTION_RULES_CODE_key" ON "DRUG_INTERACTION_RULES"("CODE");
CREATE INDEX IF NOT EXISTS "DRUG_INTERACTION_RULES_ALERT_TYPE_idx" ON "DRUG_INTERACTION_RULES"("ALERT_TYPE");
CREATE INDEX IF NOT EXISTS "DRUG_INTERACTION_RULES_STATUS_idx" ON "DRUG_INTERACTION_RULES"("STATUS");
CREATE INDEX IF NOT EXISTS "DRUG_INTERACTION_RULES_DRUG_A_ID_idx" ON "DRUG_INTERACTION_RULES"("DRUG_A_ID");
CREATE INDEX IF NOT EXISTS "DRUG_INTERACTION_RULES_DRUG_B_ID_idx" ON "DRUG_INTERACTION_RULES"("DRUG_B_ID");

CREATE TABLE IF NOT EXISTS "CLINICAL_PHARMACY_ALERTS" (
    "ALERT_ID" SERIAL PRIMARY KEY,
    "ALERT_NO" VARCHAR(50) NOT NULL,
    "PERSON_ID" INTEGER NOT NULL,
    "PRESCRIPTION_ID" INTEGER,
    "DOCTOR_USER_ID" INTEGER,
    "ALERT_TYPE" VARCHAR(40) NOT NULL,
    "SEVERITY" VARCHAR(30) NOT NULL,
    "DRUG_A" VARCHAR(255) NOT NULL,
    "DRUG_B" VARCHAR(255),
    "MESSAGE" TEXT NOT NULL,
    "RULE_CODE" VARCHAR(80),
    "STATUS" VARCHAR(30) NOT NULL DEFAULT 'Open',
    "OVERRIDE_REASON" TEXT,
    "OVERRIDDEN_BY" VARCHAR(150),
    "OVERRIDDEN_BY_ID" INTEGER,
    "OVERRIDDEN_AT" TIMESTAMP(3),
    "NOTIFY_NOTE" TEXT,
    "NOTIFIED_AT" TIMESTAMP(3),
    "NOTIFIED_BY" VARCHAR(150),
    "NOTIFIED_BY_ID" INTEGER,
    "CREATED_BY_ID" INTEGER,
    "CREATED_BY" VARCHAR(100),
    "CREATED_DATE" TIMESTAMP(3),
    "UPDATED_BY_ID" INTEGER,
    "UPDATED_BY" VARCHAR(100),
    "UPDATED_DATE" TIMESTAMP(3),
    "DELETED_FLAG" VARCHAR(1) DEFAULT 'N'
);

CREATE UNIQUE INDEX IF NOT EXISTS "CLINICAL_PHARMACY_ALERTS_ALERT_NO_key" ON "CLINICAL_PHARMACY_ALERTS"("ALERT_NO");
CREATE INDEX IF NOT EXISTS "CLINICAL_PHARMACY_ALERTS_PERSON_ID_idx" ON "CLINICAL_PHARMACY_ALERTS"("PERSON_ID");
CREATE INDEX IF NOT EXISTS "CLINICAL_PHARMACY_ALERTS_STATUS_idx" ON "CLINICAL_PHARMACY_ALERTS"("STATUS");
CREATE INDEX IF NOT EXISTS "CLINICAL_PHARMACY_ALERTS_SEVERITY_idx" ON "CLINICAL_PHARMACY_ALERTS"("SEVERITY");
CREATE INDEX IF NOT EXISTS "CLINICAL_PHARMACY_ALERTS_ALERT_TYPE_idx" ON "CLINICAL_PHARMACY_ALERTS"("ALERT_TYPE");
CREATE INDEX IF NOT EXISTS "CLINICAL_PHARMACY_ALERTS_PRESCRIPTION_ID_idx" ON "CLINICAL_PHARMACY_ALERTS"("PRESCRIPTION_ID");
CREATE INDEX IF NOT EXISTS "CLINICAL_PHARMACY_ALERTS_CREATED_DATE_idx" ON "CLINICAL_PHARMACY_ALERTS"("CREATED_DATE");

-- Seed hospital-configurable demo rules (name-based; Active)
INSERT INTO "DRUG_INTERACTION_RULES" ("CODE", "DRUG_A_NAME", "DRUG_B_NAME", "ALERT_TYPE", "SEVERITY", "MESSAGE", "STATUS", "CREATED_BY", "CREATED_DATE", "DELETED_FLAG")
VALUES
  ('DDI-HAL-OLA', 'Haloperidol', 'Olanzapine', 'DDI', 'Severe', 'QT prolongation risk — combined antipsychotic. Avoid.', 'Active', 'SYSTEM', NOW(), 'N'),
  ('DUP-DIA-LOR', 'Diazepam', 'Lorazepam', 'Duplicate', 'Moderate', 'Duplicate benzodiazepine therapy — review.', 'Active', 'SYSTEM', NOW(), 'N'),
  ('DDI-PCM-DIC', 'Paracetamol', 'Diclofenac', 'DDI', 'Mild', 'Monitor for GI/renal effects with NSAID + paracetamol combination.', 'Active', 'SYSTEM', NOW(), 'N'),
  ('ALG-PEN', 'Penicillin', NULL, 'AllergyClass', 'Severe', 'Documented penicillin-class allergy — block or clarify before dispense.', 'Active', 'SYSTEM', NOW(), 'N'),
  ('CTL-MORPH', 'Morphine', NULL, 'Controlled', 'Severe', 'Controlled substance — witness signature / override documentation required.', 'Active', 'SYSTEM', NOW(), 'N'),
  ('PSY-CLOZ', 'Clozapine', NULL, 'Psychiatric', 'Moderate', 'Clozapine new start — baseline WBC mandatory before initiation.', 'Active', 'SYSTEM', NOW(), 'N')
ON CONFLICT ("CODE") DO NOTHING;
