-- Service booking settings (1:1 with MASTER_SERVICES) + public SERVICE_BOOKINGS.

CREATE TABLE IF NOT EXISTS "SERVICE_BOOKING_SETTINGS" (
    "SETTING_ID" SERIAL NOT NULL,
    "SERVICE_ID" INTEGER NOT NULL,
    "ONLINE_BOOKABLE" BOOLEAN NOT NULL DEFAULT false,
    "DELIVERY_MODE" VARCHAR(20) NOT NULL DEFAULT 'PHYSICAL',
    "DURATION_MINUTES" INTEGER NOT NULL DEFAULT 30,
    "DAY_START" VARCHAR(5) NOT NULL DEFAULT '08:00',
    "DAY_END" VARCHAR(5) NOT NULL DEFAULT '17:00',
    "CREATED_BY" VARCHAR(100),
    "CREATED_DATE" TIMESTAMP(3),
    "UPDATED_BY" VARCHAR(100),
    "UPDATED_DATE" TIMESTAMP(3),
    CONSTRAINT "SERVICE_BOOKING_SETTINGS_pkey" PRIMARY KEY ("SETTING_ID")
);

CREATE UNIQUE INDEX IF NOT EXISTS "SERVICE_BOOKING_SETTINGS_SERVICE_ID_key"
  ON "SERVICE_BOOKING_SETTINGS"("SERVICE_ID");
CREATE INDEX IF NOT EXISTS "SERVICE_BOOKING_SETTINGS_ONLINE_BOOKABLE_idx"
  ON "SERVICE_BOOKING_SETTINGS"("ONLINE_BOOKABLE");
CREATE INDEX IF NOT EXISTS "SERVICE_BOOKING_SETTINGS_DELIVERY_MODE_idx"
  ON "SERVICE_BOOKING_SETTINGS"("DELIVERY_MODE");

DO $$ BEGIN
  ALTER TABLE "SERVICE_BOOKING_SETTINGS"
    ADD CONSTRAINT "SERVICE_BOOKING_SETTINGS_SERVICE_ID_fkey"
    FOREIGN KEY ("SERVICE_ID") REFERENCES "MASTER_SERVICES"("SERVICE_ID")
    ON DELETE CASCADE ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "SERVICE_BOOKINGS" (
    "BOOKING_ID" SERIAL NOT NULL,
    "BOOKING_NO" VARCHAR(50) NOT NULL,
    "SERVICE_ID" INTEGER NOT NULL,
    "PATIENT_NAME" VARCHAR(255) NOT NULL,
    "PHONE" VARCHAR(40) NOT NULL,
    "EMAIL" VARCHAR(255),
    "AGE" VARCHAR(20),
    "GENDER" VARCHAR(30),
    "APPOINTMENT_DATE" DATE NOT NULL,
    "START_TIME" VARCHAR(5) NOT NULL,
    "END_TIME" VARCHAR(5) NOT NULL,
    "DELIVERY_MODE" VARCHAR(20) NOT NULL,
    "PRICE_AMOUNT" DECIMAL(14,2) NOT NULL,
    "NOTES" TEXT,
    "STATUS" VARCHAR(30) NOT NULL DEFAULT 'Booked',
    "CREATED_BY" VARCHAR(100),
    "CREATED_DATE" TIMESTAMP(3),
    "UPDATED_BY" VARCHAR(100),
    "UPDATED_DATE" TIMESTAMP(3),
    CONSTRAINT "SERVICE_BOOKINGS_pkey" PRIMARY KEY ("BOOKING_ID")
);

CREATE UNIQUE INDEX IF NOT EXISTS "SERVICE_BOOKINGS_BOOKING_NO_key"
  ON "SERVICE_BOOKINGS"("BOOKING_NO");
CREATE INDEX IF NOT EXISTS "SERVICE_BOOKINGS_SERVICE_ID_APPOINTMENT_DATE_idx"
  ON "SERVICE_BOOKINGS"("SERVICE_ID", "APPOINTMENT_DATE");
CREATE INDEX IF NOT EXISTS "SERVICE_BOOKINGS_STATUS_idx"
  ON "SERVICE_BOOKINGS"("STATUS");
CREATE INDEX IF NOT EXISTS "SERVICE_BOOKINGS_APPOINTMENT_DATE_idx"
  ON "SERVICE_BOOKINGS"("APPOINTMENT_DATE");

DO $$ BEGIN
  ALTER TABLE "SERVICE_BOOKINGS"
    ADD CONSTRAINT "SERVICE_BOOKINGS_SERVICE_ID_fkey"
    FOREIGN KEY ("SERVICE_ID") REFERENCES "MASTER_SERVICES"("SERVICE_ID")
    ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- Backfill settings from existing master services
INSERT INTO "SERVICE_BOOKING_SETTINGS" (
  "SERVICE_ID", "ONLINE_BOOKABLE", "DELIVERY_MODE", "DURATION_MINUTES",
  "DAY_START", "DAY_END", "CREATED_BY", "CREATED_DATE"
)
SELECT
  ms."SERVICE_ID",
  COALESCE(ms."ONLINE_BOOKABLE", false),
  CASE WHEN COALESCE(ms."ONLINE_BOOKABLE", false) THEN 'BOTH' ELSE 'PHYSICAL' END,
  COALESCE(ms."DURATION_MINUTES", 30),
  '08:00',
  '17:00',
  'migration',
  NOW()
FROM "MASTER_SERVICES" ms
WHERE NOT EXISTS (
  SELECT 1 FROM "SERVICE_BOOKING_SETTINGS" s WHERE s."SERVICE_ID" = ms."SERVICE_ID"
);

-- Keep MasterServices mirrors aligned with settings
UPDATE "MASTER_SERVICES" ms
SET
  "ONLINE_BOOKABLE" = s."ONLINE_BOOKABLE",
  "DURATION_MINUTES" = s."DURATION_MINUTES"
FROM "SERVICE_BOOKING_SETTINGS" s
WHERE s."SERVICE_ID" = ms."SERVICE_ID";
