-- Records file retrieval, archive catalog, report snapshots

CREATE TABLE IF NOT EXISTS "RECORD_FILE_REQUESTS" (
    "REQUEST_ID" SERIAL PRIMARY KEY,
    "REQUEST_NO" VARCHAR(50) NOT NULL,
    "PERSON_ID" INTEGER NOT NULL,
    "REQUESTED_BY" VARCHAR(150) NOT NULL,
    "REQUESTED_BY_USER_ID" INTEGER,
    "DEPARTMENT" VARCHAR(100) NOT NULL,
    "REASON" TEXT NOT NULL,
    "LOCATION" VARCHAR(150) NOT NULL DEFAULT 'Records',
    "DUE_DATE" TIMESTAMP(3),
    "STATUS" VARCHAR(30) NOT NULL DEFAULT 'Requested',
    "CREATED_BY_ID" INTEGER,
    "CREATED_BY" VARCHAR(100),
    "CREATED_DATE" TIMESTAMP(3),
    "UPDATED_BY_ID" INTEGER,
    "UPDATED_BY" VARCHAR(100),
    "UPDATED_DATE" TIMESTAMP(3),
    "DELETED_FLAG" VARCHAR(1) DEFAULT 'N'
);

CREATE UNIQUE INDEX IF NOT EXISTS "RECORD_FILE_REQUESTS_REQUEST_NO_key" ON "RECORD_FILE_REQUESTS"("REQUEST_NO");
CREATE INDEX IF NOT EXISTS "RECORD_FILE_REQUESTS_PERSON_ID_idx" ON "RECORD_FILE_REQUESTS"("PERSON_ID");
CREATE INDEX IF NOT EXISTS "RECORD_FILE_REQUESTS_STATUS_idx" ON "RECORD_FILE_REQUESTS"("STATUS");
CREATE INDEX IF NOT EXISTS "RECORD_FILE_REQUESTS_DUE_DATE_idx" ON "RECORD_FILE_REQUESTS"("DUE_DATE");
CREATE INDEX IF NOT EXISTS "RECORD_FILE_REQUESTS_CREATED_DATE_idx" ON "RECORD_FILE_REQUESTS"("CREATED_DATE");

CREATE TABLE IF NOT EXISTS "RECORD_FILE_REQUEST_EVENTS" (
    "EVENT_ID" SERIAL PRIMARY KEY,
    "REQUEST_ID" INTEGER NOT NULL,
    "EVENT_TYPE" VARCHAR(50) NOT NULL,
    "OLD_STATUS" VARCHAR(30),
    "NEW_STATUS" VARCHAR(30),
    "NOTE" TEXT,
    "LOCATION" VARCHAR(150),
    "ACTOR_USER_ID" INTEGER,
    "ACTOR_LABEL" VARCHAR(150),
    "CREATED_DATE" TIMESTAMP(3),
    CONSTRAINT "RECORD_FILE_REQUEST_EVENTS_REQUEST_ID_fkey"
      FOREIGN KEY ("REQUEST_ID") REFERENCES "RECORD_FILE_REQUESTS"("REQUEST_ID") ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS "RECORD_FILE_REQUEST_EVENTS_REQUEST_ID_idx" ON "RECORD_FILE_REQUEST_EVENTS"("REQUEST_ID");
CREATE INDEX IF NOT EXISTS "RECORD_FILE_REQUEST_EVENTS_CREATED_DATE_idx" ON "RECORD_FILE_REQUEST_EVENTS"("CREATED_DATE");

CREATE TABLE IF NOT EXISTS "RECORD_ARCHIVES" (
    "ARCHIVE_ID" SERIAL PRIMARY KEY,
    "ARCHIVE_NO" VARCHAR(50) NOT NULL,
    "PERSON_ID" INTEGER NOT NULL,
    "CATEGORY" VARCHAR(40) NOT NULL,
    "ACCESS_LEVEL" VARCHAR(40) NOT NULL DEFAULT 'Standard',
    "LAST_VISIT_AT" TIMESTAMP(3),
    "ARCHIVED_AT" TIMESTAMP(3) NOT NULL,
    "RETENTION_UNTIL" TIMESTAMP(3),
    "DUE_REVIEW_AT" TIMESTAMP(3),
    "STATUS" VARCHAR(30) NOT NULL DEFAULT 'Archived',
    "NOTES" TEXT,
    "CREATED_BY_ID" INTEGER,
    "CREATED_BY" VARCHAR(100),
    "CREATED_DATE" TIMESTAMP(3),
    "UPDATED_BY_ID" INTEGER,
    "UPDATED_BY" VARCHAR(100),
    "UPDATED_DATE" TIMESTAMP(3),
    "DELETED_FLAG" VARCHAR(1) DEFAULT 'N'
);

CREATE UNIQUE INDEX IF NOT EXISTS "RECORD_ARCHIVES_ARCHIVE_NO_key" ON "RECORD_ARCHIVES"("ARCHIVE_NO");
CREATE UNIQUE INDEX IF NOT EXISTS "RECORD_ARCHIVES_PERSON_ID_key" ON "RECORD_ARCHIVES"("PERSON_ID");
CREATE INDEX IF NOT EXISTS "RECORD_ARCHIVES_CATEGORY_idx" ON "RECORD_ARCHIVES"("CATEGORY");
CREATE INDEX IF NOT EXISTS "RECORD_ARCHIVES_STATUS_idx" ON "RECORD_ARCHIVES"("STATUS");
CREATE INDEX IF NOT EXISTS "RECORD_ARCHIVES_ARCHIVED_AT_idx" ON "RECORD_ARCHIVES"("ARCHIVED_AT");
CREATE INDEX IF NOT EXISTS "RECORD_ARCHIVES_DUE_REVIEW_AT_idx" ON "RECORD_ARCHIVES"("DUE_REVIEW_AT");

CREATE TABLE IF NOT EXISTS "RECORD_REPORT_SNAPSHOTS" (
    "SNAPSHOT_ID" SERIAL PRIMARY KEY,
    "REPORT_TYPE" VARCHAR(120) NOT NULL,
    "FROM_DATE" TIMESTAMP(3) NOT NULL,
    "TO_DATE" TIMESTAMP(3) NOT NULL,
    "DEPARTMENT" VARCHAR(100),
    "METRICS_JSON" JSONB NOT NULL,
    "GENERATED_BY" VARCHAR(150),
    "GENERATED_BY_ID" INTEGER,
    "CREATED_DATE" TIMESTAMP(3),
    "DELETED_FLAG" VARCHAR(1) DEFAULT 'N'
);

CREATE INDEX IF NOT EXISTS "RECORD_REPORT_SNAPSHOTS_REPORT_TYPE_idx" ON "RECORD_REPORT_SNAPSHOTS"("REPORT_TYPE");
CREATE INDEX IF NOT EXISTS "RECORD_REPORT_SNAPSHOTS_FROM_DATE_TO_DATE_idx" ON "RECORD_REPORT_SNAPSHOTS"("FROM_DATE", "TO_DATE");
CREATE INDEX IF NOT EXISTS "RECORD_REPORT_SNAPSHOTS_CREATED_DATE_idx" ON "RECORD_REPORT_SNAPSHOTS"("CREATED_DATE");
