-- Clinical prescriptions: doctor → pharmacy queue

CREATE TABLE IF NOT EXISTS "PRESCRIPTIONS" (
    "PRESCRIPTION_ID" SERIAL NOT NULL,
    "RX_NO" VARCHAR(50) NOT NULL,
    "PERSON_ID" INTEGER NOT NULL,
    "STATUS" VARCHAR(50) NOT NULL DEFAULT 'Draft',
    "URGENCY" VARCHAR(50) NOT NULL DEFAULT 'Routine',
    "PAYMENT_STATUS" VARCHAR(50) NOT NULL DEFAULT 'Unpaid',
    "DIAGNOSIS" VARCHAR(500),
    "ALLERGIES_NOTE" VARCHAR(500),
    "CLINIC" VARCHAR(100),
    "NOTES" TEXT,
    "PHARMACY_NOTES" TEXT,
    "SENT_AT" TIMESTAMP(3),
    "PRESCRIBED_BY_ID" INTEGER,
    "PRESCRIBED_BY" VARCHAR(100),
    "CREATED_BY_ID" INTEGER,
    "CREATED_BY" VARCHAR(100),
    "CREATED_DATE" TIMESTAMP(3),
    "UPDATED_BY_ID" INTEGER,
    "UPDATED_BY" VARCHAR(100),
    "UPDATED_DATE" TIMESTAMP(3),

    CONSTRAINT "PRESCRIPTIONS_pkey" PRIMARY KEY ("PRESCRIPTION_ID")
);

CREATE UNIQUE INDEX IF NOT EXISTS "PRESCRIPTIONS_RX_NO_key" ON "PRESCRIPTIONS"("RX_NO");
CREATE INDEX IF NOT EXISTS "PRESCRIPTIONS_PERSON_ID_idx" ON "PRESCRIPTIONS"("PERSON_ID");
CREATE INDEX IF NOT EXISTS "PRESCRIPTIONS_STATUS_idx" ON "PRESCRIPTIONS"("STATUS");
CREATE INDEX IF NOT EXISTS "PRESCRIPTIONS_PAYMENT_STATUS_idx" ON "PRESCRIPTIONS"("PAYMENT_STATUS");
CREATE INDEX IF NOT EXISTS "PRESCRIPTIONS_SENT_AT_idx" ON "PRESCRIPTIONS"("SENT_AT");
CREATE INDEX IF NOT EXISTS "PRESCRIPTIONS_PRESCRIBED_BY_ID_idx" ON "PRESCRIPTIONS"("PRESCRIBED_BY_ID");

CREATE TABLE IF NOT EXISTS "PRESCRIPTION_ITEMS" (
    "ITEM_ID" SERIAL NOT NULL,
    "PRESCRIPTION_ID" INTEGER NOT NULL,
    "DRUG_ID" INTEGER NOT NULL,
    "DRUG_NAME" VARCHAR(255) NOT NULL,
    "STRENGTH" VARCHAR(100),
    "FORM" VARCHAR(50),
    "ROUTE" VARCHAR(50),
    "DOSE" VARCHAR(100) NOT NULL,
    "FREQUENCY" VARCHAR(50) NOT NULL,
    "DURATION" VARCHAR(100),
    "QUANTITY" INTEGER NOT NULL,
    "QTY_DISPENSED" INTEGER NOT NULL DEFAULT 0,
    "SOURCE" VARCHAR(50) NOT NULL DEFAULT 'Internal Pharmacy',
    "INSTRUCTIONS" TEXT,
    "INDICATION" VARCHAR(500),
    "LINE_STATUS" VARCHAR(50) NOT NULL DEFAULT 'Active',
    "UNIT_PRICE" DECIMAL(14,2) NOT NULL DEFAULT 0,

    CONSTRAINT "PRESCRIPTION_ITEMS_pkey" PRIMARY KEY ("ITEM_ID")
);

CREATE INDEX IF NOT EXISTS "PRESCRIPTION_ITEMS_PRESCRIPTION_ID_idx" ON "PRESCRIPTION_ITEMS"("PRESCRIPTION_ID");
CREATE INDEX IF NOT EXISTS "PRESCRIPTION_ITEMS_DRUG_ID_idx" ON "PRESCRIPTION_ITEMS"("DRUG_ID");

DO $$ BEGIN
  ALTER TABLE "PRESCRIPTIONS" ADD CONSTRAINT "PRESCRIPTIONS_PERSON_ID_fkey"
    FOREIGN KEY ("PERSON_ID") REFERENCES "PERSONS"("PERSON_ID") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "PRESCRIPTION_ITEMS" ADD CONSTRAINT "PRESCRIPTION_ITEMS_PRESCRIPTION_ID_fkey"
    FOREIGN KEY ("PRESCRIPTION_ID") REFERENCES "PRESCRIPTIONS"("PRESCRIPTION_ID") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "PRESCRIPTION_ITEMS" ADD CONSTRAINT "PRESCRIPTION_ITEMS_DRUG_ID_fkey"
    FOREIGN KEY ("DRUG_ID") REFERENCES "DRUGS"("DRUG_ID") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
