-- Lab LIS pipeline: samples, results, immutable result versions + LAB_STATUS on LAB_REQUESTS.

-- 1) LAB_STATUS workflow column
ALTER TABLE "LAB_REQUESTS" ADD COLUMN IF NOT EXISTS "LAB_STATUS" VARCHAR(50) NOT NULL DEFAULT 'AwaitingCollection';
CREATE INDEX IF NOT EXISTS "LAB_REQUESTS_LAB_STATUS_idx" ON "LAB_REQUESTS"("LAB_STATUS");

-- 2) LAB_SAMPLES
CREATE TABLE IF NOT EXISTS "LAB_SAMPLES" (
    "SAMPLE_ID" SERIAL NOT NULL,
    "SAMPLE_NO" VARCHAR(50) NOT NULL,
    "LAB_REQUEST_ID" INTEGER NOT NULL,
    "SPECIMEN_TYPE" VARCHAR(100) NOT NULL,
    "CONTAINER" VARCHAR(100),
    "STATUS" VARCHAR(50) NOT NULL DEFAULT 'Collected',
    "COLLECTED_BY" VARCHAR(100),
    "COLLECTED_AT" TIMESTAMP(3),
    "REJECT_REASON" TEXT,
    "CREATED_BY_ID" INTEGER,
    "CREATED_BY" VARCHAR(100),
    "CREATED_DATE" TIMESTAMP(3),
    "UPDATED_BY_ID" INTEGER,
    "UPDATED_BY" VARCHAR(100),
    "UPDATED_DATE" TIMESTAMP(3),

    CONSTRAINT "LAB_SAMPLES_pkey" PRIMARY KEY ("SAMPLE_ID")
);

CREATE UNIQUE INDEX IF NOT EXISTS "LAB_SAMPLES_SAMPLE_NO_key" ON "LAB_SAMPLES"("SAMPLE_NO");
CREATE INDEX IF NOT EXISTS "LAB_SAMPLES_LAB_REQUEST_ID_STATUS_idx" ON "LAB_SAMPLES"("LAB_REQUEST_ID", "STATUS");
CREATE INDEX IF NOT EXISTS "LAB_SAMPLES_STATUS_idx" ON "LAB_SAMPLES"("STATUS");
CREATE INDEX IF NOT EXISTS "LAB_SAMPLES_CREATED_DATE_idx" ON "LAB_SAMPLES"("CREATED_DATE");

DO $$ BEGIN
  ALTER TABLE "LAB_SAMPLES" ADD CONSTRAINT "LAB_SAMPLES_LAB_REQUEST_ID_fkey"
    FOREIGN KEY ("LAB_REQUEST_ID") REFERENCES "LAB_REQUESTS"("LAB_REQUEST_ID") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- 3) LAB_RESULTS (one per request item)
CREATE TABLE IF NOT EXISTS "LAB_RESULTS" (
    "LAB_RESULT_ID" SERIAL NOT NULL,
    "LAB_REQUEST_ID" INTEGER NOT NULL,
    "LAB_REQUEST_ITEM_ID" INTEGER NOT NULL,
    "TEMPLATE_ID" INTEGER,
    "VALUES" JSONB NOT NULL DEFAULT '{}',
    "COMMENT" TEXT,
    "STATUS" VARCHAR(50) NOT NULL DEFAULT 'Draft',
    "ENTERED_BY" VARCHAR(100),
    "ENTERED_AT" TIMESTAMP(3),
    "VALIDATED_BY" VARCHAR(100),
    "VALIDATED_AT" TIMESTAMP(3),
    "RETURN_REASON" TEXT,
    "VERSION" INTEGER NOT NULL DEFAULT 1,
    "CREATED_BY_ID" INTEGER,
    "CREATED_BY" VARCHAR(100),
    "CREATED_DATE" TIMESTAMP(3),
    "UPDATED_BY_ID" INTEGER,
    "UPDATED_BY" VARCHAR(100),
    "UPDATED_DATE" TIMESTAMP(3),

    CONSTRAINT "LAB_RESULTS_pkey" PRIMARY KEY ("LAB_RESULT_ID")
);

CREATE UNIQUE INDEX IF NOT EXISTS "LAB_RESULTS_LAB_REQUEST_ITEM_ID_key" ON "LAB_RESULTS"("LAB_REQUEST_ITEM_ID");
CREATE INDEX IF NOT EXISTS "LAB_RESULTS_LAB_REQUEST_ID_idx" ON "LAB_RESULTS"("LAB_REQUEST_ID");
CREATE INDEX IF NOT EXISTS "LAB_RESULTS_STATUS_idx" ON "LAB_RESULTS"("STATUS");
CREATE INDEX IF NOT EXISTS "LAB_RESULTS_TEMPLATE_ID_idx" ON "LAB_RESULTS"("TEMPLATE_ID");

DO $$ BEGIN
  ALTER TABLE "LAB_RESULTS" ADD CONSTRAINT "LAB_RESULTS_LAB_REQUEST_ID_fkey"
    FOREIGN KEY ("LAB_REQUEST_ID") REFERENCES "LAB_REQUESTS"("LAB_REQUEST_ID") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "LAB_RESULTS" ADD CONSTRAINT "LAB_RESULTS_LAB_REQUEST_ITEM_ID_fkey"
    FOREIGN KEY ("LAB_REQUEST_ITEM_ID") REFERENCES "LAB_REQUEST_ITEMS"("ITEM_ID") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "LAB_RESULTS" ADD CONSTRAINT "LAB_RESULTS_TEMPLATE_ID_fkey"
    FOREIGN KEY ("TEMPLATE_ID") REFERENCES "LAB_RESULT_TEMPLATES"("TEMPLATE_ID") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- 4) LAB_RESULT_VERSIONS (immutable audit snapshots)
CREATE TABLE IF NOT EXISTS "LAB_RESULT_VERSIONS" (
    "VERSION_ID" SERIAL NOT NULL,
    "LAB_RESULT_ID" INTEGER NOT NULL,
    "VERSION" INTEGER NOT NULL,
    "VALUES" JSONB NOT NULL DEFAULT '{}',
    "COMMENT" TEXT,
    "ACTION" VARCHAR(50) NOT NULL,
    "REASON" TEXT,
    "ACTED_BY" VARCHAR(100),
    "ACTED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "LAB_RESULT_VERSIONS_pkey" PRIMARY KEY ("VERSION_ID")
);

CREATE INDEX IF NOT EXISTS "LAB_RESULT_VERSIONS_LAB_RESULT_ID_VERSION_idx" ON "LAB_RESULT_VERSIONS"("LAB_RESULT_ID", "VERSION");

DO $$ BEGIN
  ALTER TABLE "LAB_RESULT_VERSIONS" ADD CONSTRAINT "LAB_RESULT_VERSIONS_LAB_RESULT_ID_fkey"
    FOREIGN KEY ("LAB_RESULT_ID") REFERENCES "LAB_RESULTS"("LAB_RESULT_ID") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
