-- HR Self-Service Phase 2 — HOD columns + Pending → PendingHr migration

ALTER TABLE "HR_LEAVE_REQUESTS"
  ADD COLUMN IF NOT EXISTS "HOD_DECISION_BY_ID" INTEGER,
  ADD COLUMN IF NOT EXISTS "HOD_DECISION_BY" VARCHAR(100),
  ADD COLUMN IF NOT EXISTS "HOD_DECISION_AT" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "HOD_NOTE" TEXT,
  ADD COLUMN IF NOT EXISTS "APPROVER_EMPLOYEE_ID" INTEGER;

-- Existing backlog: Pending leave stays with HR (skip HOD re-queue)
UPDATE "HR_LEAVE_REQUESTS"
SET "STATUS" = 'PendingHr'
WHERE "STATUS" = 'Pending';
