-- Doctor clinical profile fields on USERS
ALTER TABLE "USERS" ADD COLUMN IF NOT EXISTS "SUB_SPECIALTY" VARCHAR(150);
ALTER TABLE "USERS" ADD COLUMN IF NOT EXISTS "QUALIFICATIONS" VARCHAR(255);
ALTER TABLE "USERS" ADD COLUMN IF NOT EXISTS "DEPARTMENT_NAME" VARCHAR(150);
ALTER TABLE "USERS" ADD COLUMN IF NOT EXISTS "CLINIC_NAME" VARCHAR(150);
ALTER TABLE "USERS" ADD COLUMN IF NOT EXISTS "CONSULTATION_HOURS" VARCHAR(255);
ALTER TABLE "USERS" ADD COLUMN IF NOT EXISTS "WARD_ASSIGNMENT" VARCHAR(255);

-- Certificate template store
CREATE TABLE IF NOT EXISTS "CERTIFICATE_TEMPLATES" (
    "TEMPLATE_ID" SERIAL NOT NULL,
    "CODE" VARCHAR(80) NOT NULL,
    "NAME" VARCHAR(150) NOT NULL,
    "DESCRIPTION" TEXT,
    "CATEGORY" VARCHAR(40) NOT NULL DEFAULT 'Report',
    "FIELD_SCHEMA" JSONB NOT NULL DEFAULT '[]',
    "APPROVAL_REQUIRED" BOOLEAN NOT NULL DEFAULT false,
    "LAYOUT" VARCHAR(40) NOT NULL DEFAULT 'Standard',
    "STATUS" VARCHAR(20) NOT NULL DEFAULT 'Active',
    "CREATED_BY_ID" INTEGER,
    "CREATED_BY" VARCHAR(100),
    "CREATED_DATE" TIMESTAMP(3),
    "UPDATED_BY_ID" INTEGER,
    "UPDATED_BY" VARCHAR(100),
    "UPDATED_DATE" TIMESTAMP(3),
    CONSTRAINT "CERTIFICATE_TEMPLATES_pkey" PRIMARY KEY ("TEMPLATE_ID")
);

CREATE UNIQUE INDEX IF NOT EXISTS "CERTIFICATE_TEMPLATES_CODE_key" ON "CERTIFICATE_TEMPLATES"("CODE");
CREATE INDEX IF NOT EXISTS "CERTIFICATE_TEMPLATES_STATUS_idx" ON "CERTIFICATE_TEMPLATES"("STATUS");
CREATE INDEX IF NOT EXISTS "CERTIFICATE_TEMPLATES_CATEGORY_idx" ON "CERTIFICATE_TEMPLATES"("CATEGORY");

-- Clinical certificates / reports
CREATE TABLE IF NOT EXISTS "CLINICAL_CERTIFICATES" (
    "CERTIFICATE_ID" SERIAL NOT NULL,
    "DOC_NO" VARCHAR(50) NOT NULL,
    "PERSON_ID" INTEGER NOT NULL,
    "TEMPLATE_ID" INTEGER NOT NULL,
    "STATUS" VARCHAR(40) NOT NULL DEFAULT 'Draft',
    "FIELDS" JSONB NOT NULL DEFAULT '{}',
    "LAYOUT" VARCHAR(40) NOT NULL DEFAULT 'Standard',
    "VALIDITY_UNTIL" TIMESTAMP(3),
    "LOCKED" BOOLEAN NOT NULL DEFAULT false,
    "QR_CODE" VARCHAR(120),
    "SIGNED_AT" TIMESTAMP(3),
    "SIGNED_BY" VARCHAR(150),
    "SIGNED_BY_USER_ID" INTEGER,
    "ISSUED_AT" TIMESTAMP(3),
    "ISSUED_BY" VARCHAR(150),
    "ISSUED_BY_USER_ID" INTEGER,
    "APPROVED_AT" TIMESTAMP(3),
    "APPROVED_BY" VARCHAR(150),
    "APPROVED_BY_USER_ID" INTEGER,
    "AUTHOR_USER_ID" INTEGER,
    "CREATED_BY_ID" INTEGER,
    "CREATED_BY" VARCHAR(100),
    "CREATED_DATE" TIMESTAMP(3),
    "UPDATED_BY_ID" INTEGER,
    "UPDATED_BY" VARCHAR(100),
    "UPDATED_DATE" TIMESTAMP(3),
    CONSTRAINT "CLINICAL_CERTIFICATES_pkey" PRIMARY KEY ("CERTIFICATE_ID")
);

CREATE UNIQUE INDEX IF NOT EXISTS "CLINICAL_CERTIFICATES_DOC_NO_key" ON "CLINICAL_CERTIFICATES"("DOC_NO");
CREATE INDEX IF NOT EXISTS "CLINICAL_CERTIFICATES_PERSON_ID_idx" ON "CLINICAL_CERTIFICATES"("PERSON_ID");
CREATE INDEX IF NOT EXISTS "CLINICAL_CERTIFICATES_TEMPLATE_ID_idx" ON "CLINICAL_CERTIFICATES"("TEMPLATE_ID");
CREATE INDEX IF NOT EXISTS "CLINICAL_CERTIFICATES_STATUS_idx" ON "CLINICAL_CERTIFICATES"("STATUS");
CREATE INDEX IF NOT EXISTS "CLINICAL_CERTIFICATES_AUTHOR_USER_ID_idx" ON "CLINICAL_CERTIFICATES"("AUTHOR_USER_ID");
CREATE INDEX IF NOT EXISTS "CLINICAL_CERTIFICATES_CREATED_DATE_idx" ON "CLINICAL_CERTIFICATES"("CREATED_DATE");

CREATE TABLE IF NOT EXISTS "CLINICAL_CERTIFICATE_EVENTS" (
    "EVENT_ID" SERIAL NOT NULL,
    "CERTIFICATE_ID" INTEGER NOT NULL,
    "EVENT_TYPE" VARCHAR(50) NOT NULL,
    "ACTOR_USER_ID" INTEGER,
    "ACTOR_LABEL" VARCHAR(150),
    "NOTE" TEXT,
    "OLD_STATUS" VARCHAR(40),
    "NEW_STATUS" VARCHAR(40),
    "CREATED_DATE" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "CLINICAL_CERTIFICATE_EVENTS_pkey" PRIMARY KEY ("EVENT_ID")
);

CREATE INDEX IF NOT EXISTS "CLINICAL_CERTIFICATE_EVENTS_CERTIFICATE_ID_idx" ON "CLINICAL_CERTIFICATE_EVENTS"("CERTIFICATE_ID");
CREATE INDEX IF NOT EXISTS "CLINICAL_CERTIFICATE_EVENTS_CREATED_DATE_idx" ON "CLINICAL_CERTIFICATE_EVENTS"("CREATED_DATE");

DO $$ BEGIN
  ALTER TABLE "CLINICAL_CERTIFICATES"
    ADD CONSTRAINT "CLINICAL_CERTIFICATES_PERSON_ID_fkey"
    FOREIGN KEY ("PERSON_ID") REFERENCES "PERSONS"("PERSON_ID")
    ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "CLINICAL_CERTIFICATES"
    ADD CONSTRAINT "CLINICAL_CERTIFICATES_TEMPLATE_ID_fkey"
    FOREIGN KEY ("TEMPLATE_ID") REFERENCES "CERTIFICATE_TEMPLATES"("TEMPLATE_ID")
    ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "CLINICAL_CERTIFICATES"
    ADD CONSTRAINT "CLINICAL_CERTIFICATES_AUTHOR_USER_ID_fkey"
    FOREIGN KEY ("AUTHOR_USER_ID") REFERENCES "USERS"("USER_ID")
    ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "CLINICAL_CERTIFICATE_EVENTS"
    ADD CONSTRAINT "CLINICAL_CERTIFICATE_EVENTS_CERTIFICATE_ID_fkey"
    FOREIGN KEY ("CERTIFICATE_ID") REFERENCES "CLINICAL_CERTIFICATES"("CERTIFICATE_ID")
    ON DELETE CASCADE ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
