-- Histopathology cases
CREATE TABLE IF NOT EXISTS "LAB_HISTOPATHOLOGY_CASES" (
    "CASE_ID" SERIAL NOT NULL,
    "CASE_NO" VARCHAR(50) NOT NULL,
    "PERSON_ID" INTEGER NOT NULL,
    "LAB_REQUEST_ID" INTEGER,
    "SPECIMEN_TYPE" VARCHAR(80) NOT NULL,
    "STAGE" VARCHAR(40) NOT NULL DEFAULT 'Received',
    "SITE" VARCHAR(255),
    "GROSS" TEXT,
    "MICRO" TEXT,
    "DIAGNOSIS" TEXT,
    "GRADE" VARCHAR(80),
    "RECEIVED_AT" TIMESTAMP(3),
    "CREATED_BY_ID" INTEGER,
    "CREATED_BY" VARCHAR(100),
    "CREATED_DATE" TIMESTAMP(3),
    "UPDATED_BY_ID" INTEGER,
    "UPDATED_BY" VARCHAR(100),
    "UPDATED_DATE" TIMESTAMP(3),
    "DELETED_FLAG" VARCHAR(1) DEFAULT 'N',

    CONSTRAINT "LAB_HISTOPATHOLOGY_CASES_pkey" PRIMARY KEY ("CASE_ID")
);

CREATE UNIQUE INDEX IF NOT EXISTS "LAB_HISTOPATHOLOGY_CASES_CASE_NO_key" ON "LAB_HISTOPATHOLOGY_CASES"("CASE_NO");
CREATE INDEX IF NOT EXISTS "LAB_HISTOPATHOLOGY_CASES_PERSON_ID_idx" ON "LAB_HISTOPATHOLOGY_CASES"("PERSON_ID");
CREATE INDEX IF NOT EXISTS "LAB_HISTOPATHOLOGY_CASES_STAGE_idx" ON "LAB_HISTOPATHOLOGY_CASES"("STAGE");
CREATE INDEX IF NOT EXISTS "LAB_HISTOPATHOLOGY_CASES_CREATED_DATE_idx" ON "LAB_HISTOPATHOLOGY_CASES"("CREATED_DATE");

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'LAB_HISTOPATHOLOGY_CASES_PERSON_ID_fkey'
  ) THEN
    ALTER TABLE "LAB_HISTOPATHOLOGY_CASES"
      ADD CONSTRAINT "LAB_HISTOPATHOLOGY_CASES_PERSON_ID_fkey"
      FOREIGN KEY ("PERSON_ID") REFERENCES "PERSONS"("PERSON_ID")
      ON DELETE RESTRICT ON UPDATE CASCADE;
  END IF;
END $$;

-- Quality control runs
CREATE TABLE IF NOT EXISTS "LAB_QC_RUNS" (
    "QC_RUN_ID" SERIAL NOT NULL,
    "RUN_NO" VARCHAR(50) NOT NULL,
    "ANALYTE" VARCHAR(150) NOT NULL,
    "INSTRUMENT" VARCHAR(150) NOT NULL,
    "LEVEL" VARCHAR(10) NOT NULL,
    "EXPECTED" VARCHAR(80) NOT NULL,
    "OBSERVED" VARCHAR(80) NOT NULL,
    "RESULT" VARCHAR(20) NOT NULL,
    "FREQ" VARCHAR(40) NOT NULL,
    "RUN_DATE" DATE NOT NULL,
    "CORRECTIVE" TEXT,
    "PREVENTIVE" TEXT,
    "ASSIGNED_TO" VARCHAR(100),
    "TARGET_DATE" DATE,
    "CAPA_STATUS" VARCHAR(20) NOT NULL DEFAULT 'None',
    "CREATED_BY_ID" INTEGER,
    "CREATED_BY" VARCHAR(100),
    "CREATED_DATE" TIMESTAMP(3),
    "UPDATED_BY_ID" INTEGER,
    "UPDATED_BY" VARCHAR(100),
    "UPDATED_DATE" TIMESTAMP(3),
    "DELETED_FLAG" VARCHAR(1) DEFAULT 'N',

    CONSTRAINT "LAB_QC_RUNS_pkey" PRIMARY KEY ("QC_RUN_ID")
);

CREATE UNIQUE INDEX IF NOT EXISTS "LAB_QC_RUNS_RUN_NO_key" ON "LAB_QC_RUNS"("RUN_NO");
CREATE INDEX IF NOT EXISTS "LAB_QC_RUNS_FREQ_idx" ON "LAB_QC_RUNS"("FREQ");
CREATE INDEX IF NOT EXISTS "LAB_QC_RUNS_RESULT_idx" ON "LAB_QC_RUNS"("RESULT");
CREATE INDEX IF NOT EXISTS "LAB_QC_RUNS_RUN_DATE_idx" ON "LAB_QC_RUNS"("RUN_DATE");

-- FE catalog gaps (labData.ts) — keep existing seed rows
INSERT INTO "LAB_TESTS" ("TEST_CODE", "NAME", "CATEGORY", "SPECIMEN_TYPE", "TURNAROUND", "UNIT_PRICE", "IS_PANEL", "STATUS", "CREATED_BY", "CREATED_DATE")
VALUES
  ('MP', 'Malaria Parasite (BF)', 'Microbiology', 'Blood Smear', '1 hr', 2500, false, 'Active', 'SYSTEM', NOW()),
  ('XRC', 'Chest X-Ray', 'Radiology', 'Imaging', '1 hr', 9500, false, 'Active', 'SYSTEM', NOW())
ON CONFLICT ("TEST_CODE") DO NOTHING;
