-- Doctor/Pharmacy legacy CSV support: catalog + drug stable keys
ALTER TABLE "DIAGNOSIS_CODES" ADD COLUMN IF NOT EXISTS "LEGACY_THESAURUS_ID" INTEGER;
ALTER TABLE "DIAGNOSIS_CODES" ADD COLUMN IF NOT EXISTS "LEGACY_DISEASE_ID" INTEGER;
ALTER TABLE "DIAGNOSIS_CODES" ADD COLUMN IF NOT EXISTS "ICPC_CODE" VARCHAR(40);

CREATE UNIQUE INDEX IF NOT EXISTS "DIAGNOSIS_CODES_LEGACY_THESAURUS_ID_key"
  ON "DIAGNOSIS_CODES"("LEGACY_THESAURUS_ID");
CREATE UNIQUE INDEX IF NOT EXISTS "DIAGNOSIS_CODES_LEGACY_DISEASE_ID_key"
  ON "DIAGNOSIS_CODES"("LEGACY_DISEASE_ID");
CREATE INDEX IF NOT EXISTS "DIAGNOSIS_CODES_ICPC_CODE_idx"
  ON "DIAGNOSIS_CODES"("ICPC_CODE");

ALTER TABLE "DRUGS" ADD COLUMN IF NOT EXISTS "LEGACY_ITEM_ID" INTEGER;
CREATE UNIQUE INDEX IF NOT EXISTS "DRUGS_LEGACY_ITEM_ID_key"
  ON "DRUGS"("LEGACY_ITEM_ID");
