-- Seminal fluid analysis + specimen chain-of-custody tracking

CREATE TABLE IF NOT EXISTS "LAB_SFA_ANALYSES" (
    "SFA_ID" SERIAL PRIMARY KEY,
    "SFA_NO" VARCHAR(50) NOT NULL,
    "PERSON_ID" INTEGER NOT NULL,
    "LAB_REQUEST_ID" INTEGER,
    "VOLUME_ML" VARCHAR(40),
    "COLOUR" VARCHAR(80),
    "VISCOSITY" VARCHAR(80),
    "LIQUEFACTION_MIN" VARCHAR(40),
    "PH" VARCHAR(40),
    "COUNT_M_ML" VARCHAR(40),
    "MOTILITY_PCT" VARCHAR(40),
    "MORPHOLOGY_PCT" VARCHAR(40),
    "PUS_CELLS" VARCHAR(40),
    "RBC" VARCHAR(40),
    "EPITHELIAL" VARCHAR(40),
    "INTERPRETATION" TEXT,
    "STATUS" VARCHAR(40) NOT NULL DEFAULT 'Draft',
    "REJECT_REASON" TEXT,
    "VALIDATED_AT" TIMESTAMP(3),
    "VALIDATED_BY" VARCHAR(100),
    "CREATED_BY_ID" INTEGER,
    "CREATED_BY" VARCHAR(100),
    "CREATED_DATE" TIMESTAMP(3),
    "UPDATED_BY_ID" INTEGER,
    "UPDATED_BY" VARCHAR(100),
    "UPDATED_DATE" TIMESTAMP(3),
    "DELETED_FLAG" VARCHAR(1) DEFAULT 'N',
    CONSTRAINT "LAB_SFA_ANALYSES_SFA_NO_key" UNIQUE ("SFA_NO"),
    CONSTRAINT "LAB_SFA_ANALYSES_PERSON_ID_fkey" FOREIGN KEY ("PERSON_ID") REFERENCES "PERSONS"("PERSON_ID") ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS "LAB_SFA_ANALYSES_PERSON_ID_idx" ON "LAB_SFA_ANALYSES"("PERSON_ID");
CREATE INDEX IF NOT EXISTS "LAB_SFA_ANALYSES_STATUS_idx" ON "LAB_SFA_ANALYSES"("STATUS");
CREATE INDEX IF NOT EXISTS "LAB_SFA_ANALYSES_CREATED_DATE_idx" ON "LAB_SFA_ANALYSES"("CREATED_DATE");

CREATE TABLE IF NOT EXISTS "LAB_SPECIMEN_TRACKING" (
    "SPECIMEN_ID" SERIAL PRIMARY KEY,
    "SPECIMEN_NO" VARCHAR(50) NOT NULL,
    "PERSON_ID" INTEGER NOT NULL,
    "LAB_REQUEST_ID" INTEGER,
    "LAB_SAMPLE_ID" INTEGER,
    "TEST_LABEL" VARCHAR(150) NOT NULL,
    "COLLECTED_BY" VARCHAR(100),
    "LOCATION" VARCHAR(150) NOT NULL DEFAULT 'Reception',
    "STATUS" VARCHAR(40) NOT NULL DEFAULT 'Received',
    "COLLECTED_AT" TIMESTAMP(3),
    "TAT_LABEL" VARCHAR(40),
    "CREATED_BY_ID" INTEGER,
    "CREATED_BY" VARCHAR(100),
    "CREATED_DATE" TIMESTAMP(3),
    "UPDATED_BY_ID" INTEGER,
    "UPDATED_BY" VARCHAR(100),
    "UPDATED_DATE" TIMESTAMP(3),
    "DELETED_FLAG" VARCHAR(1) DEFAULT 'N',
    CONSTRAINT "LAB_SPECIMEN_TRACKING_SPECIMEN_NO_key" UNIQUE ("SPECIMEN_NO"),
    CONSTRAINT "LAB_SPECIMEN_TRACKING_PERSON_ID_fkey" FOREIGN KEY ("PERSON_ID") REFERENCES "PERSONS"("PERSON_ID") ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS "LAB_SPECIMEN_TRACKING_PERSON_ID_idx" ON "LAB_SPECIMEN_TRACKING"("PERSON_ID");
CREATE INDEX IF NOT EXISTS "LAB_SPECIMEN_TRACKING_STATUS_idx" ON "LAB_SPECIMEN_TRACKING"("STATUS");
CREATE INDEX IF NOT EXISTS "LAB_SPECIMEN_TRACKING_CREATED_DATE_idx" ON "LAB_SPECIMEN_TRACKING"("CREATED_DATE");

CREATE TABLE IF NOT EXISTS "LAB_SPECIMEN_EVENTS" (
    "EVENT_ID" SERIAL PRIMARY KEY,
    "SPECIMEN_ID" INTEGER NOT NULL,
    "ACTION" VARCHAR(40) NOT NULL,
    "FROM_LOCATION" VARCHAR(150),
    "TO_LOCATION" VARCHAR(150),
    "REASON" VARCHAR(255),
    "ACTOR_LABEL" VARCHAR(100),
    "CREATED_DATE" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "LAB_SPECIMEN_EVENTS_SPECIMEN_ID_fkey" FOREIGN KEY ("SPECIMEN_ID") REFERENCES "LAB_SPECIMEN_TRACKING"("SPECIMEN_ID") ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS "LAB_SPECIMEN_EVENTS_SPECIMEN_ID_idx" ON "LAB_SPECIMEN_EVENTS"("SPECIMEN_ID");
CREATE INDEX IF NOT EXISTS "LAB_SPECIMEN_EVENTS_CREATED_DATE_idx" ON "LAB_SPECIMEN_EVENTS"("CREATED_DATE");
