-- Admissions wards/beds + nursing care documentation tables
CREATE TABLE IF NOT EXISTS "WARDS" (
  "WARD_ID" SERIAL PRIMARY KEY,
  "CODE" VARCHAR(50) NOT NULL UNIQUE,
  "NAME" VARCHAR(150) NOT NULL,
  "WARD_TYPE" VARCHAR(50),
  "STATUS" VARCHAR(30) NOT NULL DEFAULT 'Active',
  "CREATED_BY" VARCHAR(100),
  "CREATED_DATE" TIMESTAMP(3),
  "UPDATED_BY" VARCHAR(100),
  "UPDATED_DATE" TIMESTAMP(3)
);

CREATE TABLE IF NOT EXISTS "BEDS" (
  "BED_ID" SERIAL PRIMARY KEY,
  "WARD_ID" INTEGER NOT NULL,
  "LABEL" VARCHAR(50) NOT NULL,
  "STATUS" VARCHAR(30) NOT NULL DEFAULT 'AVAILABLE',
  "CREATED_BY" VARCHAR(100),
  "CREATED_DATE" TIMESTAMP(3),
  "UPDATED_BY" VARCHAR(100),
  "UPDATED_DATE" TIMESTAMP(3),
  CONSTRAINT "BEDS_WARD_ID_fkey" FOREIGN KEY ("WARD_ID") REFERENCES "WARDS"("WARD_ID") ON DELETE RESTRICT ON UPDATE CASCADE
);
CREATE UNIQUE INDEX IF NOT EXISTS "BEDS_WARD_ID_LABEL_key" ON "BEDS"("WARD_ID", "LABEL");
CREATE INDEX IF NOT EXISTS "BEDS_WARD_ID_idx" ON "BEDS"("WARD_ID");
CREATE INDEX IF NOT EXISTS "BEDS_STATUS_idx" ON "BEDS"("STATUS");

CREATE TABLE IF NOT EXISTS "ADMISSIONS" (
  "ADMISSION_ID" SERIAL PRIMARY KEY,
  "PERSON_ID" INTEGER NOT NULL,
  "WARD_ID" INTEGER,
  "BED_ID" INTEGER,
  "DIAGNOSIS" TEXT,
  "CONSULTANT" VARCHAR(255),
  "ASSIGNED_NURSE" VARCHAR(255),
  "ADMISSION_TYPE" VARCHAR(50),
  "SUPERVISION_LEVEL" VARCHAR(50),
  "STATUS" VARCHAR(40) NOT NULL DEFAULT 'ADMITTED',
  "ADMITTED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "DISCHARGE_ORDERED_AT" TIMESTAMP(3),
  "DISCHARGE_ORDERED_BY" VARCHAR(100),
  "DISCHARGE_REASON" VARCHAR(500),
  "DISCHARGED_AT" TIMESTAMP(3),
  "DISCHARGED_BY" VARCHAR(100),
  "CREATED_BY_ID" INTEGER,
  "UPDATED_BY_ID" INTEGER,
  "CREATED_BY" VARCHAR(100),
  "CREATED_DATE" TIMESTAMP(3),
  "UPDATED_BY" VARCHAR(100),
  "UPDATED_DATE" TIMESTAMP(3),
  CONSTRAINT "ADMISSIONS_PERSON_ID_fkey" FOREIGN KEY ("PERSON_ID") REFERENCES "PERSONS"("PERSON_ID") ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT "ADMISSIONS_WARD_ID_fkey" FOREIGN KEY ("WARD_ID") REFERENCES "WARDS"("WARD_ID") ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT "ADMISSIONS_BED_ID_fkey" FOREIGN KEY ("BED_ID") REFERENCES "BEDS"("BED_ID") ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE INDEX IF NOT EXISTS "ADMISSIONS_PERSON_ID_idx" ON "ADMISSIONS"("PERSON_ID");
CREATE INDEX IF NOT EXISTS "ADMISSIONS_STATUS_idx" ON "ADMISSIONS"("STATUS");
CREATE INDEX IF NOT EXISTS "ADMISSIONS_WARD_ID_idx" ON "ADMISSIONS"("WARD_ID");
CREATE INDEX IF NOT EXISTS "ADMISSIONS_ADMITTED_AT_idx" ON "ADMISSIONS"("ADMITTED_AT");

CREATE TABLE IF NOT EXISTS "NURSING_NOTES" (
  "NOTE_ID" SERIAL PRIMARY KEY,
  "ADMISSION_ID" INTEGER,
  "PERSON_ID" INTEGER NOT NULL,
  "NOTE_TYPE" VARCHAR(40) NOT NULL DEFAULT 'General',
  "FORMAT" VARCHAR(20) NOT NULL DEFAULT 'Narrative',
  "BODY" TEXT NOT NULL,
  "AUTHOR_BY" VARCHAR(100),
  "CREATED_BY_ID" INTEGER,
  "CREATED_DATE" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "UPDATED_DATE" TIMESTAMP(3),
  CONSTRAINT "NURSING_NOTES_ADMISSION_ID_fkey" FOREIGN KEY ("ADMISSION_ID") REFERENCES "ADMISSIONS"("ADMISSION_ID") ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT "NURSING_NOTES_PERSON_ID_fkey" FOREIGN KEY ("PERSON_ID") REFERENCES "PERSONS"("PERSON_ID") ON DELETE RESTRICT ON UPDATE CASCADE
);
CREATE INDEX IF NOT EXISTS "NURSING_NOTES_PERSON_ID_idx" ON "NURSING_NOTES"("PERSON_ID");
CREATE INDEX IF NOT EXISTS "NURSING_NOTES_ADMISSION_ID_idx" ON "NURSING_NOTES"("ADMISSION_ID");
CREATE INDEX IF NOT EXISTS "NURSING_NOTES_CREATED_DATE_idx" ON "NURSING_NOTES"("CREATED_DATE");

CREATE TABLE IF NOT EXISTS "NURSING_VITALS" (
  "VITAL_ID" SERIAL PRIMARY KEY,
  "ADMISSION_ID" INTEGER,
  "PERSON_ID" INTEGER NOT NULL,
  "WEIGHT_KG" DECIMAL(8,2),
  "HEIGHT_CM" DECIMAL(8,2),
  "BMI" DECIMAL(8,2),
  "BLOOD_PRESSURE" VARCHAR(20),
  "TEMPERATURE_C" DECIMAL(5,2),
  "PULSE_BPM" INTEGER,
  "RESPIRATORY_RATE" INTEGER,
  "SPO2_PCT" DECIMAL(5,2),
  "BLOOD_SUGAR" DECIMAL(8,2),
  "PAIN_SCORE" INTEGER,
  "ABNORMAL" BOOLEAN NOT NULL DEFAULT false,
  "FLAGS" VARCHAR(500),
  "NOTES" TEXT,
  "RECORDED_BY" VARCHAR(100),
  "RECORDED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "CREATED_BY_ID" INTEGER,
  CONSTRAINT "NURSING_VITALS_ADMISSION_ID_fkey" FOREIGN KEY ("ADMISSION_ID") REFERENCES "ADMISSIONS"("ADMISSION_ID") ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT "NURSING_VITALS_PERSON_ID_fkey" FOREIGN KEY ("PERSON_ID") REFERENCES "PERSONS"("PERSON_ID") ON DELETE RESTRICT ON UPDATE CASCADE
);
CREATE INDEX IF NOT EXISTS "NURSING_VITALS_PERSON_ID_idx" ON "NURSING_VITALS"("PERSON_ID");
CREATE INDEX IF NOT EXISTS "NURSING_VITALS_ADMISSION_ID_idx" ON "NURSING_VITALS"("ADMISSION_ID");
CREATE INDEX IF NOT EXISTS "NURSING_VITALS_RECORDED_AT_idx" ON "NURSING_VITALS"("RECORDED_AT");
CREATE INDEX IF NOT EXISTS "NURSING_VITALS_ABNORMAL_idx" ON "NURSING_VITALS"("ABNORMAL");

CREATE TABLE IF NOT EXISTS "NURSING_CARE_PLANS" (
  "CARE_PLAN_ID" SERIAL PRIMARY KEY,
  "ADMISSION_ID" INTEGER,
  "PERSON_ID" INTEGER NOT NULL,
  "DIAGNOSIS" VARCHAR(500),
  "PROBLEM" TEXT,
  "GOAL" TEXT,
  "INTERVENTION" TEXT,
  "ACTION_TAKEN" TEXT,
  "EVALUATION" TEXT,
  "REVIEW_DATE" TIMESTAMP(3),
  "STATUS" VARCHAR(20) NOT NULL DEFAULT 'active',
  "CREATED_BY" VARCHAR(100),
  "CREATED_DATE" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "UPDATED_DATE" TIMESTAMP(3),
  CONSTRAINT "NURSING_CARE_PLANS_ADMISSION_ID_fkey" FOREIGN KEY ("ADMISSION_ID") REFERENCES "ADMISSIONS"("ADMISSION_ID") ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT "NURSING_CARE_PLANS_PERSON_ID_fkey" FOREIGN KEY ("PERSON_ID") REFERENCES "PERSONS"("PERSON_ID") ON DELETE RESTRICT ON UPDATE CASCADE
);
CREATE INDEX IF NOT EXISTS "NURSING_CARE_PLANS_PERSON_ID_idx" ON "NURSING_CARE_PLANS"("PERSON_ID");
CREATE INDEX IF NOT EXISTS "NURSING_CARE_PLANS_ADMISSION_ID_idx" ON "NURSING_CARE_PLANS"("ADMISSION_ID");
CREATE INDEX IF NOT EXISTS "NURSING_CARE_PLANS_STATUS_idx" ON "NURSING_CARE_PLANS"("STATUS");

CREATE TABLE IF NOT EXISTS "NURSING_OBSERVATIONS" (
  "OBSERVATION_ID" SERIAL PRIMARY KEY,
  "ADMISSION_ID" INTEGER,
  "PERSON_ID" INTEGER NOT NULL,
  "CHART" VARCHAR(40) NOT NULL DEFAULT 'Psychiatric',
  "INTERVAL" VARCHAR(20),
  "FIELDS_JSON" TEXT NOT NULL,
  "RECORDED_BY" VARCHAR(100),
  "RECORDED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "CREATED_BY_ID" INTEGER,
  CONSTRAINT "NURSING_OBSERVATIONS_ADMISSION_ID_fkey" FOREIGN KEY ("ADMISSION_ID") REFERENCES "ADMISSIONS"("ADMISSION_ID") ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT "NURSING_OBSERVATIONS_PERSON_ID_fkey" FOREIGN KEY ("PERSON_ID") REFERENCES "PERSONS"("PERSON_ID") ON DELETE RESTRICT ON UPDATE CASCADE
);
CREATE INDEX IF NOT EXISTS "NURSING_OBSERVATIONS_PERSON_ID_idx" ON "NURSING_OBSERVATIONS"("PERSON_ID");
CREATE INDEX IF NOT EXISTS "NURSING_OBSERVATIONS_ADMISSION_ID_idx" ON "NURSING_OBSERVATIONS"("ADMISSION_ID");
CREATE INDEX IF NOT EXISTS "NURSING_OBSERVATIONS_RECORDED_AT_idx" ON "NURSING_OBSERVATIONS"("RECORDED_AT");

CREATE TABLE IF NOT EXISTS "NURSING_INCIDENTS" (
  "INCIDENT_ID" SERIAL PRIMARY KEY,
  "ADMISSION_ID" INTEGER,
  "PERSON_ID" INTEGER,
  "PATIENT_NAME" VARCHAR(255),
  "INCIDENT_TYPE" VARCHAR(40) NOT NULL,
  "DESCRIPTION" TEXT NOT NULL,
  "ACTION_TAKEN" TEXT,
  "SEVERITY" VARCHAR(20) NOT NULL DEFAULT 'Moderate',
  "STATUS" VARCHAR(20) NOT NULL DEFAULT 'REPORTED',
  "REPORTED_BY" VARCHAR(100),
  "REVIEWED_BY" VARCHAR(100),
  "REVIEWED_AT" TIMESTAMP(3),
  "REVIEW_NOTE" TEXT,
  "CREATED_DATE" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "CREATED_BY_ID" INTEGER,
  CONSTRAINT "NURSING_INCIDENTS_ADMISSION_ID_fkey" FOREIGN KEY ("ADMISSION_ID") REFERENCES "ADMISSIONS"("ADMISSION_ID") ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT "NURSING_INCIDENTS_PERSON_ID_fkey" FOREIGN KEY ("PERSON_ID") REFERENCES "PERSONS"("PERSON_ID") ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE INDEX IF NOT EXISTS "NURSING_INCIDENTS_PERSON_ID_idx" ON "NURSING_INCIDENTS"("PERSON_ID");
CREATE INDEX IF NOT EXISTS "NURSING_INCIDENTS_STATUS_idx" ON "NURSING_INCIDENTS"("STATUS");
CREATE INDEX IF NOT EXISTS "NURSING_INCIDENTS_CREATED_DATE_idx" ON "NURSING_INCIDENTS"("CREATED_DATE");

CREATE TABLE IF NOT EXISTS "NURSING_FORM_TEMPLATES" (
  "TEMPLATE_ID" SERIAL PRIMARY KEY,
  "CODE" VARCHAR(50) NOT NULL UNIQUE,
  "TITLE" VARCHAR(255) NOT NULL,
  "SCHEMA_JSON" TEXT NOT NULL,
  "ACTIVE" BOOLEAN NOT NULL DEFAULT true,
  "CREATED_BY" VARCHAR(100),
  "CREATED_DATE" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "UPDATED_DATE" TIMESTAMP(3)
);

CREATE TABLE IF NOT EXISTS "NURSING_FORM_INSTANCES" (
  "INSTANCE_ID" SERIAL PRIMARY KEY,
  "TEMPLATE_ID" INTEGER NOT NULL,
  "ADMISSION_ID" INTEGER,
  "PERSON_ID" INTEGER NOT NULL,
  "VALUES_JSON" TEXT NOT NULL,
  "SIGNED_BY" VARCHAR(100),
  "CREATED_DATE" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "NURSING_FORM_INSTANCES_TEMPLATE_ID_fkey" FOREIGN KEY ("TEMPLATE_ID") REFERENCES "NURSING_FORM_TEMPLATES"("TEMPLATE_ID") ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT "NURSING_FORM_INSTANCES_ADMISSION_ID_fkey" FOREIGN KEY ("ADMISSION_ID") REFERENCES "ADMISSIONS"("ADMISSION_ID") ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT "NURSING_FORM_INSTANCES_PERSON_ID_fkey" FOREIGN KEY ("PERSON_ID") REFERENCES "PERSONS"("PERSON_ID") ON DELETE RESTRICT ON UPDATE CASCADE
);
CREATE INDEX IF NOT EXISTS "NURSING_FORM_INSTANCES_PERSON_ID_idx" ON "NURSING_FORM_INSTANCES"("PERSON_ID");
CREATE INDEX IF NOT EXISTS "NURSING_FORM_INSTANCES_TEMPLATE_ID_idx" ON "NURSING_FORM_INSTANCES"("TEMPLATE_ID");
