-- Align IMAGING_REQUESTS and IMAGING_STUDIES with Prisma radiology.prisma (schema drift fix)

ALTER TABLE "IMAGING_REQUESTS" ADD COLUMN IF NOT EXISTS "NURSING_ORDER_ID" INTEGER;
ALTER TABLE "IMAGING_REQUESTS" ADD COLUMN IF NOT EXISTS "SCHEDULED_AT" TIMESTAMP(3);
ALTER TABLE "IMAGING_REQUESTS" ADD COLUMN IF NOT EXISTS "SCHEDULED_ROOM" VARCHAR(80);
ALTER TABLE "IMAGING_REQUESTS" ADD COLUMN IF NOT EXISTS "STARTED_AT" TIMESTAMP(3);
ALTER TABLE "IMAGING_REQUESTS" ADD COLUMN IF NOT EXISTS "COMPLETED_AT" TIMESTAMP(3);
ALTER TABLE "IMAGING_REQUESTS" ADD COLUMN IF NOT EXISTS "STUDY_UID" VARCHAR(120);
ALTER TABLE "IMAGING_REQUESTS" ADD COLUMN IF NOT EXISTS "EQUIPMENT_ID" INTEGER;
ALTER TABLE "IMAGING_REQUESTS" ADD COLUMN IF NOT EXISTS "PREP_JSON" TEXT;
ALTER TABLE "IMAGING_REQUESTS" ADD COLUMN IF NOT EXISTS "SAFETY_JSON" TEXT;

-- DOCTOR_ID is optional in Prisma schema
ALTER TABLE "IMAGING_REQUESTS" ALTER COLUMN "DOCTOR_ID" DROP NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS "IMAGING_REQUESTS_NURSING_ORDER_ID_key"
  ON "IMAGING_REQUESTS"("NURSING_ORDER_ID")
  WHERE "NURSING_ORDER_ID" IS NOT NULL;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'IMAGING_REQUESTS_NURSING_ORDER_ID_fkey'
  ) THEN
    ALTER TABLE "IMAGING_REQUESTS"
      ADD CONSTRAINT "IMAGING_REQUESTS_NURSING_ORDER_ID_fkey"
      FOREIGN KEY ("NURSING_ORDER_ID") REFERENCES "NURSING_ORDERS"("ORDER_ID")
      ON DELETE SET NULL ON UPDATE CASCADE;
  END IF;
END $$;

ALTER TABLE "IMAGING_STUDIES" ADD COLUMN IF NOT EXISTS "SERVICE_ID" INTEGER;

CREATE INDEX IF NOT EXISTS "IMAGING_STUDIES_SERVICE_ID_idx" ON "IMAGING_STUDIES"("SERVICE_ID");

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'IMAGING_STUDIES_SERVICE_ID_fkey'
  ) THEN
    ALTER TABLE "IMAGING_STUDIES"
      ADD CONSTRAINT "IMAGING_STUDIES_SERVICE_ID_fkey"
      FOREIGN KEY ("SERVICE_ID") REFERENCES "MASTER_SERVICES"("SERVICE_ID")
      ON DELETE SET NULL ON UPDATE CASCADE;
  END IF;
END $$;
