-- HR Self-Service Phase 1 — department heads + public holidays (D3 = yes)

CREATE TABLE IF NOT EXISTS "HR_DEPARTMENT_HEADS" (
    "ID" SERIAL NOT NULL,
    "DEPARTMENT_ID" INTEGER NOT NULL,
    "HEAD_EMPLOYEE_ID" INTEGER NOT NULL,
    "DEPUTY_EMPLOYEE_ID" INTEGER,
    "CREATED_BY_ID" INTEGER,
    "CREATED_BY" VARCHAR(100),
    "CREATED_DATE" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_BY_ID" INTEGER,
    "UPDATED_BY" VARCHAR(100),
    "UPDATED_DATE" TIMESTAMP(3),
    CONSTRAINT "HR_DEPARTMENT_HEADS_pkey" PRIMARY KEY ("ID")
);
CREATE UNIQUE INDEX IF NOT EXISTS "HR_DEPARTMENT_HEADS_DEPARTMENT_ID_key" ON "HR_DEPARTMENT_HEADS"("DEPARTMENT_ID");

CREATE TABLE IF NOT EXISTS "HR_PUBLIC_HOLIDAYS" (
    "HOLIDAY_ID" SERIAL NOT NULL,
    "HOLIDAY_DATE" DATE NOT NULL,
    "NAME" VARCHAR(150) NOT NULL,
    "CREATED_BY_ID" INTEGER,
    "CREATED_BY" VARCHAR(100),
    "CREATED_DATE" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "HR_PUBLIC_HOLIDAYS_pkey" PRIMARY KEY ("HOLIDAY_ID")
);
CREATE UNIQUE INDEX IF NOT EXISTS "HR_PUBLIC_HOLIDAYS_HOLIDAY_DATE_key" ON "HR_PUBLIC_HOLIDAYS"("HOLIDAY_DATE");
