-- Psychiatric OPC (Phase C.0): visits, assessments, risk, notes

CREATE TABLE IF NOT EXISTS "OPC_VISITS" (
  "OPC_VISIT_ID" SERIAL NOT NULL,
  "VISIT_NO" VARCHAR(40) NOT NULL,
  "PERSON_ID" INTEGER NOT NULL,
  "VISIT_TYPE" VARCHAR(40) NOT NULL,
  "PAYER" VARCHAR(40) NOT NULL DEFAULT 'Cash',
  "PRIORITY" VARCHAR(20) NOT NULL DEFAULT 'Normal',
  "STATUS" VARCHAR(40) NOT NULL DEFAULT 'WAITING',
  "ASSIGNED_DOCTOR" VARCHAR(120),
  "CLINIC" VARCHAR(120),
  "REASON" TEXT,
  "BILLING_STATUS" VARCHAR(20) NOT NULL DEFAULT 'NotBilled',
  "CONSULT_AMOUNT" DECIMAL(18,2) NOT NULL DEFAULT 7500,
  "PAID_AT" TIMESTAMP(3),
  "PAID_BY" VARCHAR(120),
  "PAYMENT_CHANNEL" VARCHAR(40),
  "PAYMENT_REF" VARCHAR(100),
  "CHECK_IN_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "CREATED_BY_ID" INTEGER,
  "CREATED_BY" VARCHAR(120),
  "CREATED_DATE" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "UPDATED_DATE" TIMESTAMP(3),
  "AUDIT_JSON" TEXT,
  CONSTRAINT "OPC_VISITS_pkey" PRIMARY KEY ("OPC_VISIT_ID")
);

CREATE UNIQUE INDEX IF NOT EXISTS "OPC_VISITS_VISIT_NO_key" ON "OPC_VISITS"("VISIT_NO");
CREATE INDEX IF NOT EXISTS "OPC_VISITS_PERSON_ID_idx" ON "OPC_VISITS"("PERSON_ID");
CREATE INDEX IF NOT EXISTS "OPC_VISITS_STATUS_idx" ON "OPC_VISITS"("STATUS");
CREATE INDEX IF NOT EXISTS "OPC_VISITS_CHECK_IN_AT_idx" ON "OPC_VISITS"("CHECK_IN_AT");
CREATE INDEX IF NOT EXISTS "OPC_VISITS_BILLING_STATUS_idx" ON "OPC_VISITS"("BILLING_STATUS");

DO $$ BEGIN
  ALTER TABLE "OPC_VISITS" ADD CONSTRAINT "OPC_VISITS_PERSON_ID_fkey"
    FOREIGN KEY ("PERSON_ID") REFERENCES "PERSONS"("PERSON_ID") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "OPC_ASSESSMENTS" (
  "ASSESSMENT_ID" SERIAL NOT NULL,
  "PERSON_ID" INTEGER NOT NULL,
  "OPC_VISIT_ID" INTEGER,
  "TYPE" VARCHAR(60) NOT NULL,
  "VALUES_JSON" TEXT NOT NULL,
  "SUMMARY" TEXT,
  "CREATED_BY" VARCHAR(120),
  "CREATED_DATE" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "OPC_ASSESSMENTS_pkey" PRIMARY KEY ("ASSESSMENT_ID")
);

CREATE INDEX IF NOT EXISTS "OPC_ASSESSMENTS_PERSON_ID_idx" ON "OPC_ASSESSMENTS"("PERSON_ID");
CREATE INDEX IF NOT EXISTS "OPC_ASSESSMENTS_OPC_VISIT_ID_idx" ON "OPC_ASSESSMENTS"("OPC_VISIT_ID");

DO $$ BEGIN
  ALTER TABLE "OPC_ASSESSMENTS" ADD CONSTRAINT "OPC_ASSESSMENTS_PERSON_ID_fkey"
    FOREIGN KEY ("PERSON_ID") REFERENCES "PERSONS"("PERSON_ID") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "OPC_ASSESSMENTS" ADD CONSTRAINT "OPC_ASSESSMENTS_OPC_VISIT_ID_fkey"
    FOREIGN KEY ("OPC_VISIT_ID") REFERENCES "OPC_VISITS"("OPC_VISIT_ID") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "OPC_RISK_ASSESSMENTS" (
  "RISK_ID" SERIAL NOT NULL,
  "PERSON_ID" INTEGER NOT NULL,
  "OPC_VISIT_ID" INTEGER,
  "SELF_HARM" VARCHAR(20) NOT NULL,
  "HARM_TO_OTHERS" VARCHAR(20) NOT NULL,
  "ABSCONDING" VARCHAR(20) NOT NULL,
  "NEGLECT" VARCHAR(20) NOT NULL,
  "SUBSTANCE" VARCHAR(20) NOT NULL,
  "VULNERABLE_FLAG" BOOLEAN NOT NULL DEFAULT false,
  "CRISIS_ALERT" BOOLEAN NOT NULL DEFAULT false,
  "SAFETY_PLAN" TEXT,
  "CREATED_BY" VARCHAR(120),
  "CREATED_DATE" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "OPC_RISK_ASSESSMENTS_pkey" PRIMARY KEY ("RISK_ID")
);

CREATE INDEX IF NOT EXISTS "OPC_RISK_ASSESSMENTS_PERSON_ID_idx" ON "OPC_RISK_ASSESSMENTS"("PERSON_ID");
CREATE INDEX IF NOT EXISTS "OPC_RISK_ASSESSMENTS_OPC_VISIT_ID_idx" ON "OPC_RISK_ASSESSMENTS"("OPC_VISIT_ID");

DO $$ BEGIN
  ALTER TABLE "OPC_RISK_ASSESSMENTS" ADD CONSTRAINT "OPC_RISK_ASSESSMENTS_PERSON_ID_fkey"
    FOREIGN KEY ("PERSON_ID") REFERENCES "PERSONS"("PERSON_ID") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "OPC_RISK_ASSESSMENTS" ADD CONSTRAINT "OPC_RISK_ASSESSMENTS_OPC_VISIT_ID_fkey"
    FOREIGN KEY ("OPC_VISIT_ID") REFERENCES "OPC_VISITS"("OPC_VISIT_ID") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "OPC_NOTES" (
  "NOTE_ID" SERIAL NOT NULL,
  "PERSON_ID" INTEGER NOT NULL,
  "OPC_VISIT_ID" INTEGER,
  "TYPE" VARCHAR(60) NOT NULL,
  "CONTENT" TEXT NOT NULL,
  "STATUS" VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
  "CONFIDENTIAL" BOOLEAN NOT NULL DEFAULT false,
  "CREATED_BY" VARCHAR(120),
  "CREATED_BY_ID" INTEGER,
  "CREATED_DATE" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "UPDATED_DATE" TIMESTAMP(3),
  CONSTRAINT "OPC_NOTES_pkey" PRIMARY KEY ("NOTE_ID")
);

CREATE INDEX IF NOT EXISTS "OPC_NOTES_PERSON_ID_idx" ON "OPC_NOTES"("PERSON_ID");
CREATE INDEX IF NOT EXISTS "OPC_NOTES_OPC_VISIT_ID_idx" ON "OPC_NOTES"("OPC_VISIT_ID");

DO $$ BEGIN
  ALTER TABLE "OPC_NOTES" ADD CONSTRAINT "OPC_NOTES_PERSON_ID_fkey"
    FOREIGN KEY ("PERSON_ID") REFERENCES "PERSONS"("PERSON_ID") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "OPC_NOTES" ADD CONSTRAINT "OPC_NOTES_OPC_VISIT_ID_fkey"
    FOREIGN KEY ("OPC_VISIT_ID") REFERENCES "OPC_VISITS"("OPC_VISIT_ID") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
