-- Lab specialty workstations + blood donors / unit doctor fields

CREATE TABLE IF NOT EXISTS "LAB_DRUG_SCREENS" (
    "SCREEN_ID" SERIAL PRIMARY KEY,
    "SCREEN_NO" VARCHAR(50) NOT NULL,
    "PERSON_ID" INTEGER NOT NULL,
    "LAB_REQUEST_ID" INTEGER,
    "SAMPLE_NO" VARCHAR(50),
    "SAMPLE_TYPE" VARCHAR(50) NOT NULL DEFAULT 'Urine',
    "COLLECTED_AT" TIMESTAMP(3),
    "COLLECTED_BY" VARCHAR(100),
    "STATUS" VARCHAR(40) NOT NULL DEFAULT 'Draft',
    "REJECT_REASON" TEXT,
    "VALIDATED_AT" TIMESTAMP(3),
    "VALIDATED_BY" VARCHAR(100),
    "CREATED_BY_ID" INTEGER,
    "CREATED_BY" VARCHAR(100),
    "CREATED_DATE" TIMESTAMP(3),
    "UPDATED_BY_ID" INTEGER,
    "UPDATED_BY" VARCHAR(100),
    "UPDATED_DATE" TIMESTAMP(3),
    "DELETED_FLAG" VARCHAR(1) DEFAULT 'N',
    CONSTRAINT "LAB_DRUG_SCREENS_PERSON_ID_fkey"
      FOREIGN KEY ("PERSON_ID") REFERENCES "PERSONS"("PERSON_ID") ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS "LAB_DRUG_SCREENS_SCREEN_NO_key" ON "LAB_DRUG_SCREENS"("SCREEN_NO");
CREATE INDEX IF NOT EXISTS "LAB_DRUG_SCREENS_PERSON_ID_idx" ON "LAB_DRUG_SCREENS"("PERSON_ID");
CREATE INDEX IF NOT EXISTS "LAB_DRUG_SCREENS_STATUS_idx" ON "LAB_DRUG_SCREENS"("STATUS");
CREATE INDEX IF NOT EXISTS "LAB_DRUG_SCREENS_CREATED_DATE_idx" ON "LAB_DRUG_SCREENS"("CREATED_DATE");
CREATE INDEX IF NOT EXISTS "LAB_DRUG_SCREENS_LAB_REQUEST_ID_idx" ON "LAB_DRUG_SCREENS"("LAB_REQUEST_ID");

CREATE TABLE IF NOT EXISTS "LAB_DRUG_SCREEN_RESULTS" (
    "RESULT_ID" SERIAL PRIMARY KEY,
    "SCREEN_ID" INTEGER NOT NULL,
    "DRUG_CODE" VARCHAR(40) NOT NULL,
    "DRUG_NAME" VARCHAR(100) NOT NULL,
    "RESULT" VARCHAR(20) NOT NULL DEFAULT 'Pending',
    "REMARKS" VARCHAR(255),
    CONSTRAINT "LAB_DRUG_SCREEN_RESULTS_SCREEN_ID_fkey"
      FOREIGN KEY ("SCREEN_ID") REFERENCES "LAB_DRUG_SCREENS"("SCREEN_ID") ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS "LAB_DRUG_SCREEN_RESULTS_SCREEN_ID_DRUG_CODE_key"
  ON "LAB_DRUG_SCREEN_RESULTS"("SCREEN_ID", "DRUG_CODE");
CREATE INDEX IF NOT EXISTS "LAB_DRUG_SCREEN_RESULTS_SCREEN_ID_idx" ON "LAB_DRUG_SCREEN_RESULTS"("SCREEN_ID");

CREATE TABLE IF NOT EXISTS "LAB_CULTURES" (
    "CULTURE_ID" SERIAL PRIMARY KEY,
    "CULTURE_NO" VARCHAR(50) NOT NULL,
    "PERSON_ID" INTEGER NOT NULL,
    "LAB_REQUEST_ID" INTEGER,
    "CULTURE_TYPE" VARCHAR(80) NOT NULL,
    "ORGANISM" VARCHAR(150),
    "COLONY_COUNT" VARCHAR(100),
    "GRAM_STAIN" VARCHAR(100),
    "STATUS" VARCHAR(40) NOT NULL DEFAULT 'Provisional',
    "SCIENTIST" VARCHAR(150),
    "REPORTED_AT" TIMESTAMP(3),
    "CREATED_BY_ID" INTEGER,
    "CREATED_BY" VARCHAR(100),
    "CREATED_DATE" TIMESTAMP(3),
    "UPDATED_BY_ID" INTEGER,
    "UPDATED_BY" VARCHAR(100),
    "UPDATED_DATE" TIMESTAMP(3),
    "DELETED_FLAG" VARCHAR(1) DEFAULT 'N',
    CONSTRAINT "LAB_CULTURES_PERSON_ID_fkey"
      FOREIGN KEY ("PERSON_ID") REFERENCES "PERSONS"("PERSON_ID") ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS "LAB_CULTURES_CULTURE_NO_key" ON "LAB_CULTURES"("CULTURE_NO");
CREATE INDEX IF NOT EXISTS "LAB_CULTURES_PERSON_ID_idx" ON "LAB_CULTURES"("PERSON_ID");
CREATE INDEX IF NOT EXISTS "LAB_CULTURES_STATUS_idx" ON "LAB_CULTURES"("STATUS");
CREATE INDEX IF NOT EXISTS "LAB_CULTURES_CULTURE_TYPE_idx" ON "LAB_CULTURES"("CULTURE_TYPE");
CREATE INDEX IF NOT EXISTS "LAB_CULTURES_CREATED_DATE_idx" ON "LAB_CULTURES"("CREATED_DATE");

CREATE TABLE IF NOT EXISTS "LAB_CULTURE_SENSITIVITIES" (
    "SENSITIVITY_ID" SERIAL PRIMARY KEY,
    "CULTURE_ID" INTEGER NOT NULL,
    "ANTIBIOTIC" VARCHAR(100) NOT NULL,
    "RESULT" VARCHAR(1) NOT NULL,
    CONSTRAINT "LAB_CULTURE_SENSITIVITIES_CULTURE_ID_fkey"
      FOREIGN KEY ("CULTURE_ID") REFERENCES "LAB_CULTURES"("CULTURE_ID") ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS "LAB_CULTURE_SENSITIVITIES_CULTURE_ID_ANTIBIOTIC_key"
  ON "LAB_CULTURE_SENSITIVITIES"("CULTURE_ID", "ANTIBIOTIC");
CREATE INDEX IF NOT EXISTS "LAB_CULTURE_SENSITIVITIES_CULTURE_ID_idx" ON "LAB_CULTURE_SENSITIVITIES"("CULTURE_ID");

CREATE TABLE IF NOT EXISTS "LAB_REPORT_SNAPSHOTS" (
    "REPORT_ID" SERIAL PRIMARY KEY,
    "REPORT_TYPE" VARCHAR(60) NOT NULL,
    "FROM_DATE" DATE NOT NULL,
    "TO_DATE" DATE NOT NULL,
    "TITLE" VARCHAR(255) NOT NULL,
    "PAYLOAD" JSONB NOT NULL DEFAULT '{}',
    "FILE_SIZE_LABEL" VARCHAR(40),
    "CREATED_BY_ID" INTEGER,
    "CREATED_BY" VARCHAR(100),
    "CREATED_DATE" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS "LAB_REPORT_SNAPSHOTS_REPORT_TYPE_idx" ON "LAB_REPORT_SNAPSHOTS"("REPORT_TYPE");
CREATE INDEX IF NOT EXISTS "LAB_REPORT_SNAPSHOTS_CREATED_DATE_idx" ON "LAB_REPORT_SNAPSHOTS"("CREATED_DATE");

CREATE TABLE IF NOT EXISTS "BLOOD_DONORS" (
    "DONOR_ID" SERIAL PRIMARY KEY,
    "DONOR_NO" VARCHAR(50) NOT NULL,
    "FULL_NAME" VARCHAR(200) NOT NULL,
    "PHONE" VARCHAR(40) NOT NULL,
    "ADDRESS" VARCHAR(255),
    "BLOOD_GROUP" VARCHAR(10),
    "NOTES" TEXT,
    "STATUS" VARCHAR(30) NOT NULL DEFAULT 'Active',
    "CREATED_BY_ID" INTEGER,
    "CREATED_BY" VARCHAR(100),
    "CREATED_DATE" TIMESTAMP(3),
    "UPDATED_BY_ID" INTEGER,
    "UPDATED_BY" VARCHAR(100),
    "UPDATED_DATE" TIMESTAMP(3),
    "DELETED_FLAG" VARCHAR(1) DEFAULT 'N'
);

CREATE UNIQUE INDEX IF NOT EXISTS "BLOOD_DONORS_DONOR_NO_key" ON "BLOOD_DONORS"("DONOR_NO");
CREATE INDEX IF NOT EXISTS "BLOOD_DONORS_PHONE_idx" ON "BLOOD_DONORS"("PHONE");
CREATE INDEX IF NOT EXISTS "BLOOD_DONORS_STATUS_idx" ON "BLOOD_DONORS"("STATUS");
CREATE INDEX IF NOT EXISTS "BLOOD_DONORS_FULL_NAME_idx" ON "BLOOD_DONORS"("FULL_NAME");

ALTER TABLE "BLOOD_UNITS" ADD COLUMN IF NOT EXISTS "DONOR_ID" INTEGER;
ALTER TABLE "BLOOD_UNITS" ADD COLUMN IF NOT EXISTS "DOCTOR_ID" INTEGER;
ALTER TABLE "BLOOD_UNITS" ADD COLUMN IF NOT EXISTS "DOCTOR_LABEL" VARCHAR(150);

DO $$ BEGIN
  ALTER TABLE "BLOOD_UNITS"
    ADD CONSTRAINT "BLOOD_UNITS_DONOR_ID_fkey"
    FOREIGN KEY ("DONOR_ID") REFERENCES "BLOOD_DONORS"("DONOR_ID")
    ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

CREATE INDEX IF NOT EXISTS "BLOOD_UNITS_DONOR_ID_idx" ON "BLOOD_UNITS"("DONOR_ID");
CREATE INDEX IF NOT EXISTS "BLOOD_UNITS_DOCTOR_ID_idx" ON "BLOOD_UNITS"("DOCTOR_ID");

ALTER TABLE "BLOOD_REQUESTS" ADD COLUMN IF NOT EXISTS "DOCTOR_ID" INTEGER;
CREATE INDEX IF NOT EXISTS "BLOOD_REQUESTS_DOCTOR_ID_idx" ON "BLOOD_REQUESTS"("DOCTOR_ID");
