-- AlterTable
ALTER TABLE "SERVICE_BOOKINGS" ADD COLUMN IF NOT EXISTS "CHECKED_IN_AT" TIMESTAMP(3);
ALTER TABLE "SERVICE_BOOKINGS" ADD COLUMN IF NOT EXISTS "CHECKED_IN_BY" VARCHAR(100);
ALTER TABLE "SERVICE_BOOKINGS" ADD COLUMN IF NOT EXISTS "PAYMENT_CHANNEL" VARCHAR(50);
ALTER TABLE "SERVICE_BOOKINGS" ADD COLUMN IF NOT EXISTS "PAYMENT_REF" VARCHAR(100);
ALTER TABLE "SERVICE_BOOKINGS" ADD COLUMN IF NOT EXISTS "PAID_AT" TIMESTAMP(3);
