-- Clinical referrals (doctor → Records/Nurse → department attend or admit)

CREATE TABLE IF NOT EXISTS "CLINICAL_REFERRALS" (
    "REFERRAL_ID" SERIAL NOT NULL,
    "REFERRAL_NO" VARCHAR(50) NOT NULL,
    "PERSON_ID" INTEGER NOT NULL,
    "ENCOUNTER_ID" INTEGER,
    "ADMISSION_ID" INTEGER,
    "REFERRAL_KIND" VARCHAR(30) NOT NULL,
    "CARE_SETTING" VARCHAR(30) NOT NULL DEFAULT 'Outpatient',
    "PRIORITY" VARCHAR(30) NOT NULL DEFAULT 'Routine',
    "FROM_DEPARTMENT" VARCHAR(100),
    "TO_DEPARTMENT" VARCHAR(100),
    "TO_DOCTOR_USER_ID" INTEGER,
    "TO_DOCTOR_LABEL" VARCHAR(150),
    "EXTERNAL_FACILITY" VARCHAR(255),
    "EXTERNAL_CONTACT" VARCHAR(150),
    "EXTERNAL_ADDRESS" VARCHAR(500),
    "REASON" TEXT NOT NULL,
    "PROVISIONAL_DIAGNOSIS" TEXT,
    "CLINICAL_SUMMARY" TEXT,
    "SPECIFIC_QUESTION" TEXT,
    "OUTCOME_NOTE" TEXT,
    "STATUS" VARCHAR(40) NOT NULL DEFAULT 'Submitted',
    "REQUESTED_BY_USER_ID" INTEGER,
    "ACKED_BY_USER_ID" INTEGER,
    "ACKED_AT" TIMESTAMP(3),
    "ROUTED_BY_USER_ID" INTEGER,
    "ROUTED_AT" TIMESTAMP(3),
    "ALLOCATED_BY_USER_ID" INTEGER,
    "ALLOCATED_AT" TIMESTAMP(3),
    "ALLOCATED_WARD_ID" INTEGER,
    "ALLOCATED_BED_ID" INTEGER,
    "ACCEPTED_BY_USER_ID" INTEGER,
    "ACCEPTED_AT" TIMESTAMP(3),
    "COMPLETED_BY_USER_ID" INTEGER,
    "COMPLETED_AT" TIMESTAMP(3),
    "REJECTION_REASON" TEXT,
    "RETURN_REASON" TEXT,
    "CREATED_BY_ID" INTEGER,
    "CREATED_BY" VARCHAR(100),
    "CREATED_DATE" TIMESTAMP(3),
    "UPDATED_BY_ID" INTEGER,
    "UPDATED_BY" VARCHAR(100),
    "UPDATED_DATE" TIMESTAMP(3),
    CONSTRAINT "CLINICAL_REFERRALS_pkey" PRIMARY KEY ("REFERRAL_ID")
);

CREATE UNIQUE INDEX IF NOT EXISTS "CLINICAL_REFERRALS_REFERRAL_NO_key" ON "CLINICAL_REFERRALS"("REFERRAL_NO");
CREATE INDEX IF NOT EXISTS "CLINICAL_REFERRALS_PERSON_ID_idx" ON "CLINICAL_REFERRALS"("PERSON_ID");
CREATE INDEX IF NOT EXISTS "CLINICAL_REFERRALS_STATUS_idx" ON "CLINICAL_REFERRALS"("STATUS");
CREATE INDEX IF NOT EXISTS "CLINICAL_REFERRALS_TO_DEPARTMENT_idx" ON "CLINICAL_REFERRALS"("TO_DEPARTMENT");
CREATE INDEX IF NOT EXISTS "CLINICAL_REFERRALS_REFERRAL_KIND_idx" ON "CLINICAL_REFERRALS"("REFERRAL_KIND");
CREATE INDEX IF NOT EXISTS "CLINICAL_REFERRALS_REQUESTED_BY_USER_ID_idx" ON "CLINICAL_REFERRALS"("REQUESTED_BY_USER_ID");
CREATE INDEX IF NOT EXISTS "CLINICAL_REFERRALS_CREATED_DATE_idx" ON "CLINICAL_REFERRALS"("CREATED_DATE");

DO $$ BEGIN
  ALTER TABLE "CLINICAL_REFERRALS" ADD CONSTRAINT "CLINICAL_REFERRALS_PERSON_ID_fkey"
    FOREIGN KEY ("PERSON_ID") REFERENCES "PERSONS"("PERSON_ID") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "CLINICAL_REFERRALS" ADD CONSTRAINT "CLINICAL_REFERRALS_ADMISSION_ID_fkey"
    FOREIGN KEY ("ADMISSION_ID") REFERENCES "ADMISSIONS"("ADMISSION_ID") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "CLINICAL_REFERRALS" ADD CONSTRAINT "CLINICAL_REFERRALS_ALLOCATED_WARD_ID_fkey"
    FOREIGN KEY ("ALLOCATED_WARD_ID") REFERENCES "WARDS"("WARD_ID") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "CLINICAL_REFERRALS" ADD CONSTRAINT "CLINICAL_REFERRALS_ALLOCATED_BED_ID_fkey"
    FOREIGN KEY ("ALLOCATED_BED_ID") REFERENCES "BEDS"("BED_ID") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "CLINICAL_REFERRALS" ADD CONSTRAINT "CLINICAL_REFERRALS_REQUESTED_BY_USER_ID_fkey"
    FOREIGN KEY ("REQUESTED_BY_USER_ID") REFERENCES "USERS"("USER_ID") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "CLINICAL_REFERRALS" ADD CONSTRAINT "CLINICAL_REFERRALS_TO_DOCTOR_USER_ID_fkey"
    FOREIGN KEY ("TO_DOCTOR_USER_ID") REFERENCES "USERS"("USER_ID") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "CLINICAL_REFERRAL_EVENTS" (
    "EVENT_ID" SERIAL NOT NULL,
    "REFERRAL_ID" INTEGER NOT NULL,
    "EVENT_TYPE" VARCHAR(50) NOT NULL,
    "ACTOR_USER_ID" INTEGER,
    "ACTOR_LABEL" VARCHAR(150),
    "NOTE" TEXT,
    "OLD_STATUS" VARCHAR(40),
    "NEW_STATUS" VARCHAR(40),
    "CREATED_DATE" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "CLINICAL_REFERRAL_EVENTS_pkey" PRIMARY KEY ("EVENT_ID")
);

CREATE INDEX IF NOT EXISTS "CLINICAL_REFERRAL_EVENTS_REFERRAL_ID_idx" ON "CLINICAL_REFERRAL_EVENTS"("REFERRAL_ID");
CREATE INDEX IF NOT EXISTS "CLINICAL_REFERRAL_EVENTS_CREATED_DATE_idx" ON "CLINICAL_REFERRAL_EVENTS"("CREATED_DATE");

DO $$ BEGIN
  ALTER TABLE "CLINICAL_REFERRAL_EVENTS" ADD CONSTRAINT "CLINICAL_REFERRAL_EVENTS_REFERRAL_ID_fkey"
    FOREIGN KEY ("REFERRAL_ID") REFERENCES "CLINICAL_REFERRALS"("REFERRAL_ID") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
