-- Clinical documentation notes + immutable version snapshots

CREATE TABLE IF NOT EXISTS "CLINICAL_NOTES" (
    "CLINICAL_NOTE_ID" SERIAL NOT NULL,
    "NOTE_NO" VARCHAR(50) NOT NULL,
    "PERSON_ID" INTEGER NOT NULL,
    "ENCOUNTER_ID" INTEGER,
    "AUTHOR_ID" INTEGER NOT NULL,
    "NOTE_TYPE" VARCHAR(100) NOT NULL,
    "CLINIC" VARCHAR(100),
    "STATUS" VARCHAR(50) NOT NULL DEFAULT 'Draft',
    "PRIORITY" VARCHAR(50) NOT NULL DEFAULT 'Routine',
    "FIELDS" JSONB NOT NULL DEFAULT '{}',
    "VERSION" INTEGER NOT NULL DEFAULT 1,
    "RETURN_REASON" TEXT,
    "SIGNED_AT" TIMESTAMP(3),
    "SIGNED_BY_ID" INTEGER,
    "SIGNED_BY" VARCHAR(100),
    "SUBMITTED_AT" TIMESTAMP(3),
    "VOIDED_AT" TIMESTAMP(3),
    "CREATED_BY_ID" INTEGER,
    "CREATED_BY" VARCHAR(100),
    "CREATED_DATE" TIMESTAMP(3),
    "UPDATED_BY_ID" INTEGER,
    "UPDATED_BY" VARCHAR(100),
    "UPDATED_DATE" TIMESTAMP(3),

    CONSTRAINT "CLINICAL_NOTES_pkey" PRIMARY KEY ("CLINICAL_NOTE_ID")
);

CREATE UNIQUE INDEX IF NOT EXISTS "CLINICAL_NOTES_NOTE_NO_key" ON "CLINICAL_NOTES"("NOTE_NO");
CREATE INDEX IF NOT EXISTS "CLINICAL_NOTES_PERSON_ID_idx" ON "CLINICAL_NOTES"("PERSON_ID");
CREATE INDEX IF NOT EXISTS "CLINICAL_NOTES_AUTHOR_ID_idx" ON "CLINICAL_NOTES"("AUTHOR_ID");
CREATE INDEX IF NOT EXISTS "CLINICAL_NOTES_STATUS_idx" ON "CLINICAL_NOTES"("STATUS");
CREATE INDEX IF NOT EXISTS "CLINICAL_NOTES_NOTE_TYPE_idx" ON "CLINICAL_NOTES"("NOTE_TYPE");
CREATE INDEX IF NOT EXISTS "CLINICAL_NOTES_CREATED_DATE_idx" ON "CLINICAL_NOTES"("CREATED_DATE");
CREATE INDEX IF NOT EXISTS "CLINICAL_NOTES_ENCOUNTER_ID_idx" ON "CLINICAL_NOTES"("ENCOUNTER_ID");

CREATE TABLE IF NOT EXISTS "CLINICAL_NOTE_VERSIONS" (
    "VERSION_ID" SERIAL NOT NULL,
    "CLINICAL_NOTE_ID" INTEGER NOT NULL,
    "VERSION" INTEGER NOT NULL,
    "FIELDS" JSONB NOT NULL,
    "STATUS" VARCHAR(50) NOT NULL,
    "CHANGE_SUMMARY" VARCHAR(500),
    "CREATED_BY_ID" INTEGER,
    "CREATED_BY" VARCHAR(100),
    "CREATED_DATE" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "CLINICAL_NOTE_VERSIONS_pkey" PRIMARY KEY ("VERSION_ID")
);

CREATE UNIQUE INDEX IF NOT EXISTS "CLINICAL_NOTE_VERSIONS_CLINICAL_NOTE_ID_VERSION_key"
  ON "CLINICAL_NOTE_VERSIONS"("CLINICAL_NOTE_ID", "VERSION");
CREATE INDEX IF NOT EXISTS "CLINICAL_NOTE_VERSIONS_CLINICAL_NOTE_ID_idx"
  ON "CLINICAL_NOTE_VERSIONS"("CLINICAL_NOTE_ID");

DO $$ BEGIN
  ALTER TABLE "CLINICAL_NOTES" ADD CONSTRAINT "CLINICAL_NOTES_PERSON_ID_fkey"
    FOREIGN KEY ("PERSON_ID") REFERENCES "PERSONS"("PERSON_ID") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "CLINICAL_NOTES" ADD CONSTRAINT "CLINICAL_NOTES_ENCOUNTER_ID_fkey"
    FOREIGN KEY ("ENCOUNTER_ID") REFERENCES "ENCOUNTERS"("ENCOUNTER_ID") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "CLINICAL_NOTES" ADD CONSTRAINT "CLINICAL_NOTES_AUTHOR_ID_fkey"
    FOREIGN KEY ("AUTHOR_ID") REFERENCES "USERS"("USER_ID") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "CLINICAL_NOTE_VERSIONS" ADD CONSTRAINT "CLINICAL_NOTE_VERSIONS_CLINICAL_NOTE_ID_fkey"
    FOREIGN KEY ("CLINICAL_NOTE_ID") REFERENCES "CLINICAL_NOTES"("CLINICAL_NOTE_ID") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
