-- Doctor follow-up appointments (scheduled from consultation complete / workspace)

CREATE TABLE IF NOT EXISTS "FOLLOW_UPS" (
    "FOLLOW_UP_ID" SERIAL NOT NULL,
    "PERSON_ID" INTEGER NOT NULL,
    "ENCOUNTER_ID" INTEGER,
    "DOCTOR_ID" INTEGER NOT NULL,
    "CLINIC" VARCHAR(100),
    "SCHEDULED_DATE" DATE NOT NULL,
    "SCHEDULED_TIME" VARCHAR(20),
    "PRIORITY" VARCHAR(50) NOT NULL DEFAULT 'Routine',
    "STATUS" VARCHAR(50) NOT NULL DEFAULT 'Scheduled',
    "PREV_DX" VARCHAR(500),
    "REASON" TEXT,
    "REMINDER" VARCHAR(50),
    "CREATED_BY_ID" INTEGER,
    "CREATED_BY" VARCHAR(100),
    "CREATED_DATE" TIMESTAMP(3),
    "UPDATED_BY_ID" INTEGER,
    "UPDATED_BY" VARCHAR(100),
    "UPDATED_DATE" TIMESTAMP(3),

    CONSTRAINT "FOLLOW_UPS_pkey" PRIMARY KEY ("FOLLOW_UP_ID")
);

CREATE INDEX IF NOT EXISTS "FOLLOW_UPS_PERSON_ID_idx" ON "FOLLOW_UPS"("PERSON_ID");
CREATE INDEX IF NOT EXISTS "FOLLOW_UPS_DOCTOR_ID_idx" ON "FOLLOW_UPS"("DOCTOR_ID");
CREATE INDEX IF NOT EXISTS "FOLLOW_UPS_SCHEDULED_DATE_idx" ON "FOLLOW_UPS"("SCHEDULED_DATE");
CREATE INDEX IF NOT EXISTS "FOLLOW_UPS_STATUS_idx" ON "FOLLOW_UPS"("STATUS");
CREATE INDEX IF NOT EXISTS "FOLLOW_UPS_ENCOUNTER_ID_idx" ON "FOLLOW_UPS"("ENCOUNTER_ID");

DO $$ BEGIN
  ALTER TABLE "FOLLOW_UPS" ADD CONSTRAINT "FOLLOW_UPS_PERSON_ID_fkey"
    FOREIGN KEY ("PERSON_ID") REFERENCES "PERSONS"("PERSON_ID") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "FOLLOW_UPS" ADD CONSTRAINT "FOLLOW_UPS_ENCOUNTER_ID_fkey"
    FOREIGN KEY ("ENCOUNTER_ID") REFERENCES "ENCOUNTERS"("ENCOUNTER_ID") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "FOLLOW_UPS" ADD CONSTRAINT "FOLLOW_UPS_DOCTOR_ID_fkey"
    FOREIGN KEY ("DOCTOR_ID") REFERENCES "USERS"("USER_ID") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
