-- Admission billing Phase 1: ward rates, package catalogue, unpaid bills.

-- 1) Ward pricing columns
ALTER TABLE "WARDS" ADD COLUMN IF NOT EXISTS "WARD_CLASS" VARCHAR(40);
ALTER TABLE "WARDS" ADD COLUMN IF NOT EXISTS "DAILY_BED_RATE" DECIMAL(14,2) NOT NULL DEFAULT 0;
ALTER TABLE "WARDS" ADD COLUMN IF NOT EXISTS "ADMISSION_DEPOSIT_DEFAULT" DECIMAL(14,2) NOT NULL DEFAULT 0;

UPDATE "WARDS" SET "WARD_CLASS" = 'General', "DAILY_BED_RATE" = 5000, "ADMISSION_DEPOSIT_DEFAULT" = 50000
WHERE "CODE" = 'W1C' AND ("DAILY_BED_RATE" IS NULL OR "DAILY_BED_RATE" = 0);

UPDATE "WARDS" SET "WARD_CLASS" = 'ICU', "DAILY_BED_RATE" = 80000, "ADMISSION_DEPOSIT_DEFAULT" = 100000
WHERE "CODE" = 'ICU' AND ("DAILY_BED_RATE" IS NULL OR "DAILY_BED_RATE" = 0);

-- Extra wards for testing (idempotent)
INSERT INTO "WARDS" ("CODE", "NAME", "WARD_TYPE", "WARD_CLASS", "DAILY_BED_RATE", "ADMISSION_DEPOSIT_DEFAULT", "STATUS", "CREATED_BY", "CREATED_DATE")
VALUES
  ('GEN', 'General Ward', 'General', 'General', 5000, 50000, 'Active', 'SYSTEM', NOW()),
  ('PRIV', 'Private Ward', 'General', 'Private', 40000, 75000, 'Active', 'SYSTEM', NOW()),
  ('VIP', 'VIP Ward', 'General', 'VIP', 80000, 100000, 'Active', 'SYSTEM', NOW()),
  ('SEMI', 'Semi Private Ward', 'General', 'SemiPrivate', 20000, 60000, 'Active', 'SYSTEM', NOW())
ON CONFLICT ("CODE") DO NOTHING;

-- Beds for new wards if missing
INSERT INTO "BEDS" ("WARD_ID", "LABEL", "STATUS", "CREATED_BY", "CREATED_DATE")
SELECT w."WARD_ID", b.label, 'AVAILABLE', 'SYSTEM', NOW()
FROM "WARDS" w
CROSS JOIN (VALUES ('01'), ('02'), ('03'), ('04')) AS b(label)
WHERE w."CODE" IN ('GEN', 'PRIV', 'VIP', 'SEMI')
  AND NOT EXISTS (
    SELECT 1 FROM "BEDS" x WHERE x."WARD_ID" = w."WARD_ID" AND x."LABEL" = b.label
  );

-- 2) Admission billing catalogue
CREATE TABLE IF NOT EXISTS "ADMISSION_BILLING_ITEMS" (
    "ITEM_ID" SERIAL NOT NULL,
    "ITEM_CODE" VARCHAR(40) NOT NULL,
    "NAME" VARCHAR(150) NOT NULL,
    "CATEGORY" VARCHAR(40) NOT NULL,
    "UNIT_PRICE" DECIMAL(14,2) NOT NULL,
    "STATUS" VARCHAR(30) NOT NULL DEFAULT 'Active',
    "CREATED_BY" VARCHAR(100),
    "CREATED_DATE" TIMESTAMP(3),
    "UPDATED_BY" VARCHAR(100),
    "UPDATED_DATE" TIMESTAMP(3),
    CONSTRAINT "ADMISSION_BILLING_ITEMS_pkey" PRIMARY KEY ("ITEM_ID")
);

CREATE UNIQUE INDEX IF NOT EXISTS "ADMISSION_BILLING_ITEMS_ITEM_CODE_key" ON "ADMISSION_BILLING_ITEMS"("ITEM_CODE");
CREATE INDEX IF NOT EXISTS "ADMISSION_BILLING_ITEMS_STATUS_idx" ON "ADMISSION_BILLING_ITEMS"("STATUS");
CREATE INDEX IF NOT EXISTS "ADMISSION_BILLING_ITEMS_CATEGORY_idx" ON "ADMISSION_BILLING_ITEMS"("CATEGORY");

INSERT INTO "ADMISSION_BILLING_ITEMS" ("ITEM_CODE", "NAME", "CATEGORY", "UNIT_PRICE", "STATUS", "CREATED_BY", "CREATED_DATE")
VALUES
  ('ADM-FEE', 'Admission Fee', 'AdmissionFee', 5000, 'Active', 'SYSTEM', NOW()),
  ('ADM-NURS', 'Nursing Assessment', 'Nursing', 3000, 'Active', 'SYSTEM', NOW()),
  ('ADM-FOLD', 'Patient Folder', 'Folder', 1000, 'Active', 'SYSTEM', NOW()),
  ('ADM-CONS', 'Initial Consumables', 'Consumables', 2500, 'Active', 'SYSTEM', NOW()),
  ('ADM-DEP', 'Emergency Deposit', 'Deposit', 50000, 'Active', 'SYSTEM', NOW())
ON CONFLICT ("ITEM_CODE") DO NOTHING;

-- 3) Admission bills
CREATE TABLE IF NOT EXISTS "ADMISSION_BILLS" (
    "ADMISSION_BILL_ID" SERIAL NOT NULL,
    "BILL_NO" VARCHAR(50) NOT NULL,
    "PERSON_ID" INTEGER NOT NULL,
    "ADMISSION_ID" INTEGER,
    "ADMISSION_REQUEST_ID" INTEGER,
    "TOTAL_AMOUNT" DECIMAL(14,2) NOT NULL DEFAULT 0,
    "PAYMENT_STATUS" VARCHAR(30) NOT NULL DEFAULT 'Unpaid',
    "PAYMENT_CHANNEL" VARCHAR(50),
    "PAYMENT_REF" VARCHAR(100),
    "PAID_AT" TIMESTAMP(3),
    "PAID_BY" VARCHAR(100),
    "CREATED_BY_ID" INTEGER,
    "UPDATED_BY_ID" INTEGER,
    "CREATED_BY" VARCHAR(100),
    "CREATED_DATE" TIMESTAMP(3),
    "UPDATED_BY" VARCHAR(100),
    "UPDATED_DATE" TIMESTAMP(3),
    CONSTRAINT "ADMISSION_BILLS_pkey" PRIMARY KEY ("ADMISSION_BILL_ID")
);

CREATE UNIQUE INDEX IF NOT EXISTS "ADMISSION_BILLS_BILL_NO_key" ON "ADMISSION_BILLS"("BILL_NO");
CREATE INDEX IF NOT EXISTS "ADMISSION_BILLS_PERSON_ID_idx" ON "ADMISSION_BILLS"("PERSON_ID");
CREATE INDEX IF NOT EXISTS "ADMISSION_BILLS_ADMISSION_ID_idx" ON "ADMISSION_BILLS"("ADMISSION_ID");
CREATE INDEX IF NOT EXISTS "ADMISSION_BILLS_PAYMENT_STATUS_idx" ON "ADMISSION_BILLS"("PAYMENT_STATUS");
CREATE INDEX IF NOT EXISTS "ADMISSION_BILLS_CREATED_DATE_idx" ON "ADMISSION_BILLS"("CREATED_DATE");

DO $$ BEGIN
  ALTER TABLE "ADMISSION_BILLS" ADD CONSTRAINT "ADMISSION_BILLS_PERSON_ID_fkey"
    FOREIGN KEY ("PERSON_ID") REFERENCES "PERSONS"("PERSON_ID") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "ADMISSION_BILLS" ADD CONSTRAINT "ADMISSION_BILLS_ADMISSION_ID_fkey"
    FOREIGN KEY ("ADMISSION_ID") REFERENCES "ADMISSIONS"("ADMISSION_ID") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "ADMISSION_BILLS" ADD CONSTRAINT "ADMISSION_BILLS_ADMISSION_REQUEST_ID_fkey"
    FOREIGN KEY ("ADMISSION_REQUEST_ID") REFERENCES "ADMISSION_REQUESTS"("ADMISSION_REQUEST_ID") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS "ADMISSION_BILL_LINES" (
    "LINE_ID" SERIAL NOT NULL,
    "ADMISSION_BILL_ID" INTEGER NOT NULL,
    "ITEM_CODE" VARCHAR(40) NOT NULL,
    "DESCRIPTION" VARCHAR(255) NOT NULL,
    "QTY" INTEGER NOT NULL DEFAULT 1,
    "UNIT_PRICE" DECIMAL(14,2) NOT NULL,
    "LINE_TOTAL" DECIMAL(14,2) NOT NULL,
    CONSTRAINT "ADMISSION_BILL_LINES_pkey" PRIMARY KEY ("LINE_ID")
);

CREATE INDEX IF NOT EXISTS "ADMISSION_BILL_LINES_ADMISSION_BILL_ID_idx" ON "ADMISSION_BILL_LINES"("ADMISSION_BILL_ID");

DO $$ BEGIN
  ALTER TABLE "ADMISSION_BILL_LINES" ADD CONSTRAINT "ADMISSION_BILL_LINES_ADMISSION_BILL_ID_fkey"
    FOREIGN KEY ("ADMISSION_BILL_ID") REFERENCES "ADMISSION_BILLS"("ADMISSION_BILL_ID") ON DELETE CASCADE ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
