-- Doctor emergency override sessions + critical alerts

CREATE TABLE IF NOT EXISTS "EMERGENCY_OVERRIDE_SESSIONS" (
    "SESSION_ID" SERIAL PRIMARY KEY,
    "OVERRIDE_NO" VARCHAR(50) NOT NULL,
    "PERSON_ID" INTEGER NOT NULL,
    "ADMISSION_ID" INTEGER,
    "REASON" VARCHAR(120) NOT NULL,
    "JUSTIFICATION" TEXT NOT NULL,
    "SEVERITY" INTEGER NOT NULL DEFAULT 3,
    "DURATION_MINUTES" INTEGER NOT NULL DEFAULT 60,
    "LOCATION" VARCHAR(150),
    "CONSULTANT" VARCHAR(150),
    "STATUS" VARCHAR(30) NOT NULL DEFAULT 'Active',
    "ACTIONS_JSON" TEXT,
    "STARTED_AT" TIMESTAMP(3) NOT NULL,
    "ENDS_AT" TIMESTAMP(3),
    "ENDED_AT" TIMESTAMP(3),
    "CREATED_BY_ID" INTEGER,
    "CREATED_BY" VARCHAR(100),
    "CREATED_DATE" TIMESTAMP(3),
    "UPDATED_BY_ID" INTEGER,
    "UPDATED_BY" VARCHAR(100),
    "UPDATED_DATE" TIMESTAMP(3),
    "DELETED_FLAG" VARCHAR(1) DEFAULT 'N'
);

CREATE UNIQUE INDEX IF NOT EXISTS "EMERGENCY_OVERRIDE_SESSIONS_OVERRIDE_NO_key"
  ON "EMERGENCY_OVERRIDE_SESSIONS"("OVERRIDE_NO");
CREATE INDEX IF NOT EXISTS "EMERGENCY_OVERRIDE_SESSIONS_PERSON_ID_idx"
  ON "EMERGENCY_OVERRIDE_SESSIONS"("PERSON_ID");
CREATE INDEX IF NOT EXISTS "EMERGENCY_OVERRIDE_SESSIONS_STATUS_idx"
  ON "EMERGENCY_OVERRIDE_SESSIONS"("STATUS");
CREATE INDEX IF NOT EXISTS "EMERGENCY_OVERRIDE_SESSIONS_STARTED_AT_idx"
  ON "EMERGENCY_OVERRIDE_SESSIONS"("STARTED_AT");
CREATE INDEX IF NOT EXISTS "EMERGENCY_OVERRIDE_SESSIONS_CREATED_BY_ID_idx"
  ON "EMERGENCY_OVERRIDE_SESSIONS"("CREATED_BY_ID");

CREATE TABLE IF NOT EXISTS "EMERGENCY_CRITICAL_ALERTS" (
    "ALERT_ID" SERIAL PRIMARY KEY,
    "PERSON_ID" INTEGER,
    "ALERT_TYPE" VARCHAR(80) NOT NULL,
    "MESSAGE" TEXT NOT NULL,
    "SEVERITY" VARCHAR(30) NOT NULL DEFAULT 'High',
    "ACKNOWLEDGED_AT" TIMESTAMP(3),
    "ACKNOWLEDGED_BY_ID" INTEGER,
    "ACKNOWLEDGED_BY" VARCHAR(100),
    "CREATED_BY_ID" INTEGER,
    "CREATED_BY" VARCHAR(100),
    "CREATED_DATE" TIMESTAMP(3),
    "DELETED_FLAG" VARCHAR(1) DEFAULT 'N'
);

CREATE INDEX IF NOT EXISTS "EMERGENCY_CRITICAL_ALERTS_PERSON_ID_idx"
  ON "EMERGENCY_CRITICAL_ALERTS"("PERSON_ID");
CREATE INDEX IF NOT EXISTS "EMERGENCY_CRITICAL_ALERTS_SEVERITY_idx"
  ON "EMERGENCY_CRITICAL_ALERTS"("SEVERITY");
CREATE INDEX IF NOT EXISTS "EMERGENCY_CRITICAL_ALERTS_CREATED_DATE_idx"
  ON "EMERGENCY_CRITICAL_ALERTS"("CREATED_DATE");
CREATE INDEX IF NOT EXISTS "EMERGENCY_CRITICAL_ALERTS_ACKNOWLEDGED_AT_idx"
  ON "EMERGENCY_CRITICAL_ALERTS"("ACKNOWLEDGED_AT");
