-- Patient Transfer Management + in-app Notifications

CREATE TABLE IF NOT EXISTS "PATIENT_TRANSFERS" (
    "TRANSFER_ID" SERIAL NOT NULL,
    "TRANSFER_NO" VARCHAR(50) NOT NULL,
    "PERSON_ID" INTEGER NOT NULL,
    "ADMISSION_ID" INTEGER,
    "TRANSFER_TYPE" VARCHAR(40) NOT NULL,
    "PRIORITY" VARCHAR(30) NOT NULL DEFAULT 'Routine',
    "FROM_WARD_ID" INTEGER,
    "TO_WARD_ID" INTEGER,
    "TO_WARD_PREFERENCE" VARCHAR(150),
    "DESTINATION_LABEL" VARCHAR(150),
    "ALLOCATED_BED_ID" INTEGER,
    "REASON" TEXT NOT NULL,
    "CLINICAL_NOTES" TEXT,
    "HANDOVER_NOTES" TEXT,
    "STATUS" VARCHAR(40) NOT NULL DEFAULT 'Submitted',
    "REQUESTED_BY_USER_ID" INTEGER,
    "PREPARED_BY_USER_ID" INTEGER,
    "PREPARED_AT" TIMESTAMP(3),
    "ALLOCATED_BY_USER_ID" INTEGER,
    "ALLOCATED_AT" TIMESTAMP(3),
    "ACCEPTED_BY_USER_ID" INTEGER,
    "ACCEPTED_AT" TIMESTAMP(3),
    "DEPARTED_BY_USER_ID" INTEGER,
    "DEPARTED_AT" TIMESTAMP(3),
    "RECEIVED_BY_USER_ID" INTEGER,
    "RECEIVED_AT" TIMESTAMP(3),
    "REJECTION_REASON" TEXT,
    "EXTERNAL_FACILITY" VARCHAR(255),
    "CREATED_BY_ID" INTEGER,
    "CREATED_BY" VARCHAR(100),
    "CREATED_DATE" TIMESTAMP(3),
    "UPDATED_BY_ID" INTEGER,
    "UPDATED_BY" VARCHAR(100),
    "UPDATED_DATE" TIMESTAMP(3),
    CONSTRAINT "PATIENT_TRANSFERS_pkey" PRIMARY KEY ("TRANSFER_ID")
);

CREATE UNIQUE INDEX IF NOT EXISTS "PATIENT_TRANSFERS_TRANSFER_NO_key" ON "PATIENT_TRANSFERS"("TRANSFER_NO");
CREATE INDEX IF NOT EXISTS "PATIENT_TRANSFERS_PERSON_ID_idx" ON "PATIENT_TRANSFERS"("PERSON_ID");
CREATE INDEX IF NOT EXISTS "PATIENT_TRANSFERS_ADMISSION_ID_idx" ON "PATIENT_TRANSFERS"("ADMISSION_ID");
CREATE INDEX IF NOT EXISTS "PATIENT_TRANSFERS_STATUS_idx" ON "PATIENT_TRANSFERS"("STATUS");
CREATE INDEX IF NOT EXISTS "PATIENT_TRANSFERS_FROM_WARD_ID_idx" ON "PATIENT_TRANSFERS"("FROM_WARD_ID");
CREATE INDEX IF NOT EXISTS "PATIENT_TRANSFERS_TO_WARD_ID_idx" ON "PATIENT_TRANSFERS"("TO_WARD_ID");
CREATE INDEX IF NOT EXISTS "PATIENT_TRANSFERS_REQUESTED_BY_USER_ID_idx" ON "PATIENT_TRANSFERS"("REQUESTED_BY_USER_ID");
CREATE INDEX IF NOT EXISTS "PATIENT_TRANSFERS_CREATED_DATE_idx" ON "PATIENT_TRANSFERS"("CREATED_DATE");

DO $$ BEGIN
  ALTER TABLE "PATIENT_TRANSFERS" ADD CONSTRAINT "PATIENT_TRANSFERS_PERSON_ID_fkey"
    FOREIGN KEY ("PERSON_ID") REFERENCES "PERSONS"("PERSON_ID") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "PATIENT_TRANSFERS" ADD CONSTRAINT "PATIENT_TRANSFERS_ADMISSION_ID_fkey"
    FOREIGN KEY ("ADMISSION_ID") REFERENCES "ADMISSIONS"("ADMISSION_ID") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "PATIENT_TRANSFERS" ADD CONSTRAINT "PATIENT_TRANSFERS_FROM_WARD_ID_fkey"
    FOREIGN KEY ("FROM_WARD_ID") REFERENCES "WARDS"("WARD_ID") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "PATIENT_TRANSFERS" ADD CONSTRAINT "PATIENT_TRANSFERS_TO_WARD_ID_fkey"
    FOREIGN KEY ("TO_WARD_ID") REFERENCES "WARDS"("WARD_ID") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "PATIENT_TRANSFERS" ADD CONSTRAINT "PATIENT_TRANSFERS_ALLOCATED_BED_ID_fkey"
    FOREIGN KEY ("ALLOCATED_BED_ID") REFERENCES "BEDS"("BED_ID") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "PATIENT_TRANSFERS" ADD CONSTRAINT "PATIENT_TRANSFERS_REQUESTED_BY_USER_ID_fkey"
    FOREIGN KEY ("REQUESTED_BY_USER_ID") REFERENCES "USERS"("USER_ID") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "PATIENT_TRANSFER_EVENTS" (
    "EVENT_ID" SERIAL NOT NULL,
    "TRANSFER_ID" INTEGER NOT NULL,
    "EVENT_TYPE" VARCHAR(50) NOT NULL,
    "ACTOR_USER_ID" INTEGER,
    "ACTOR_LABEL" VARCHAR(150),
    "NOTE" TEXT,
    "OLD_STATUS" VARCHAR(40),
    "NEW_STATUS" VARCHAR(40),
    "CREATED_DATE" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "PATIENT_TRANSFER_EVENTS_pkey" PRIMARY KEY ("EVENT_ID")
);

CREATE INDEX IF NOT EXISTS "PATIENT_TRANSFER_EVENTS_TRANSFER_ID_idx" ON "PATIENT_TRANSFER_EVENTS"("TRANSFER_ID");
CREATE INDEX IF NOT EXISTS "PATIENT_TRANSFER_EVENTS_CREATED_DATE_idx" ON "PATIENT_TRANSFER_EVENTS"("CREATED_DATE");

DO $$ BEGIN
  ALTER TABLE "PATIENT_TRANSFER_EVENTS" ADD CONSTRAINT "PATIENT_TRANSFER_EVENTS_TRANSFER_ID_fkey"
    FOREIGN KEY ("TRANSFER_ID") REFERENCES "PATIENT_TRANSFERS"("TRANSFER_ID") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "NOTIFICATIONS" (
    "NOTIFICATION_ID" SERIAL NOT NULL,
    "USER_ID" INTEGER NOT NULL,
    "ROLE_HINT" VARCHAR(50),
    "TYPE" VARCHAR(60) NOT NULL,
    "TITLE" VARCHAR(255) NOT NULL,
    "BODY" TEXT,
    "LINK_PATH" VARCHAR(255),
    "ENTITY" VARCHAR(80),
    "ENTITY_ID" INTEGER,
    "PERSON_ID" INTEGER,
    "IS_READ" BOOLEAN NOT NULL DEFAULT false,
    "ACKNOWLEDGED_AT" TIMESTAMP(3),
    "CREATED_DATE" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "NOTIFICATIONS_pkey" PRIMARY KEY ("NOTIFICATION_ID")
);

CREATE INDEX IF NOT EXISTS "NOTIFICATIONS_USER_ID_IS_READ_CREATED_DATE_idx"
  ON "NOTIFICATIONS"("USER_ID", "IS_READ", "CREATED_DATE");
CREATE INDEX IF NOT EXISTS "NOTIFICATIONS_TYPE_idx" ON "NOTIFICATIONS"("TYPE");
CREATE INDEX IF NOT EXISTS "NOTIFICATIONS_PERSON_ID_idx" ON "NOTIFICATIONS"("PERSON_ID");

DO $$ BEGIN
  ALTER TABLE "NOTIFICATIONS" ADD CONSTRAINT "NOTIFICATIONS_USER_ID_fkey"
    FOREIGN KEY ("USER_ID") REFERENCES "USERS"("USER_ID") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
