-- Align legacy WARDS/BEDS (init schema) to inpatient Prisma model, then seed standard testing inventory.
-- Root cause of empty Records admit dropdowns: CREATE TABLE IF NOT EXISTS skipped when legacy
-- WARDS/BEDS already existed (WARD_NAME / WARDS_ID / BED_NO / AVAILABILITY), so CODE/NAME/WARD_ID/LABEL/STATUS were missing.

-- ─── WARDS: ensure inpatient columns ─────────────────────────────────────────
ALTER TABLE "WARDS" ADD COLUMN IF NOT EXISTS "CODE" VARCHAR(50);
ALTER TABLE "WARDS" ADD COLUMN IF NOT EXISTS "NAME" VARCHAR(150);
ALTER TABLE "WARDS" ADD COLUMN IF NOT EXISTS "WARD_TYPE" VARCHAR(50);
ALTER TABLE "WARDS" ADD COLUMN IF NOT EXISTS "WARD_CLASS" VARCHAR(40);
ALTER TABLE "WARDS" ADD COLUMN IF NOT EXISTS "GENDER" VARCHAR(20);
ALTER TABLE "WARDS" ADD COLUMN IF NOT EXISTS "DAILY_BED_RATE" DECIMAL(14,2) NOT NULL DEFAULT 0;
ALTER TABLE "WARDS" ADD COLUMN IF NOT EXISTS "ADMISSION_DEPOSIT_DEFAULT" DECIMAL(14,2) NOT NULL DEFAULT 0;
ALTER TABLE "WARDS" ADD COLUMN IF NOT EXISTS "STATUS" VARCHAR(30);
ALTER TABLE "WARDS" ADD COLUMN IF NOT EXISTS "CREATED_BY" VARCHAR(100);
ALTER TABLE "WARDS" ADD COLUMN IF NOT EXISTS "CREATED_DATE" TIMESTAMP(3);
ALTER TABLE "WARDS" ADD COLUMN IF NOT EXISTS "UPDATED_BY" VARCHAR(100);
ALTER TABLE "WARDS" ADD COLUMN IF NOT EXISTS "UPDATED_DATE" TIMESTAMP(3);

-- Backfill NAME from legacy WARD_NAME when present
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'WARDS' AND column_name = 'WARD_NAME'
  ) THEN
    EXECUTE 'UPDATE "WARDS" SET "NAME" = COALESCE(NULLIF(TRIM("NAME"), ''''), NULLIF(TRIM("WARD_NAME"), ''''), ''Ward '' || "WARD_ID"::text) WHERE "NAME" IS NULL OR TRIM("NAME") = ''''';
  ELSE
    UPDATE "WARDS"
    SET "NAME" = COALESCE(NULLIF(TRIM("NAME"), ''), 'Ward ' || "WARD_ID"::text)
    WHERE "NAME" IS NULL OR TRIM("NAME") = '';
  END IF;
END $$;

-- Backfill CODE if empty
UPDATE "WARDS"
SET "CODE" = COALESCE(NULLIF(TRIM("CODE"), ''), 'W' || LPAD("WARD_ID"::text, 4, '0'))
WHERE "CODE" IS NULL OR TRIM("CODE") = '';

UPDATE "WARDS" SET "STATUS" = COALESCE(NULLIF(TRIM("STATUS"), ''), 'Active');
UPDATE "WARDS" SET "GENDER" = COALESCE(NULLIF(TRIM("GENDER"), ''), 'Mixed');
UPDATE "WARDS" SET "CREATED_DATE" = COALESCE("CREATED_DATE", NOW());
UPDATE "WARDS" SET "CREATED_BY" = COALESCE("CREATED_BY", 'SYSTEM');

ALTER TABLE "WARDS" ALTER COLUMN "CODE" SET NOT NULL;
ALTER TABLE "WARDS" ALTER COLUMN "NAME" SET NOT NULL;
ALTER TABLE "WARDS" ALTER COLUMN "STATUS" SET NOT NULL;
ALTER TABLE "WARDS" ALTER COLUMN "STATUS" SET DEFAULT 'Active';
ALTER TABLE "WARDS" ALTER COLUMN "GENDER" SET NOT NULL;
ALTER TABLE "WARDS" ALTER COLUMN "GENDER" SET DEFAULT 'Mixed';

CREATE UNIQUE INDEX IF NOT EXISTS "WARDS_CODE_key" ON "WARDS"("CODE");
CREATE INDEX IF NOT EXISTS "WARDS_GENDER_idx" ON "WARDS"("GENDER");
CREATE INDEX IF NOT EXISTS "WARDS_STATUS_idx" ON "WARDS"("STATUS");

-- ─── BEDS: ensure inpatient columns ──────────────────────────────────────────
ALTER TABLE "BEDS" ADD COLUMN IF NOT EXISTS "WARD_ID" INTEGER;
ALTER TABLE "BEDS" ADD COLUMN IF NOT EXISTS "LABEL" VARCHAR(50);
ALTER TABLE "BEDS" ADD COLUMN IF NOT EXISTS "STATUS" VARCHAR(30);
ALTER TABLE "BEDS" ADD COLUMN IF NOT EXISTS "CREATED_BY" VARCHAR(100);
ALTER TABLE "BEDS" ADD COLUMN IF NOT EXISTS "CREATED_DATE" TIMESTAMP(3);
ALTER TABLE "BEDS" ADD COLUMN IF NOT EXISTS "UPDATED_BY" VARCHAR(100);
ALTER TABLE "BEDS" ADD COLUMN IF NOT EXISTS "UPDATED_DATE" TIMESTAMP(3);

-- Backfill WARD_ID from legacy WARDS_ID
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'BEDS' AND column_name = 'WARDS_ID'
  ) THEN
    EXECUTE 'UPDATE "BEDS" SET "WARD_ID" = COALESCE("WARD_ID", "WARDS_ID") WHERE "WARD_ID" IS NULL';
  END IF;
END $$;

-- Backfill LABEL from legacy BED_NO
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'BEDS' AND column_name = 'BED_NO'
  ) THEN
    EXECUTE 'UPDATE "BEDS" SET "LABEL" = COALESCE(NULLIF(TRIM("LABEL"), ''''), NULLIF(TRIM("BED_NO"), ''''), ''BED-'' || "BED_ID"::text) WHERE "LABEL" IS NULL OR TRIM("LABEL") = ''''';
  ELSE
    UPDATE "BEDS"
    SET "LABEL" = COALESCE(NULLIF(TRIM("LABEL"), ''), 'BED-' || "BED_ID"::text)
    WHERE "LABEL" IS NULL OR TRIM("LABEL") = '';
  END IF;
END $$;

-- Backfill STATUS from legacy AVAILABILITY (or default AVAILABLE)
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'BEDS' AND column_name = 'AVAILABILITY'
  ) THEN
    EXECUTE $u$
      UPDATE "BEDS" SET "STATUS" = CASE
        WHEN "STATUS" IS NOT NULL AND TRIM("STATUS") <> '' THEN UPPER(TRIM("STATUS"))
        WHEN UPPER(TRIM(COALESCE("AVAILABILITY", ''))) IN ('AVAILABLE', 'YES', 'FREE', '1', 'TRUE') THEN 'AVAILABLE'
        WHEN UPPER(TRIM(COALESCE("AVAILABILITY", ''))) IN ('OCCUPIED', 'NO', 'TAKEN', '0', 'FALSE') THEN 'OCCUPIED'
        WHEN UPPER(TRIM(COALESCE("AVAILABILITY", ''))) IN ('RESERVED') THEN 'RESERVED'
        WHEN UPPER(TRIM(COALESCE("AVAILABILITY", ''))) IN ('MAINTENANCE', 'OUT_OF_SERVICE', 'OOS') THEN 'OUT_OF_SERVICE'
        ELSE 'AVAILABLE'
      END
      WHERE "STATUS" IS NULL OR TRIM("STATUS") = ''
    $u$;
  ELSE
    UPDATE "BEDS"
    SET "STATUS" = COALESCE(NULLIF(TRIM("STATUS"), ''), 'AVAILABLE')
    WHERE "STATUS" IS NULL OR TRIM("STATUS") = '';
  END IF;
END $$;

UPDATE "BEDS" SET "CREATED_DATE" = COALESCE("CREATED_DATE", NOW());
UPDATE "BEDS" SET "CREATED_BY" = COALESCE("CREATED_BY", 'SYSTEM');

-- Drop orphan beds that still have no ward (cannot assign)
DELETE FROM "BEDS" WHERE "WARD_ID" IS NULL;

ALTER TABLE "BEDS" ALTER COLUMN "WARD_ID" SET NOT NULL;
ALTER TABLE "BEDS" ALTER COLUMN "LABEL" SET NOT NULL;
ALTER TABLE "BEDS" ALTER COLUMN "STATUS" SET NOT NULL;
ALTER TABLE "BEDS" ALTER COLUMN "STATUS" SET DEFAULT 'AVAILABLE';

CREATE UNIQUE INDEX IF NOT EXISTS "BEDS_WARD_ID_LABEL_key" ON "BEDS"("WARD_ID", "LABEL");
CREATE INDEX IF NOT EXISTS "BEDS_WARD_ID_idx" ON "BEDS"("WARD_ID");
CREATE INDEX IF NOT EXISTS "BEDS_STATUS_idx" ON "BEDS"("STATUS");

DO $$ BEGIN
  ALTER TABLE "BEDS" ADD CONSTRAINT "BEDS_WARD_ID_fkey"
    FOREIGN KEY ("WARD_ID") REFERENCES "WARDS"("WARD_ID") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- ─── Standard testing wards (idempotent upsert by CODE) ─────────────────────
INSERT INTO "WARDS" (
  "CODE", "NAME", "WARD_TYPE", "WARD_CLASS", "GENDER",
  "DAILY_BED_RATE", "ADMISSION_DEPOSIT_DEFAULT", "STATUS", "CREATED_BY", "CREATED_DATE"
)
VALUES
  ('MGEN', 'Male General Ward', 'General', 'General', 'Male', 5000, 50000, 'Active', 'SYSTEM', NOW()),
  ('FGEN', 'Female General Ward', 'General', 'General', 'Female', 5000, 50000, 'Active', 'SYSTEM', NOW()),
  ('MIXG', 'Mixed Medical Ward', 'General', 'General', 'Mixed', 5000, 50000, 'Active', 'SYSTEM', NOW()),
  ('MVIP', 'Male VIP Ward', 'General', 'VIP', 'Male', 80000, 100000, 'Active', 'SYSTEM', NOW()),
  ('FVIP', 'Female VIP Ward', 'General', 'VIP', 'Female', 80000, 100000, 'Active', 'SYSTEM', NOW()),
  ('GEN',  'General Ward', 'General', 'General', 'Mixed', 5000, 50000, 'Active', 'SYSTEM', NOW()),
  ('PRIV', 'Private Ward', 'General', 'Private', 'Mixed', 40000, 75000, 'Active', 'SYSTEM', NOW()),
  ('SEMI', 'Semi Private Ward', 'General', 'SemiPrivate', 'Mixed', 20000, 60000, 'Active', 'SYSTEM', NOW()),
  ('VIP',  'VIP Ward', 'General', 'VIP', 'Mixed', 80000, 100000, 'Active', 'SYSTEM', NOW()),
  ('ICU',  'ICU', 'ICU', 'ICU', 'Mixed', 80000, 100000, 'Active', 'SYSTEM', NOW()),
  ('W1C',  'Ward 1C (Psychiatric)', 'Psychiatric', 'General', 'Mixed', 5000, 50000, 'Active', 'SYSTEM', NOW())
ON CONFLICT ("CODE") DO UPDATE SET
  "NAME" = EXCLUDED."NAME",
  "WARD_TYPE" = EXCLUDED."WARD_TYPE",
  "WARD_CLASS" = EXCLUDED."WARD_CLASS",
  "GENDER" = EXCLUDED."GENDER",
  "DAILY_BED_RATE" = EXCLUDED."DAILY_BED_RATE",
  "ADMISSION_DEPOSIT_DEFAULT" = EXCLUDED."ADMISSION_DEPOSIT_DEFAULT",
  "STATUS" = 'Active',
  "UPDATED_BY" = 'SYSTEM',
  "UPDATED_DATE" = NOW();

-- Pad 20 AVAILABLE beds (01–20) on every standard Active ward — skip existing labels
INSERT INTO "BEDS" ("WARD_ID", "LABEL", "STATUS", "CREATED_BY", "CREATED_DATE")
SELECT w."WARD_ID", b.label, 'AVAILABLE', 'SYSTEM', NOW()
FROM "WARDS" w
CROSS JOIN (
  VALUES
    ('01'),('02'),('03'),('04'),('05'),('06'),('07'),('08'),('09'),('10'),
    ('11'),('12'),('13'),('14'),('15'),('16'),('17'),('18'),('19'),('20')
) AS b(label)
WHERE w."CODE" IN ('MGEN','FGEN','MIXG','MVIP','FVIP','GEN','PRIV','SEMI','VIP','ICU','W1C')
  AND w."STATUS" = 'Active'
  AND NOT EXISTS (
    SELECT 1 FROM "BEDS" x WHERE x."WARD_ID" = w."WARD_ID" AND x."LABEL" = b.label
  );

-- Leave seeded beds AVAILABLE so Records can assign them during admit testing.
-- Occupancy is updated to OCCUPIED by POST /api/admissions when a patient is admitted.