-- Nursing operations Phases 10–12: orders, tasks, MAR, shifts, handover, ICU, messages, reports

CREATE TABLE IF NOT EXISTS "NURSING_ORDERS" (
  "ORDER_ID" SERIAL PRIMARY KEY,
  "PERSON_ID" INTEGER NOT NULL,
  "ADMISSION_ID" INTEGER,
  "KIND" VARCHAR(20) NOT NULL,
  "ITEMS_JSON" TEXT NOT NULL,
  "STATUS" VARCHAR(40) NOT NULL DEFAULT 'ORDERED',
  "ORDERED_BY" VARCHAR(100),
  "ACKNOWLEDGED_BY" VARCHAR(100),
  "ACKNOWLEDGED_AT" TIMESTAMP(3),
  "PAYMENT_STATUS" VARCHAR(30) NOT NULL DEFAULT 'UNPAID',
  "LAB_STATUS" VARCHAR(40),
  "SAMPLE_ID" VARCHAR(80),
  "SAMPLE_COLLECTED_AT" TIMESTAMP(3),
  "SAMPLE_COLLECTED_BY" VARCHAR(100),
  "CREATED_BY_ID" INTEGER,
  "CREATED_DATE" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "UPDATED_DATE" TIMESTAMP(3),
  CONSTRAINT "NURSING_ORDERS_PERSON_ID_fkey" FOREIGN KEY ("PERSON_ID") REFERENCES "PERSONS"("PERSON_ID") ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT "NURSING_ORDERS_ADMISSION_ID_fkey" FOREIGN KEY ("ADMISSION_ID") REFERENCES "ADMISSIONS"("ADMISSION_ID") ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE INDEX IF NOT EXISTS "NURSING_ORDERS_PERSON_ID_idx" ON "NURSING_ORDERS"("PERSON_ID");
CREATE INDEX IF NOT EXISTS "NURSING_ORDERS_ADMISSION_ID_idx" ON "NURSING_ORDERS"("ADMISSION_ID");
CREATE INDEX IF NOT EXISTS "NURSING_ORDERS_KIND_idx" ON "NURSING_ORDERS"("KIND");
CREATE INDEX IF NOT EXISTS "NURSING_ORDERS_STATUS_idx" ON "NURSING_ORDERS"("STATUS");
CREATE INDEX IF NOT EXISTS "NURSING_ORDERS_CREATED_DATE_idx" ON "NURSING_ORDERS"("CREATED_DATE");

CREATE TABLE IF NOT EXISTS "NURSING_TASKS" (
  "TASK_ID" SERIAL PRIMARY KEY,
  "PERSON_ID" INTEGER,
  "ADMISSION_ID" INTEGER,
  "PATIENT_NAME" VARCHAR(255),
  "TITLE" VARCHAR(500) NOT NULL,
  "CATEGORY" VARCHAR(40) NOT NULL DEFAULT 'Other',
  "STATUS" VARCHAR(30) NOT NULL DEFAULT 'PENDING',
  "DUE_AT" TIMESTAMP(3),
  "SOURCE_ORDER_ID" INTEGER,
  "ASSIGNED_TO" VARCHAR(100),
  "CREATED_BY" VARCHAR(100),
  "CREATED_BY_ID" INTEGER,
  "CREATED_DATE" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "UPDATED_DATE" TIMESTAMP(3),
  CONSTRAINT "NURSING_TASKS_PERSON_ID_fkey" FOREIGN KEY ("PERSON_ID") REFERENCES "PERSONS"("PERSON_ID") ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT "NURSING_TASKS_ADMISSION_ID_fkey" FOREIGN KEY ("ADMISSION_ID") REFERENCES "ADMISSIONS"("ADMISSION_ID") ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT "NURSING_TASKS_SOURCE_ORDER_ID_fkey" FOREIGN KEY ("SOURCE_ORDER_ID") REFERENCES "NURSING_ORDERS"("ORDER_ID") ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE INDEX IF NOT EXISTS "NURSING_TASKS_PERSON_ID_idx" ON "NURSING_TASKS"("PERSON_ID");
CREATE INDEX IF NOT EXISTS "NURSING_TASKS_STATUS_idx" ON "NURSING_TASKS"("STATUS");
CREATE INDEX IF NOT EXISTS "NURSING_TASKS_DUE_AT_idx" ON "NURSING_TASKS"("DUE_AT");
CREATE INDEX IF NOT EXISTS "NURSING_TASKS_SOURCE_ORDER_ID_idx" ON "NURSING_TASKS"("SOURCE_ORDER_ID");

CREATE TABLE IF NOT EXISTS "NURSING_MAR_ENTRIES" (
  "MAR_ID" SERIAL PRIMARY KEY,
  "PERSON_ID" INTEGER NOT NULL,
  "ADMISSION_ID" INTEGER,
  "ORDER_ID" INTEGER,
  "DRUG" VARCHAR(255) NOT NULL,
  "DOSE" VARCHAR(100) NOT NULL,
  "ROUTE" VARCHAR(50) NOT NULL,
  "FREQUENCY" VARCHAR(100) NOT NULL,
  "SCHEDULED_TIME" TIMESTAMP(3) NOT NULL,
  "KIND" VARCHAR(30) NOT NULL DEFAULT 'Scheduled',
  "STATUS" VARCHAR(20) NOT NULL DEFAULT 'PENDING',
  "REASON" TEXT,
  "SIDE_EFFECTS" TEXT,
  "SOURCE" VARCHAR(255),
  "PRESCRIBER" VARCHAR(255),
  "NOTES" TEXT,
  "PHARMACY_DISPENSED" BOOLEAN NOT NULL DEFAULT false,
  "ADMINISTERED_BY" VARCHAR(100),
  "ADMINISTERED_AT" TIMESTAMP(3),
  "CREATED_BY_ID" INTEGER,
  "CREATED_DATE" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "UPDATED_DATE" TIMESTAMP(3),
  CONSTRAINT "NURSING_MAR_ENTRIES_PERSON_ID_fkey" FOREIGN KEY ("PERSON_ID") REFERENCES "PERSONS"("PERSON_ID") ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT "NURSING_MAR_ENTRIES_ADMISSION_ID_fkey" FOREIGN KEY ("ADMISSION_ID") REFERENCES "ADMISSIONS"("ADMISSION_ID") ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT "NURSING_MAR_ENTRIES_ORDER_ID_fkey" FOREIGN KEY ("ORDER_ID") REFERENCES "NURSING_ORDERS"("ORDER_ID") ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE INDEX IF NOT EXISTS "NURSING_MAR_ENTRIES_PERSON_ID_idx" ON "NURSING_MAR_ENTRIES"("PERSON_ID");
CREATE INDEX IF NOT EXISTS "NURSING_MAR_ENTRIES_ADMISSION_ID_idx" ON "NURSING_MAR_ENTRIES"("ADMISSION_ID");
CREATE INDEX IF NOT EXISTS "NURSING_MAR_ENTRIES_STATUS_idx" ON "NURSING_MAR_ENTRIES"("STATUS");
CREATE INDEX IF NOT EXISTS "NURSING_MAR_ENTRIES_SCHEDULED_TIME_idx" ON "NURSING_MAR_ENTRIES"("SCHEDULED_TIME");
CREATE INDEX IF NOT EXISTS "NURSING_MAR_ENTRIES_KIND_idx" ON "NURSING_MAR_ENTRIES"("KIND");

CREATE TABLE IF NOT EXISTS "NURSING_SHIFTS" (
  "SHIFT_ID" SERIAL PRIMARY KEY,
  "WARD_ID" INTEGER,
  "SHIFT" VARCHAR(20) NOT NULL,
  "STATUS" VARCHAR(20) NOT NULL DEFAULT 'Scheduled',
  "LEAD_NURSE" VARCHAR(100),
  "STAFF_COUNT" INTEGER NOT NULL DEFAULT 0,
  "PATIENTS_COVERED" INTEGER NOT NULL DEFAULT 0,
  "START_AT" TIMESTAMP(3),
  "END_AT" TIMESTAMP(3),
  "SUMMARY" TEXT,
  "CREATED_BY_ID" INTEGER,
  "CREATED_DATE" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "UPDATED_DATE" TIMESTAMP(3),
  CONSTRAINT "NURSING_SHIFTS_WARD_ID_fkey" FOREIGN KEY ("WARD_ID") REFERENCES "WARDS"("WARD_ID") ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE INDEX IF NOT EXISTS "NURSING_SHIFTS_WARD_ID_idx" ON "NURSING_SHIFTS"("WARD_ID");
CREATE INDEX IF NOT EXISTS "NURSING_SHIFTS_STATUS_idx" ON "NURSING_SHIFTS"("STATUS");
CREATE INDEX IF NOT EXISTS "NURSING_SHIFTS_START_AT_idx" ON "NURSING_SHIFTS"("START_AT");

CREATE TABLE IF NOT EXISTS "NURSING_HANDOVERS" (
  "HANDOVER_ID" SERIAL PRIMARY KEY,
  "WARD_ID" INTEGER,
  "WARD_NAME" VARCHAR(150),
  "SHIFT" VARCHAR(20) NOT NULL,
  "SUMMARY" TEXT NOT NULL,
  "CRITICAL_PATIENTS_JSON" TEXT NOT NULL DEFAULT '[]',
  "PENDING_MEDS" TEXT,
  "PENDING_LABS" TEXT,
  "INCIDENTS" TEXT,
  "SPECIAL_INSTRUCTIONS" TEXT,
  "HANDED_OVER_BY" VARCHAR(100),
  "RECEIVED_BY" VARCHAR(100),
  "ACKNOWLEDGED" BOOLEAN NOT NULL DEFAULT false,
  "ACKNOWLEDGED_AT" TIMESTAMP(3),
  "CREATED_BY_ID" INTEGER,
  "CREATED_DATE" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "NURSING_HANDOVERS_WARD_ID_fkey" FOREIGN KEY ("WARD_ID") REFERENCES "WARDS"("WARD_ID") ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE INDEX IF NOT EXISTS "NURSING_HANDOVERS_WARD_ID_idx" ON "NURSING_HANDOVERS"("WARD_ID");
CREATE INDEX IF NOT EXISTS "NURSING_HANDOVERS_CREATED_DATE_idx" ON "NURSING_HANDOVERS"("CREATED_DATE");

CREATE TABLE IF NOT EXISTS "NURSING_ICU_NOTES" (
  "ICU_NOTE_ID" SERIAL PRIMARY KEY,
  "PERSON_ID" INTEGER NOT NULL,
  "ADMISSION_ID" INTEGER,
  "BLOOD_PRESSURE" VARCHAR(20),
  "SPO2_PCT" DECIMAL(5, 2),
  "HEART_RATE" INTEGER,
  "VENT_SETTINGS" VARCHAR(500),
  "NOTE" TEXT,
  "RECORDED_BY" VARCHAR(100),
  "RECORDED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "CREATED_BY_ID" INTEGER,
  CONSTRAINT "NURSING_ICU_NOTES_PERSON_ID_fkey" FOREIGN KEY ("PERSON_ID") REFERENCES "PERSONS"("PERSON_ID") ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT "NURSING_ICU_NOTES_ADMISSION_ID_fkey" FOREIGN KEY ("ADMISSION_ID") REFERENCES "ADMISSIONS"("ADMISSION_ID") ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE INDEX IF NOT EXISTS "NURSING_ICU_NOTES_PERSON_ID_idx" ON "NURSING_ICU_NOTES"("PERSON_ID");
CREATE INDEX IF NOT EXISTS "NURSING_ICU_NOTES_ADMISSION_ID_idx" ON "NURSING_ICU_NOTES"("ADMISSION_ID");
CREATE INDEX IF NOT EXISTS "NURSING_ICU_NOTES_RECORDED_AT_idx" ON "NURSING_ICU_NOTES"("RECORDED_AT");

CREATE TABLE IF NOT EXISTS "NURSING_ICU_INFUSIONS" (
  "INFUSION_ID" SERIAL PRIMARY KEY,
  "PERSON_ID" INTEGER NOT NULL,
  "ADMISSION_ID" INTEGER,
  "MEDICATION" VARCHAR(255) NOT NULL,
  "CURRENT_RATE" VARCHAR(100),
  "NEW_RATE" VARCHAR(100),
  "REASON" VARCHAR(500),
  "NOTE" TEXT,
  "STATUS" VARCHAR(30) NOT NULL DEFAULT 'Running',
  "RECORDED_BY" VARCHAR(100),
  "RECORDED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "CREATED_BY_ID" INTEGER,
  CONSTRAINT "NURSING_ICU_INFUSIONS_PERSON_ID_fkey" FOREIGN KEY ("PERSON_ID") REFERENCES "PERSONS"("PERSON_ID") ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT "NURSING_ICU_INFUSIONS_ADMISSION_ID_fkey" FOREIGN KEY ("ADMISSION_ID") REFERENCES "ADMISSIONS"("ADMISSION_ID") ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE INDEX IF NOT EXISTS "NURSING_ICU_INFUSIONS_PERSON_ID_idx" ON "NURSING_ICU_INFUSIONS"("PERSON_ID");
CREATE INDEX IF NOT EXISTS "NURSING_ICU_INFUSIONS_ADMISSION_ID_idx" ON "NURSING_ICU_INFUSIONS"("ADMISSION_ID");
CREATE INDEX IF NOT EXISTS "NURSING_ICU_INFUSIONS_RECORDED_AT_idx" ON "NURSING_ICU_INFUSIONS"("RECORDED_AT");

CREATE TABLE IF NOT EXISTS "NURSING_MESSAGES" (
  "MESSAGE_ID" SERIAL PRIMARY KEY,
  "CHANNEL" VARCHAR(40) NOT NULL,
  "BODY" TEXT NOT NULL,
  "FROM_LABEL" VARCHAR(100),
  "FROM_USER_ID" INTEGER,
  "PERSON_ID" INTEGER,
  "IS_MINE" BOOLEAN NOT NULL DEFAULT true,
  "READ_AT" TIMESTAMP(3),
  "CREATED_DATE" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "NURSING_MESSAGES_PERSON_ID_fkey" FOREIGN KEY ("PERSON_ID") REFERENCES "PERSONS"("PERSON_ID") ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE INDEX IF NOT EXISTS "NURSING_MESSAGES_CHANNEL_idx" ON "NURSING_MESSAGES"("CHANNEL");
CREATE INDEX IF NOT EXISTS "NURSING_MESSAGES_CREATED_DATE_idx" ON "NURSING_MESSAGES"("CREATED_DATE");
CREATE INDEX IF NOT EXISTS "NURSING_MESSAGES_PERSON_ID_idx" ON "NURSING_MESSAGES"("PERSON_ID");

CREATE TABLE IF NOT EXISTS "NURSING_REPORT_SNAPSHOTS" (
  "REPORT_ID" SERIAL PRIMARY KEY,
  "REPORT_TYPE" VARCHAR(40) NOT NULL,
  "RANGE_LABEL" VARCHAR(100),
  "WARD_ID" INTEGER,
  "WARD_NAME" VARCHAR(150),
  "NOTES" TEXT,
  "PAYLOAD_JSON" TEXT NOT NULL,
  "GENERATED_BY" VARCHAR(100),
  "CREATED_DATE" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "NURSING_REPORT_SNAPSHOTS_WARD_ID_fkey" FOREIGN KEY ("WARD_ID") REFERENCES "WARDS"("WARD_ID") ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE INDEX IF NOT EXISTS "NURSING_REPORT_SNAPSHOTS_REPORT_TYPE_idx" ON "NURSING_REPORT_SNAPSHOTS"("REPORT_TYPE");
CREATE INDEX IF NOT EXISTS "NURSING_REPORT_SNAPSHOTS_CREATED_DATE_idx" ON "NURSING_REPORT_SNAPSHOTS"("CREATED_DATE");
