-- Imaging reports (radiologist release + doctor critical ack)
CREATE TABLE IF NOT EXISTS "IMAGING_REPORTS" (
  "REPORT_ID" SERIAL PRIMARY KEY,
  "REPORT_NO" VARCHAR(50) NOT NULL,
  "IMAGING_REQUEST_ID" INTEGER NOT NULL,
  "PERSON_ID" INTEGER NOT NULL,
  "FINDINGS" TEXT,
  "IMPRESSION" TEXT,
  "CRITICAL" VARCHAR(1) NOT NULL DEFAULT 'N',
  "STATUS" VARCHAR(50) NOT NULL DEFAULT 'Draft',
  "RELEASED_AT" TIMESTAMP(3),
  "CRITICAL_ACK_AT" TIMESTAMP(3),
  "CRITICAL_ACK_BY" VARCHAR(100),
  "CRITICAL_ACK_BY_ID" INTEGER,
  "DELETED" VARCHAR(1) DEFAULT 'N',
  "DELETED_DATE" TIMESTAMP(3),
  "CREATED_BY_ID" INTEGER,
  "CREATED_BY" VARCHAR(100),
  "CREATED_DATE" TIMESTAMP(3),
  "UPDATED_BY_ID" INTEGER,
  "UPDATED_BY" VARCHAR(100),
  "UPDATED_DATE" TIMESTAMP(3),
  CONSTRAINT "IMAGING_REPORTS_REPORT_NO_key" UNIQUE ("REPORT_NO"),
  CONSTRAINT "IMAGING_REPORTS_IMAGING_REQUEST_ID_fkey"
    FOREIGN KEY ("IMAGING_REQUEST_ID") REFERENCES "IMAGING_REQUESTS"("IMAGING_REQUEST_ID") ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT "IMAGING_REPORTS_PERSON_ID_fkey"
    FOREIGN KEY ("PERSON_ID") REFERENCES "PERSONS"("PERSON_ID") ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS "IMAGING_REPORTS_IMAGING_REQUEST_ID_idx" ON "IMAGING_REPORTS"("IMAGING_REQUEST_ID");
CREATE INDEX IF NOT EXISTS "IMAGING_REPORTS_PERSON_ID_idx" ON "IMAGING_REPORTS"("PERSON_ID");
CREATE INDEX IF NOT EXISTS "IMAGING_REPORTS_STATUS_idx" ON "IMAGING_REPORTS"("STATUS");
CREATE INDEX IF NOT EXISTS "IMAGING_REPORTS_CRITICAL_idx" ON "IMAGING_REPORTS"("CRITICAL");
CREATE INDEX IF NOT EXISTS "IMAGING_REPORTS_CREATED_DATE_idx" ON "IMAGING_REPORTS"("CREATED_DATE");
