-- Legacy appointments are staff-scheduled; public bookings stay on SERVICE_BOOKINGS.
ALTER TABLE "FOLLOW_UPS" ADD COLUMN IF NOT EXISTS "CREATOR_TYPE" VARCHAR(20);

UPDATE "FOLLOW_UPS" SET "CREATOR_TYPE" = 'staff' WHERE "CREATOR_TYPE" IS NULL OR TRIM("CREATOR_TYPE") = '';

ALTER TABLE "FOLLOW_UPS" ALTER COLUMN "CREATOR_TYPE" SET DEFAULT 'staff';
ALTER TABLE "FOLLOW_UPS" ALTER COLUMN "CREATOR_TYPE" SET NOT NULL;

CREATE INDEX IF NOT EXISTS "FOLLOW_UPS_CREATOR_TYPE_idx" ON "FOLLOW_UPS"("CREATOR_TYPE");
