-- Staff support requests (shared ticket domain for header Support button + HR queue)

CREATE TABLE IF NOT EXISTS "SUPPORT_REQUESTS" (
    "REQUEST_ID" SERIAL PRIMARY KEY,
    "REQUEST_NO" VARCHAR(50) NOT NULL,
    "USER_ID" INTEGER NOT NULL,
    "STAFF_NAME" VARCHAR(150) NOT NULL,
    "ROLE_LABEL" VARCHAR(100),
    "ISSUE_TYPE" VARCHAR(40) NOT NULL,
    "DESCRIPTION" TEXT NOT NULL,
    "MODULE" VARCHAR(40),
    "STATUS" VARCHAR(30) NOT NULL DEFAULT 'Open',
    "RESOLVED_NOTE" TEXT,
    "RESOLVED_AT" TIMESTAMP(3),
    "RESOLVED_BY" VARCHAR(150),
    "RESOLVED_BY_ID" INTEGER,
    "CREATED_BY_ID" INTEGER,
    "CREATED_BY" VARCHAR(100),
    "CREATED_DATE" TIMESTAMP(3),
    "UPDATED_BY_ID" INTEGER,
    "UPDATED_BY" VARCHAR(100),
    "UPDATED_DATE" TIMESTAMP(3),
    "DELETED_FLAG" VARCHAR(1) DEFAULT 'N'
);

CREATE UNIQUE INDEX IF NOT EXISTS "SUPPORT_REQUESTS_REQUEST_NO_key"
  ON "SUPPORT_REQUESTS"("REQUEST_NO");
CREATE INDEX IF NOT EXISTS "SUPPORT_REQUESTS_USER_ID_idx"
  ON "SUPPORT_REQUESTS"("USER_ID");
CREATE INDEX IF NOT EXISTS "SUPPORT_REQUESTS_STATUS_idx"
  ON "SUPPORT_REQUESTS"("STATUS");
CREATE INDEX IF NOT EXISTS "SUPPORT_REQUESTS_MODULE_idx"
  ON "SUPPORT_REQUESTS"("MODULE");
CREATE INDEX IF NOT EXISTS "SUPPORT_REQUESTS_CREATED_DATE_idx"
  ON "SUPPORT_REQUESTS"("CREATED_DATE");
CREATE INDEX IF NOT EXISTS "SUPPORT_REQUESTS_ISSUE_TYPE_idx"
  ON "SUPPORT_REQUESTS"("ISSUE_TYPE");
