-- HEIP daily reports — additive tables (Phases 1–4)

CREATE TABLE IF NOT EXISTS "HEIP_REPORT_TEMPLATES" (
    "TEMPLATE_ID" SERIAL NOT NULL,
    "CODE" VARCHAR(60) NOT NULL,
    "NAME" VARCHAR(200) NOT NULL,
    "DEPARTMENT_ID" INTEGER,
    "ROLE_NAME" VARCHAR(80),
    "FREQUENCY" VARCHAR(20) NOT NULL DEFAULT 'daily',
    "DEADLINE_HOUR" INTEGER NOT NULL DEFAULT 10,
    "DEADLINE_GRACE_HOURS" INTEGER NOT NULL DEFAULT 2,
    "IS_ACTIVE" BOOLEAN NOT NULL DEFAULT true,
    "CREATED_BY_ID" INTEGER,
    "CREATED_BY" VARCHAR(100),
    "CREATED_DATE" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_BY_ID" INTEGER,
    "UPDATED_BY" VARCHAR(100),
    "UPDATED_DATE" TIMESTAMP(3),
    CONSTRAINT "HEIP_REPORT_TEMPLATES_pkey" PRIMARY KEY ("TEMPLATE_ID")
);
CREATE UNIQUE INDEX IF NOT EXISTS "HEIP_REPORT_TEMPLATES_CODE_key" ON "HEIP_REPORT_TEMPLATES"("CODE");
CREATE INDEX IF NOT EXISTS "HEIP_REPORT_TEMPLATES_DEPARTMENT_ID_idx" ON "HEIP_REPORT_TEMPLATES"("DEPARTMENT_ID");
CREATE INDEX IF NOT EXISTS "HEIP_REPORT_TEMPLATES_IS_ACTIVE_idx" ON "HEIP_REPORT_TEMPLATES"("IS_ACTIVE");
CREATE INDEX IF NOT EXISTS "HEIP_REPORT_TEMPLATES_ROLE_NAME_idx" ON "HEIP_REPORT_TEMPLATES"("ROLE_NAME");

CREATE TABLE IF NOT EXISTS "HEIP_TEMPLATE_VERSIONS" (
    "VERSION_ID" SERIAL NOT NULL,
    "TEMPLATE_ID" INTEGER NOT NULL,
    "VERSION_NO" INTEGER NOT NULL,
    "FIELD_SCHEMA" JSONB NOT NULL,
    "STATUS" VARCHAR(20) NOT NULL DEFAULT 'Draft',
    "PUBLISHED_AT" TIMESTAMP(3),
    "PUBLISHED_BY_ID" INTEGER,
    "PUBLISHED_BY" VARCHAR(100),
    "CREATED_BY_ID" INTEGER,
    "CREATED_BY" VARCHAR(100),
    "CREATED_DATE" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_BY_ID" INTEGER,
    "UPDATED_BY" VARCHAR(100),
    "UPDATED_DATE" TIMESTAMP(3),
    CONSTRAINT "HEIP_TEMPLATE_VERSIONS_pkey" PRIMARY KEY ("VERSION_ID")
);
CREATE UNIQUE INDEX IF NOT EXISTS "HEIP_TEMPLATE_VERSIONS_TEMPLATE_ID_VERSION_NO_key" ON "HEIP_TEMPLATE_VERSIONS"("TEMPLATE_ID", "VERSION_NO");
CREATE INDEX IF NOT EXISTS "HEIP_TEMPLATE_VERSIONS_TEMPLATE_ID_STATUS_idx" ON "HEIP_TEMPLATE_VERSIONS"("TEMPLATE_ID", "STATUS");

CREATE TABLE IF NOT EXISTS "HEIP_REPORTS" (
    "REPORT_ID" SERIAL NOT NULL,
    "TEMPLATE_ID" INTEGER NOT NULL,
    "TEMPLATE_VERSION_ID" INTEGER NOT NULL,
    "EMPLOYEE_ID" INTEGER NOT NULL,
    "USER_ID" INTEGER,
    "DEPARTMENT_ID" INTEGER,
    "REPORT_DATE" DATE NOT NULL,
    "SHIFT" VARCHAR(40),
    "STATUS" VARCHAR(30) NOT NULL DEFAULT 'Draft',
    "LATE" BOOLEAN NOT NULL DEFAULT false,
    "PREVIOUS_REPORT_ID" INTEGER,
    "AMENDMENT_REASON" TEXT,
    "SUBMITTED_AT" TIMESTAMP(3),
    "APPROVED_AT" TIMESTAMP(3),
    "APPROVED_BY_ID" INTEGER,
    "APPROVED_BY" VARCHAR(100),
    "RETURN_COMMENT" TEXT,
    "CREATED_BY_ID" INTEGER,
    "CREATED_BY" VARCHAR(100),
    "CREATED_DATE" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_BY_ID" INTEGER,
    "UPDATED_BY" VARCHAR(100),
    "UPDATED_DATE" TIMESTAMP(3),
    CONSTRAINT "HEIP_REPORTS_pkey" PRIMARY KEY ("REPORT_ID")
);
CREATE INDEX IF NOT EXISTS "HEIP_REPORTS_REPORT_DATE_DEPARTMENT_ID_idx" ON "HEIP_REPORTS"("REPORT_DATE", "DEPARTMENT_ID");
CREATE INDEX IF NOT EXISTS "HEIP_REPORTS_EMPLOYEE_ID_REPORT_DATE_idx" ON "HEIP_REPORTS"("EMPLOYEE_ID", "REPORT_DATE");
CREATE INDEX IF NOT EXISTS "HEIP_REPORTS_STATUS_idx" ON "HEIP_REPORTS"("STATUS");
CREATE INDEX IF NOT EXISTS "HEIP_REPORTS_TEMPLATE_ID_REPORT_DATE_idx" ON "HEIP_REPORTS"("TEMPLATE_ID", "REPORT_DATE");
CREATE INDEX IF NOT EXISTS "HEIP_REPORTS_PREVIOUS_REPORT_ID_idx" ON "HEIP_REPORTS"("PREVIOUS_REPORT_ID");

CREATE TABLE IF NOT EXISTS "HEIP_REPORT_VALUES" (
    "VALUE_ID" SERIAL NOT NULL,
    "REPORT_ID" INTEGER NOT NULL,
    "FIELD_KEY" VARCHAR(80) NOT NULL,
    "METRIC_KEY" VARCHAR(80),
    "VALUE_TEXT" TEXT,
    "VALUE_NUMBER" DECIMAL(18,4),
    "VALUE_JSON" JSONB,
    "SYSTEM_VALUE_NUMBER" DECIMAL(18,4),
    "SYSTEM_VALUE_TEXT" TEXT,
    "OVERRIDE_REASON" TEXT,
    "CREATED_DATE" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_DATE" TIMESTAMP(3),
    CONSTRAINT "HEIP_REPORT_VALUES_pkey" PRIMARY KEY ("VALUE_ID")
);
CREATE UNIQUE INDEX IF NOT EXISTS "HEIP_REPORT_VALUES_REPORT_ID_FIELD_KEY_key" ON "HEIP_REPORT_VALUES"("REPORT_ID", "FIELD_KEY");
CREATE INDEX IF NOT EXISTS "HEIP_REPORT_VALUES_METRIC_KEY_idx" ON "HEIP_REPORT_VALUES"("METRIC_KEY");
CREATE INDEX IF NOT EXISTS "HEIP_REPORT_VALUES_REPORT_ID_idx" ON "HEIP_REPORT_VALUES"("REPORT_ID");

CREATE TABLE IF NOT EXISTS "HEIP_REPORT_EVENTS" (
    "EVENT_ID" SERIAL NOT NULL,
    "REPORT_ID" INTEGER NOT NULL,
    "EVENT_TYPE" VARCHAR(40) NOT NULL,
    "FROM_STATUS" VARCHAR(30),
    "TO_STATUS" VARCHAR(30),
    "COMMENT" TEXT,
    "ACTOR_ID" INTEGER,
    "ACTOR_LABEL" VARCHAR(100),
    "CREATED_DATE" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "HEIP_REPORT_EVENTS_pkey" PRIMARY KEY ("EVENT_ID")
);
CREATE INDEX IF NOT EXISTS "HEIP_REPORT_EVENTS_REPORT_ID_idx" ON "HEIP_REPORT_EVENTS"("REPORT_ID");
CREATE INDEX IF NOT EXISTS "HEIP_REPORT_EVENTS_CREATED_DATE_idx" ON "HEIP_REPORT_EVENTS"("CREATED_DATE");

CREATE TABLE IF NOT EXISTS "HEIP_RED_FLAGS" (
    "FLAG_ID" SERIAL NOT NULL,
    "REPORT_ID" INTEGER NOT NULL,
    "FIELD_KEY" VARCHAR(80) NOT NULL,
    "METRIC_KEY" VARCHAR(80),
    "TRIGGER_OP" VARCHAR(20) NOT NULL,
    "TRIGGER_VALUE" VARCHAR(100),
    "OBSERVED_VALUE" VARCHAR(200),
    "DEPARTMENT_ID" INTEGER,
    "EMPLOYEE_ID" INTEGER,
    "ACKED_AT" TIMESTAMP(3),
    "ACKED_BY_ID" INTEGER,
    "ACKED_BY" VARCHAR(100),
    "ACK_NOTE" TEXT,
    "CREATED_DATE" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "HEIP_RED_FLAGS_pkey" PRIMARY KEY ("FLAG_ID")
);
CREATE INDEX IF NOT EXISTS "HEIP_RED_FLAGS_ACKED_AT_idx" ON "HEIP_RED_FLAGS"("ACKED_AT");
CREATE INDEX IF NOT EXISTS "HEIP_RED_FLAGS_REPORT_ID_idx" ON "HEIP_RED_FLAGS"("REPORT_ID");
CREATE INDEX IF NOT EXISTS "HEIP_RED_FLAGS_DEPARTMENT_ID_idx" ON "HEIP_RED_FLAGS"("DEPARTMENT_ID");
CREATE INDEX IF NOT EXISTS "HEIP_RED_FLAGS_CREATED_DATE_idx" ON "HEIP_RED_FLAGS"("CREATED_DATE");

CREATE TABLE IF NOT EXISTS "HEIP_DEPARTMENT_SUMMARIES" (
    "SUMMARY_ID" SERIAL NOT NULL,
    "DEPARTMENT_ID" INTEGER NOT NULL,
    "REPORT_DATE" DATE NOT NULL,
    "BODY" TEXT NOT NULL,
    "AUTHOR_EMPLOYEE_ID" INTEGER,
    "AUTHOR_USER_ID" INTEGER,
    "CREATED_BY_ID" INTEGER,
    "CREATED_BY" VARCHAR(100),
    "CREATED_DATE" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_BY_ID" INTEGER,
    "UPDATED_BY" VARCHAR(100),
    "UPDATED_DATE" TIMESTAMP(3),
    CONSTRAINT "HEIP_DEPARTMENT_SUMMARIES_pkey" PRIMARY KEY ("SUMMARY_ID")
);
CREATE UNIQUE INDEX IF NOT EXISTS "HEIP_DEPARTMENT_SUMMARIES_DEPARTMENT_ID_REPORT_DATE_key" ON "HEIP_DEPARTMENT_SUMMARIES"("DEPARTMENT_ID", "REPORT_DATE");
CREATE INDEX IF NOT EXISTS "HEIP_DEPARTMENT_SUMMARIES_REPORT_DATE_idx" ON "HEIP_DEPARTMENT_SUMMARIES"("REPORT_DATE");

-- FKs (additive; IF NOT EXISTS via DO block for re-run safety)
DO $$ BEGIN
  ALTER TABLE "HEIP_TEMPLATE_VERSIONS"
    ADD CONSTRAINT "HEIP_TEMPLATE_VERSIONS_TEMPLATE_ID_fkey"
    FOREIGN KEY ("TEMPLATE_ID") REFERENCES "HEIP_REPORT_TEMPLATES"("TEMPLATE_ID") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "HEIP_REPORTS"
    ADD CONSTRAINT "HEIP_REPORTS_TEMPLATE_ID_fkey"
    FOREIGN KEY ("TEMPLATE_ID") REFERENCES "HEIP_REPORT_TEMPLATES"("TEMPLATE_ID") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "HEIP_REPORTS"
    ADD CONSTRAINT "HEIP_REPORTS_TEMPLATE_VERSION_ID_fkey"
    FOREIGN KEY ("TEMPLATE_VERSION_ID") REFERENCES "HEIP_TEMPLATE_VERSIONS"("VERSION_ID") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "HEIP_REPORTS"
    ADD CONSTRAINT "HEIP_REPORTS_PREVIOUS_REPORT_ID_fkey"
    FOREIGN KEY ("PREVIOUS_REPORT_ID") REFERENCES "HEIP_REPORTS"("REPORT_ID") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "HEIP_REPORT_VALUES"
    ADD CONSTRAINT "HEIP_REPORT_VALUES_REPORT_ID_fkey"
    FOREIGN KEY ("REPORT_ID") REFERENCES "HEIP_REPORTS"("REPORT_ID") ON DELETE CASCADE ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "HEIP_REPORT_EVENTS"
    ADD CONSTRAINT "HEIP_REPORT_EVENTS_REPORT_ID_fkey"
    FOREIGN KEY ("REPORT_ID") REFERENCES "HEIP_REPORTS"("REPORT_ID") ON DELETE CASCADE ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "HEIP_RED_FLAGS"
    ADD CONSTRAINT "HEIP_RED_FLAGS_REPORT_ID_fkey"
    FOREIGN KEY ("REPORT_ID") REFERENCES "HEIP_REPORTS"("REPORT_ID") ON DELETE CASCADE ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
