-- Clinical note HTML templates (legacy GENERIC_TEMPLATES)
CREATE TABLE IF NOT EXISTS "CLINICAL_NOTE_TEMPLATES" (
  "TEMPLATE_ID" SERIAL PRIMARY KEY,
  "LEGACY_TEMPLATE_ID" INTEGER,
  "CODE" VARCHAR(80) NOT NULL,
  "NAME" VARCHAR(255) NOT NULL,
  "TEMPLATE_TYPE" VARCHAR(100),
  "CONTENT_HTML" TEXT,
  "STATUS" VARCHAR(30) NOT NULL DEFAULT 'Active',
  "CREATED_BY" VARCHAR(100),
  "CREATED_DATE" TIMESTAMP(3),
  "UPDATED_BY" VARCHAR(100),
  "UPDATED_DATE" TIMESTAMP(3)
);

CREATE UNIQUE INDEX IF NOT EXISTS "CLINICAL_NOTE_TEMPLATES_LEGACY_TEMPLATE_ID_key"
  ON "CLINICAL_NOTE_TEMPLATES"("LEGACY_TEMPLATE_ID");
CREATE UNIQUE INDEX IF NOT EXISTS "CLINICAL_NOTE_TEMPLATES_CODE_key"
  ON "CLINICAL_NOTE_TEMPLATES"("CODE");
CREATE INDEX IF NOT EXISTS "CLINICAL_NOTE_TEMPLATES_STATUS_idx"
  ON "CLINICAL_NOTE_TEMPLATES"("STATUS");
CREATE INDEX IF NOT EXISTS "CLINICAL_NOTE_TEMPLATES_TEMPLATE_TYPE_idx"
  ON "CLINICAL_NOTE_TEMPLATES"("TEMPLATE_TYPE");
