-- Legacy lookup tables for CSV migration (exact IDs preserved by importer)

CREATE TABLE IF NOT EXISTS "USER_TYPES" (
    "USER_TYPE_ID" INTEGER NOT NULL,
    "NAME" VARCHAR(100) NOT NULL,
    CONSTRAINT "USER_TYPES_pkey" PRIMARY KEY ("USER_TYPE_ID")
);

CREATE TABLE IF NOT EXISTS "CLINICS" (
    "CLINIC_ID" INTEGER NOT NULL,
    "CLINIC_NAME" VARCHAR(255) NOT NULL,
    "DESCRIPTION" VARCHAR(500),
    "DEPARTMENT_ID" INTEGER,
    "IS_CONSULTATION_FREE" VARCHAR(10),
    "HOSPITAL_ID" INTEGER,
    "BRANCH_ID" INTEGER,
    "CLINIC_CATEGORY" VARCHAR(50),
    "CLINIC_CODE" VARCHAR(50),
    "DISCONTINUE_FLAG" VARCHAR(10),
    CONSTRAINT "CLINICS_pkey" PRIMARY KEY ("CLINIC_ID")
);

CREATE INDEX IF NOT EXISTS "CLINICS_HOSPITAL_ID_BRANCH_ID_idx" ON "CLINICS"("HOSPITAL_ID", "BRANCH_ID");
CREATE INDEX IF NOT EXISTS "CLINICS_DEPARTMENT_ID_idx" ON "CLINICS"("DEPARTMENT_ID");

CREATE TABLE IF NOT EXISTS "DOCTORS" (
    "DOCTOR_ID" INTEGER NOT NULL,
    "DOCTOR_NAME" VARCHAR(255) NOT NULL,
    "DOCTORS_TYPE" VARCHAR(100),
    "QULIFICATION" VARCHAR(255),
    "GLOBAL_DOCTOR_ID" INTEGER,
    CONSTRAINT "DOCTORS_pkey" PRIMARY KEY ("DOCTOR_ID")
);

-- Extend WARDS with optional legacy location columns
ALTER TABLE "WARDS" ADD COLUMN IF NOT EXISTS "DESCRIPTION" VARCHAR(500);
ALTER TABLE "WARDS" ADD COLUMN IF NOT EXISTS "HOSPITAL_ID" INTEGER;
ALTER TABLE "WARDS" ADD COLUMN IF NOT EXISTS "BRANCH_ID" INTEGER;
ALTER TABLE "WARDS" ADD COLUMN IF NOT EXISTS "DISCONTINUE_FLAG" VARCHAR(10);

CREATE INDEX IF NOT EXISTS "WARDS_HOSPITAL_ID_BRANCH_ID_idx" ON "WARDS"("HOSPITAL_ID", "BRANCH_ID");
