-- Doctor consultation encounters (payment-gated start from TRIAGE queue)

CREATE TABLE IF NOT EXISTS "ENCOUNTERS" (
    "ENCOUNTER_ID" SERIAL NOT NULL,
    "PERSON_ID" INTEGER NOT NULL,
    "TRIAGE_ID" INTEGER NOT NULL,
    "DOCTOR_ID" INTEGER NOT NULL,
    "STATUS" VARCHAR(50) NOT NULL DEFAULT 'In Consultation',
    "CHIEF_COMPLAINT" TEXT,
    "HISTORY" TEXT,
    "EXAMINATION" TEXT,
    "ASSESSMENT" TEXT,
    "PLAN" TEXT,
    "VERSION" INTEGER NOT NULL DEFAULT 1,
    "STARTED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "COMPLETED_AT" TIMESTAMP(3),
    "OUTCOME" VARCHAR(255),
    "CREATED_BY_ID" INTEGER,
    "CREATED_BY" VARCHAR(100),
    "CREATED_DATE" TIMESTAMP(3),
    "UPDATED_BY_ID" INTEGER,
    "UPDATED_BY" VARCHAR(100),
    "UPDATED_DATE" TIMESTAMP(3),

    CONSTRAINT "ENCOUNTERS_pkey" PRIMARY KEY ("ENCOUNTER_ID")
);

CREATE UNIQUE INDEX IF NOT EXISTS "ENCOUNTERS_TRIAGE_ID_key" ON "ENCOUNTERS"("TRIAGE_ID");
CREATE INDEX IF NOT EXISTS "ENCOUNTERS_PERSON_ID_idx" ON "ENCOUNTERS"("PERSON_ID");
CREATE INDEX IF NOT EXISTS "ENCOUNTERS_DOCTOR_ID_idx" ON "ENCOUNTERS"("DOCTOR_ID");
CREATE INDEX IF NOT EXISTS "ENCOUNTERS_STATUS_idx" ON "ENCOUNTERS"("STATUS");
CREATE INDEX IF NOT EXISTS "ENCOUNTERS_STARTED_AT_idx" ON "ENCOUNTERS"("STARTED_AT");

DO $$ BEGIN
  ALTER TABLE "ENCOUNTERS" ADD CONSTRAINT "ENCOUNTERS_PERSON_ID_fkey"
    FOREIGN KEY ("PERSON_ID") REFERENCES "PERSONS"("PERSON_ID") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "ENCOUNTERS" ADD CONSTRAINT "ENCOUNTERS_TRIAGE_ID_fkey"
    FOREIGN KEY ("TRIAGE_ID") REFERENCES "TRIAGE"("TRIAGE_ID") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "ENCOUNTERS" ADD CONSTRAINT "ENCOUNTERS_DOCTOR_ID_fkey"
    FOREIGN KEY ("DOCTOR_ID") REFERENCES "USERS"("USER_ID") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
